### ISSUE TITLE
property 訳(1)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#650]
```
http://docs.python.jp/2.7/library/functions.html#property
http://docs.python.jp/3.3/library/functions.html#property

  This makes it possible to create read-only properties easily
  using property() as a decorator:

部分の訳「これにより、」部分。「This」は単に property 
全体を指すと思われます。
つまり、本来原文は改行されているべきであった、とみる��
�き。「doc がもし与えられた
ならば云々、これにより」ではないですね。3.3訳から「こ��
�により、」丸々省いてしまっては。

  property() をデコレータ (decorator) として使い、読み取り専用プロパティを容易に作れます:

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 25 Sep 2013 at 9:58

**Comment by artakase** [comment]
https://bitbucket.org/pydocja/py27/commits/92c92e7264831054491311a803f269f4a81a096d
更新によって読み取り専用 property の例の後にドキュメント文字列への言及が入ったため、この文の意味がより分かりやすくなりました。「This makes it possible to」は控えめに「そのため、」と訳しておきました。

**Comment by hhsprings** [comment]
GoogleCodeExporter からの auto-migrate だと issue あげた本人にも更新通知が届かない…だけでなくなんとなく songofacandy さんのツッコミにも反応すればいいのにしてこなかったので、ひょっとしたらこの issue をどう扱うべきか決めかねている、というのもあります? songofacandy さんのご指摘どおりで、ワタシの誤解と思います、元々の話は。ので Close しちゃってください。というかなんかワタシの誤解がいつまでも残ってると晒し者な気分 (^^;
