### ISSUE TITLE
round 訳とシグニチャ

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#654]
```
http://docs.python.jp/2.7/library/functions.html#round

  Values are rounded to the closest multiple of 10 to the power minus ndigits;

部分。3.3訳が正解です。

  値は 10 のマイナス ndigits 乗の倍数の中で最も近いものに丸められます
  　　　　　　　　　　　　　　^^
また、シグニチャは

  round(number[, ndigits])

# round の仕様って、2.7と3.xで違うんですね…

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 26 Sep 2013 at 12:49

**Comment by artakase** [comment]
シグニチャは修正しようか迷いましたが、
どうせ (原文) をクリックしたら最新の原本に飛ぶので、新しい方に合わせることにしました。
しくじってコミット 2 つに分かれてしまいましたが、修正しました。
https://bitbucket.org/pydocja/py27/commits/92c92e7264831054491311a803f269f4a81a096d
https://bitbucket.org/pydocja/py27/commits/6d198256b9d7171ac70bf763d92484636b8e72f0
