### ISSUE TITLE
PyString_Format の arg 引数

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#657]
```
http://docs.python.org/2.7/c-api/string.html#PyString_Format

see http://bugs.python.org/issue19163

多分原文が実態と乖離してます。引数 arg 
は「タプルでなければなりません」
ではないと思います。

# 本家トラッカーの反応を見守ってから…

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 4 Oct 2013 at 11:18

**Comment by methane** [comment]
Transifex みたら c-api--string の翻訳率50%程度だなぁ。

**Comment by hhsprings** [comment]
rst での訳があるものについては、C API とライブラリ以外をまず100%にしました。時間みつけて少しずつやっていこうかなとは思ってました。未訳部分をみると実際かなり下らない差異(一番多いのは rst マークアップだけが変わったようなもの)もあって、本気でそこだけに集中すればそんなに大変でもなかったりもするんですけどね…。

何か問題をみつけたものに対して「rst を直す従来のやり方が早いか頑張って PO 化するか」都度選択するしかないのかなとも思ってはいました。PO 化が理想ではありますが、大変な作業なのも確かで。

**Comment by methane** [comment]
C API を見るのは玄人だけなので、 Tutorail やよく使うライブラリに比べると邦訳の重要性は低いです。
一方正確性は損ない、翻訳を見た人が躓いて時間を無駄にした上で結局原文に当たらないといけないようではこのプロジェクト自体の意味がなくなります。

ということで、 C API に関しては、翻訳率に関わらず強制的に po 化してしまうという選択肢も…

**Comment by hhsprings** [comment]
C API を強制的に po 化、は、読者の立場としては賛成出来ます。問題にしているのが 2.7 の話なので、翻訳参加者が気が散ることがないようにだけは誘導して欲しいとは思います。未訳があると手を出したくなるのが性と思うので。やはり主は 3 系でそちらに集中すべきと思うので。Wiki に作業優先度を書くとかですかねぇ。(What's old に手を出してるのも実はそれもあります。翻訳率が低いのが永遠に残ってると気が散る上にモチベーションも下がっていきそうな気がして。)

**Comment by hhsprings** [comment]
Transifex で 100% にした上で、元の課題「The *args* argument must be a tuple or dict.」の対応しました。

**Comment by methane** [comment]
c-api/string.rst を原文に差し替えました。
次のビルドから Transifex ベースに移行するはずです。
