### ISSUE TITLE
PyExc_BufferError 説明の抜け

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#659]
```
http://docs.python.jp/2.7/c-api/exceptions.html#standardexceptions

http://bugs.python.org/msg199458

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 11 Oct 2013 at 10:05

**Comment by methane** [comment]
これまだ本家の 2.7 でも直ってないですね

**Comment by hhsprings** [comment]
もともと本家にもワタシ issue あげてた (2013 年らしい) んですが、昨日これのパッチあげてくれた人がいます(　http://bugs.python.org/issue19225 )。

**Comment by cocoatomo** [comment]
2つ目のパッチが出て以降動きが無いんですね.
これは誰に振ると話が進むのだろう?

**Comment by methane** [comment]
pull request 送ると話が進みます。
他人が書いたパッチの場合は、まずその issue でパッチ作者に would you create a pull request? とか聴いて、作者からの許可がもらえるか、1週間くらい反応が無かったら代理で pull request 投げていいです。
(git の author をできるだけパッチ作者にしたいので、確認なしに勝手にプルリクエストにするのはあまりよくないです。)

**Comment by cocoatomo** [comment]
雑な文章だけどコメントしておきました.
http://bugs.python.org/issue19225?@ok_message=msg%20289196%20created%0Aissue%2019225%20nosy_count%2C%20nosy%2C%20messages%2C%20message_count%20edited%20ok&@template=item#msg289196

**Comment by cocoatomo** [comment]
(操作間違えました)

**Comment by cocoatomo** [comment]
master に対して PR 投げました. https://github.com/python/cpython/pull/881

3.5 とか 2.7 用にするには修正必要だけど, それはコミッターが何とかしてくれるもの?

**Comment by methane** [comment]
今のところbackportは全部手作業（Misc/NEWSが新しい仕組みになったら自動化される予定）です。
放って置いてもコミッターがするし、送ってくださってももちろんOKです。

http://cpython-devguide.readthedocs.io/committing.html#backport-and-cherry-pick-labels

個人的には cherry_picker.py はまだ使う価値が無くて、普通に `cherry-pick -x コミット` でOK

**Comment by cocoatomo** [comment]
backportを作成

2.7 → https://github.com/python/cpython/pull/964
3.5 → https://github.com/python/cpython/pull/965
3.6 → https://github.com/python/cpython/pull/966

3.6 はマージ済み, 3.5 はマージ待ち, 2.7 は単純な cherry-pick では済まなかったのでレビュー待ちです.

**Comment by cocoatomo** [comment]
無事に全部マージされました。

次回の原文の更新で反映されます。
