### ISSUE TITLE
calendar.Calendarクラスのメソッドがモジュール関数として説明されてしまっている

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#676]
```
URL、あるいはファイル名は？
  https://docs.python.org/2.7/library/calendar.html
どんな問題ですか？
  ドキュメントのインデントがおかしい? たとえば itermonthdays という
  モジュール関数は存在せず、正しくは calendar.Calendarクラスのメソッド。

  # 誤訳しようがない内容なので、かつて原文が間違っていた、とかですかね。
  # 原文は実態と合ってます。

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 16 Apr 2014 at 6:00

**Comment by artakase** [comment]
修正しました。
https://bitbucket.org/pydocja/py27/commits/c31cd90c5c77a42e0e021d41906810e88ba719c7

翻訳版の rst におけるインデントが、原文のrstと異なるために起きた問題でした。
