### ISSUE TITLE
codecs.encode、codecs.decode ドキュメントの抜け

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#678]
```
http://docs.python.jp/2.7/library/codecs.html

codecs.encode、codecs.decode ドキュメントの抜け。
(原文の問題。 http://bugs.python.org/issue17827 、2.7.7でFIX。)

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 18 Jul 2014 at 12:26

**Comment by artakase** [comment]
Fixed via https://bitbucket.org/pydocja/py27/commits/48d06135abcd17b7ebc28ccdc3f9976c3fac905d
