### ISSUE TITLE
「(原文)」へのリンクの誤り

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#679]
```
URL、あるいはファイル名は？

どんな問題ですか？



```

Original issue reported on code.google.com by `cabezon....@gmail.com` on 21 Jul 2014 at 2:20

**Comment by artakase** [comment]
https://bitbucket.org/pydocja/cpython-ja/commits/97212ae86deeee231e356c3631ae2e2c8ec0d061
にて修正しました。

**Comment by methane** [comment]
ありがとうございます。
