### ISSUE TITLE
typo: Python 2.7ja1 document

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#680]
```
以下のURL中の「予約済みの識別子種」の説明中にtypoと思わ�
��き場所があります

http://docs.python.jp/2.7/reference/lexical_analysis.html

「あらゆる __*__ 
の名前の利用は、文脈に関わらず、明示的に記録されまな��
�ので、警告無く損害に合う危険に晒すことになります。」

とありますが、おそらく「明示的に記録されないので」が��
�しい(「ま」が余分）。



```

Original issue reported on code.google.com by `mokuno.m...@gmail.com` on 23 Jul 2014 at 3:53

**Comment by artakase** [comment]
Fixed via https://bitbucket.org/pydocja/py27/commits/d9f66022795ec0bff3e40c159e6feb9e5a1c1b46

typoどころか、完全な誤訳でした。
\_\_init\_\_() メソッドの定義のようなドキュメントに書いてある使い方をするなら問題ないよ、という内容でした。
