### ISSUE TITLE
jsom

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#687]
```
http://docs.python.jp/2.7/library/configparser.html

jsom モジュールは、同じ目的に利用できる JavaScript 
の文法のサブセットを実装しています
^^^^

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 17 Feb 2015 at 2:04

**Comment by artakase** [comment]
Fixed via https://bitbucket.org/pydocja/py27/commits/34d8b76856d626a79326637b19c1c570463e0d61
3.x のドキュメントもTransifex上で同様に修正しました。
