### ISSUE TITLE
structモジュールのドキュメント間違いに関して

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#688]
```
http://docs.python.jp/2.7/library/struct.html


7.3.2.2. 
フォーマット文字で"h"の標準サイズが1になっているが
2の間違いではないでしょうか?

3.4のマニュアルは間違っていないようでした
```

Original issue reported on code.google.com by `shoujihi...@gmail.com` on 21 Feb 2015 at 5:02

**Comment by osamu0329nakamura** [comment]
bitbucket のほうにPR投げましたので対応をお願いします。
https://bitbucket.org/pydocja/py27/pull-request/2/fix-693-683-688-698/diff
