### ISSUE TITLE
_winreg.QueryValueEx(key, value_name)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#689]
```
http://docs.python.jp/2.7/library/_winreg.html#_winreg.QueryValueEx

-----
The result is a tuple of 2 items:

Index	Meaning
0	The value of the registry item.
-----
なので、
誤：「0	レジストリ要素の名前。」
正：「0 レジストリ要素の値。」

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 21 Feb 2015 at 7:35

**Comment by artakase** [comment]
Fixed via https://bitbucket.org/pydocja/py27/commits/53c29a1307275f0031bb546cded125ad0cb41bf3
3.x のドキュメントもTransifex上で同様に修正しました。
