### ISSUE TITLE
「Tools/scripts/ftpmi rror.py」（余分な空白）

### ISSUE THREAD

**Issue by GoogleCodeExporter** [python-doc-ja/python-doc-ja#698]
```
http://docs.python.jp/2.7/library/ftplib.html#ftplib.all_errors 
の下の「参考」内。

```

Original issue reported on code.google.com by `xwhhspri...@gmail.com` on 11 May 2015 at 6:04

**Comment by osamu0329nakamura** [comment]
bitbucket のほうにPR投げましたので対応をお願いします。
https://bitbucket.org/pydocja/py27/pull-request/2/fix-693-683-688-698/diff

**Comment by methane** [comment]
報告ありがとうございます。

これ、誤訳じゃなくて、単に翻訳の原文 (2.7.2) と現在の英語のドキュメント (2.7.10) の差分ですね。

セキュリティに関わる部分なので（だからこそマイクロバージョンで挙動が変わる修正が入った）、2.7.2 のまま放置するよりは修正するべきだとは思うのですが、ちょっと 2.7 系のドキュメントの更新どうするか考えるので少しお待ち下さい。

**Comment by methane** [comment]
一応 2.7.2 の原文を確認しておきました。

```
.. attribute:: FTP_TLS.ssl_version

   The SSL version to use (defaults to *TLSv1*).
```

**Comment by methane** [comment]
merged
