### ISSUE TITLE
README ダウンロードのリンク切れ

### ISSUE THREAD

**Issue by osamu0329nakamura** [python-doc-ja/python-doc-ja#700]
READMEの以下の２つのリンクが切れています。対応するまでの間は、READMEに移行中ですと記載してはどうでしょうか？

ダウンロードする
http://code.google.com/p/python-doc-ja/downloads/list

古いドキュメント
http://www.python.jp/pub/doc_jp/

**Comment by methane** [comment]
一旦消しました。
