### ISSUE TITLE
(2.7) 20.8.2. FTP_TLS Objects の原文との乖離

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#701]
原文は
```
FTP_TLS.ssl_version
    The SSL version to use (defaults to ssl.PROTOCOL_SSLv23).
```

日本語訳は
```
FTP_TLS.ssl_version(原文)
    使用する SSL のバージョン (デフォルトは TLSv1) です。
```

デフォルト値が違うのも問題ですが、それよりもモジュール変数「ssl.～」にたどり着けないのが…。

**Comment by methane** [comment]
あれ、これどっかでマージしたような…

**Comment by methane** [comment]
https://bitbucket.org/pydocja/py27/commits/91f7dcf47edfd6ff641e367b3e3db0cd985599f4

**Comment by hhsprings** [comment]
あ、すいません…、新しいのを見つけたついでに、と思って、あまり確認せずに入れてしまいました。

**Comment by methane** [comment]
サイトにも反映されてますね。
http://docs.python.jp/2/library/ftplib.html#ftplib.FTP_TLS.ssl_version

**Comment by hhsprings** [comment]
なんか失礼しました

**Comment by methane** [comment]
いえいえ。報告感謝です。
