### ISSUE TITLE
「7.1.4. テンプレート文字列」のTemplateの使い方の例

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#702]
原文で「Here is an example of how to use a Template::」とコロンふたつで code block に入っているところ、日本語訳で「Templateの使い方の例を以下に示します:」とコロンが一つのため、pycon のハイライトになってません。

**Comment by methane** [comment]
Fixed via https://bitbucket.org/pydocja/py27/commits/67dd1470920296950530e730d59602ec8d8d0ea5
