### ISSUE TITLE
urllib.request.install_opener()  の誤訳

### ISSUE THREAD

**Issue by inoshiro** [python-doc-ja/python-doc-ja#703]
以下の文章に誤訳がありました。

> 標準で URL を開くオブジェクトとして OpenerDirector のインスタンスをインストールします。 このコードは引数が本当に **urlopen() のインスタンス**であるかどうかはチェックしないので、適切なインタフェースを持ったクラスは何でも動作します。
http://docs.python.jp/3.4/library/urllib.request.html#urllib.request.install_opener

原文は下記。

> Install an OpenerDirector instance as the default global opener. **Installing an opener is only necessary if you want urlopen to use that opener; otherwise, simply call OpenerDirector.open() instead of urlopen(). The code does not check for a real OpenerDirector, and any class with the appropriate interface will work.**
https://docs.python.org/3.4/library/urllib.request.html#urllib.request.install_opener

誤りは2点。

* 文が一つ抜け落ちている
* チェックするのは urlopen() のインスタンスかどうかではなく、OpenerDirectorのインスタンス

抜け落ちている文の翻訳はこんな感じでしょうか。
> 指定の opener を用いた urlopen を使う必要がある場合にのみ opener をインストールしてください。そうでない場合は単純に urlopen() の代わりに OpenerDirector.open() を呼んでください。

インスタンスの誤りを修正した文です。
> このコードは引数が本当に **OpenerDirector** のインスタンスであるかどうかはチェックしないので、適切なインタフェースを持ったクラスは何でも動作します。」

ついでに最初の一文も改善出来そうです。
> OpenerDirector のインスタンスをモジュールが標準で用いるグローバルなオープナーとしてインストールします。

コードを読んでみたところ、install_opener() はモジュール全体で使うオープナーを置き換える動作をするようなので、このような訳が適切かと思います。

**Comment by inoshiro** [comment]
2.7では一文抜けているものの、インスタンスはOpenerDirectorになってますね。
http://docs.python.jp/2/library/urllib2.html#urllib2.install_opener

**Comment by methane** [comment]
Transifex の方 (3.4) で、以下のように訳文を修正しました。

```
指定された :class:`OpenerDirector` のインスタンスを、デフォルトで利用されるグローバルの opener としてインストールします。
opener のインストールは、 urlopen にその opener を使って欲しいとき以外必要ありません。普段は単に :func:`~urllib.request.urlopen` の代わりに :meth:`OpenerDirector.open` を利用してください。
この関数は引数が本当に :class:`OpenerDirector` のインスタンスであるかどうかはチェックしません。適切なインタフェースを持った任意のクラスを利用することができます。
```

**Comment by methane** [comment]
Python 2.7 の方でも同じように修正しました
