### ISSUE TITLE
「20.8. ftplib — FTPプロトコルクライアント」の「ftplib モジュールを使ったサンプル」

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#704]
かなりしょうもない内容であって、なおかつ根本的に原文がおそらく 2.7.2 以降に更新されていて乖離している、ということもあるのですが。

訳文で「# ユーザ名 anonymous、パスワード anonyumou」がコメント、実行結果が「s@」となっているので物凄く違和感あったのですが、これ、
```
>>> ftp.login()                     # user anonymous, passwd anonymous@
'230 Login successful.'
```
ですよね。(s@の前に誤って改行が入り、なおかつ「'230 Login successful.'」が抜けた…?)

原文の最新に追従するのはともかくとして、「s@」と「'230 Login successful.'」は修正してあったほうがよいかなぁと思います。

**Comment by methane** [comment]
fixed.
