### ISSUE TITLE
typo condiction -> condition

### ISSUE THREAD

**Issue by sacrada** [python-doc-ja/python-doc-ja#705]
http://docs.python.jp/3.3/tutorial/datastructures.html#tut-conditions
http://docs.python.jp/2.7/tutorial/datastructures.html#tut-conditions
http://docs.python.jp/2.6/tutorial/datastructures.html#tut-conditions
http://docs.python.jp/2/tutorial/datastructures.html#tut-conditions

#695 と同様の案件ですが、closeとなっていたので。
「5.7. 条件についてもう少し」の冒頭文の「condiction」は、「condition」の誤りだと思われます。

**Comment by osamu0329nakamura** [comment]
3.4 のドキュメントしか確認できていませんでした。すいません。

Transifex上はpy33バージョンも、conditionに修正しているんですが、3.4版しか反映されていませんね。
py27についてはbitbucket上でPRあげました。
py26以前はどこを修正すればよかったか分からなかったため、未着手です。

**Comment by methane** [comment]
翻訳の人的リソースが足りてないので、最新安定版 (いまなら 3.4) にリソースを集中するという方式をとっています。
ただし、 Python 2.7 は Python 史上初の LTS なので、誤訳の修正や本家への追従は指摘された範囲で続けようと思います。

2.6, 3.3 は、「これは古いバージョンです」みたいなリンク出して新しいバージョンに誘導するか、
いっその事Webから消してしまったほうがいいかもしれません。
