### ISSUE TITLE
http://docs.python.jp/2.7/library/cgi.html#cgi.parse の原文からの乖離

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#706]
翻訳で「環境変数、またはファイルからからクエリを解釈します」と言っているのに環境変数を受け取らないシグニチャになっており、また、CGI なので環境変数みてくれるはずなのでヘンだなぁと思ったら、原文から乖離してました：

```
.. function:: parse(fp[, environ[, keep_blank_values[, strict_parsing]]])

   Parse a query in the environment or from a file (the file defaults to
   ``sys.stdin`` and environment defaults to ``os.environ``). 
   The *keep_blank_values* and *strict_parsing* parameters are
   passed to :func:`urlparse.parse_qs` unchanged.
```
シグニチャと「ファイルは標準で sys.stdin になります」部分だけですね。

    (ファイルは標準で ``sys.stdin``、環境変数は標準で ``os.environ`` になります)

3.xでも同じなんですが、3.x は今度は原文が間違ったままです：
http://docs.python.jp/3.4/library/cgi.html#cgi.parse

本家に言った方がいいかも…。

**Comment by artakase** [comment]
2.7 の該当箇所を追加しました。
https://bitbucket.org/pydocja/py27/commits/c13837e3f4c81174f6d0ef4478a08546c2d8bf60

また、3.x の原文が更新され、環境変数を受け取る変数およびそのデフォルトが environ=os.environ として追記されたので、こちらも正しくなりました。
