### ISSUE TITLE
Python 3.x の footer、サイドバーのリンクが google code のまま

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#707]
気付いておられるかもしれませんが、

  https://bitbucket.org/pydocja/cpython-ja/src/f23bac72cb9facbb959f6544a8b8c2e6f65d2c26/Doc/tools/templates/layout.html?at=3.4
  https://bitbucket.org/pydocja/cpython-ja/src/f23bac72cb9facbb959f6544a8b8c2e6f65d2c26/Doc/tools/templates/indexsidebar.html?at=3.4

テンプレートが google code を指したままになっています。

**Comment by methane** [comment]
fixed
