### ISSUE TITLE
Transifex上に存在する訳語がドキュメントに反映されていない

### ISSUE THREAD

**Issue by FGtatsuro** [python-doc-ja/python-doc-ja#708]
「Python 標準ライブラリ」の「5. 組み込み例外」に一部訳されていない部分が表示されていました。
http://docs.python.jp/3.4/library/exceptions.html#bltin-exceptions

```
The built-in exception classes can be subclassed to define new exceptions; programmers are encouraged to derive new exceptions from the Exception class or one of its subclasses, and not from BaseException. More information on defining exceptions is available in the Python Tutorial under ユーザー定義例外.
```

翻訳してみようと思いTransifex上の該当ページを開いたのですが、既に対応する部分の翻訳は成されているようでした。
https://www.transifex.com/projects/p/python-34-ja/viewstrings/#ja/library--exceptions/27249955

事象が発生する原因は分からなかったため、issueを登録するに留めさせて頂きます。

**Comment by artakase** [comment]
3.4がリリースされてから、この部分の原文が更新されているようです。
https://bitbucket.org/pydocja/cpython-ja/diff/Doc/library/exceptions.rst?diff2=8dc1b45bd467&at=3.4

対して、Transifex上ではこの原文が更新されていないので、新しい原文に古い翻訳が適用できず、翻訳されていないドキュメントが表示されてしまうのだと考えられます。

**Comment by FGtatsuro** [comment]
コメントありがとうございます。
このような場合は原文の更新が必要なのですね。
