### ISSUE TITLE
Python3.5対応

### ISSUE THREAD

**Issue by iku000888** [python-doc-ja/python-doc-ja#711]
タイムリーな話題なのでIssueあげてみました。
3.4の翻訳完了後でしょうか。

**Comment by methane** [comment]
3.4 の翻訳完了を待つつもりはないですが、 x.y.0 リリース直後は本家のドキュメントの方も
多くの人の目に止まり始めたばかりでドタバタしてるので、あまり急いでも居ない感じです。
半年は長過ぎると思うので、3ヶ月以内位をめどにします。

**Comment by iku000888** [comment]
丁寧なご回答ありがとうございます！
オフトピックもいいところですが、3.4で翻訳されたものの再利用等の仕組みが気になっています。
もしよろしければそのあたりも教えていただけたりしますでしょうか？

**Comment by methane** [comment]
翻訳は Transifex で行っているのですが、 Transifex に翻訳メモリという機能があります。
これは原文と訳文の対を管理するもので、同じ原文があれば自動的に同じ訳文が適用されます。
なので、 3.4 と 3.5 で翻訳メモリを共有すれば、変化がない部分の翻訳はそのまま引き継がれます。

また、少しだけ修正された場合は未訳になりますが、その場合も Web インターフェイスで翻訳していれば
類似度が高い原文を自動で見つけてきて表示してくれるので、変化があった部分だけ修正してあとは使いまわすことが可能です。

これは、 3.4 -> 3.5 の場合だけでなく、同じバージョンのドキュメントの中でも定型的な言い回しがあれば
suggest してくれる場合があるので、日本語側の表現の揺れを減らすのにも役立ちます。

**Comment by methane** [comment]
3.5.1 も出たということで、ギリギリですが予定通り年内に 3.5 の翻訳を開始しました。
