### ISSUE TITLE
「Parse a URL into six components, returning a 6-tuple」について

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#712]
http://docs.python.jp/2.7/library/urlparse.html#urlparse.urlparse
  http://docs.python.jp/3.3/library/urllib.parse.html#urllib.parse.urlparse

「6 要素のタプルを返」すわけではないのですよね、「タプルもどき」ではあるにせよ：

```pycon
>>> import urlparse
>>> pr = urlparse.urlparse("http://localhost:8000/examplefiles/termcap;par?style=emacs")
>>> pr
ParseResult(scheme='http', netloc='localhost:8000', path='/examplefiles/termcap', params='par', query='style=emacs', fragment='')
>>> type(pr)
<class 'urlparse.ParseResult'>
>>> pr[0]
'http'
>>> tuple(pr)
('http', 'localhost:8000', '/examplefiles/termcap', 'par', 'style=emacs', '')
```

Sequence Types として振舞うので「タプル」は全く嘘ではないですし直後のスニペットから自明であって、この問題で混乱する人は誰一人いないと思います。ので、特に修正する必要はないかなぁ、という気もしますが、こうやって記録は残る価値はあるとは思うので、一応上げとくことにしました。(私も別に混乱したとかではなくて、直後のスニペットと説明が合ってない気がして気になっただけの、些細な違和感でしかなかったです。)

正直かなりどうでも良いことと思うので、このまま何も措置せずクローズ、でも良いかと思います。(それでも issue には残るのでそれで良いかと。)

**Comment by hhsprings** [comment]
あ、すいません、下の方に tuple のサブクラスであることの説明、書いてありました。

**Comment by hhsprings** [comment]
原文の最初のスニペットがマズいんだろうなぁ。ここで tuple 的な使い方をしてれば…。

**Comment by methane** [comment]
純粋な tuple として利用する必要がある場面もないので、例はそのままで良いと思います。
少しでもわかりやすくするなら最初から 6 tuple じゃなくて named tuple described below. と書けば
良いのかもしれません。とりあえず翻訳プロジェクトとしては close します。
