### ISSUE TITLE
(?P<name>...)の説明

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#713]
[7.2.1. 正規表現のシンタクス](https://docs.python.org/2.7/library/re.html#re-syntax)の「(?P&lt;name&gt;...)」について。

余力があれば(ないとは思いますが)…。

原文のほうのアップデート、なのですかね? 結構内容違ってます。「たとえば、もしパターンが」部分を表で説明するようにした、ということでしょうか。(Python 3 ドキュメントからのバックポート、のようにもみえます。というかおそらくそう。)

Python 2x でのマイクロバージョンの更新については人によって考え方が違うようですので、方針はお任せします。表になって格段にわかりやすくなった、「だけ」で、言ってる内容は変わらないように思いますので。

**Comment by methane** [comment]
Python 2 系までは Transifex を使ってないので、原文の更新への対応は原文の diff を取って
手作業でやってました。とてもパワーが必要なので、 Python 3 系に比べて今後レガシーになる
ばかりの Python 2 でそこまでやる気力は無いです。

とはいえ、原文の方も意味があって修正されているはずなので、特に 2.7 は他のバージョンと異なり
ある程度新機能の追加もされたりしているので、指摘された箇所はその重要度に応じて個別に
だれかが対応していきます。

この件は特に元の原文＆翻訳に間違いがあったとか、 Python 2.7.10 のアップデートで変更された
とかではないので、本当にだれかが気が向いたらという感じになると思います。

**Comment by hhsprings** [comment]
> この件は特に元の原文＆翻訳に間違いがあったとか、 Python 2.7.10 のアップデートで変更された
> とかではないので、本当にだれかが気が向いたらという感じになると思います。

それでよいと思います。

というか毎度指摘あげるたびに、自分でやってしまおうかとも思うんですが、なかなかこっちに力割けなくて、協力できなくて申し訳ないなぁと思ったりもしてます。逆に私のほうも「余力があって気が向いた」ときにでも、対応しようかなと思います。(やりかたまだわかってないですが、2.7系だと Fork して PR 投げれば良いのですかね。)

**Comment by hhsprings** [comment]
[PR](https://bitbucket.org/pydocja/py27/pull-requests/5/713-_-fix/diff)上げときました。「気が向いたら」なんて言ってるとやらないと思うので。

PR の説明にも書きましたけど、「the ``repl`` argument of ``re.sub()``」は素直に「re.sub に渡す repl 引数」と思います。が、現状で 2.7～3.5 まで原文が全く同じなので 2.7 だけ勝手に直すのもアレと思って、ひとまずそのままにしてあります。

**Comment by methane** [comment]
Transifex の library--re が 85% なのでまだ Transifex 化してないのですが、どうしましょう？

**Comment by hhsprings** [comment]
あれ? 2.7 の library-re は 100% になってません? ここはまっさきに 100% にしたつもりだったんですけど。

**Comment by methane** [comment]
Sphinx のアップデートかなにかで翻訳対象が追加されてたみたいです。
未翻訳を見たら全部記号だったので、かたっぱしから原文コピーして保存していきました。
リポジトリの方は re.rst は既に原文に置き換えていた (=Transifex 化していた)ので、 「Transifex化していない」は間違いでした。

**Comment by methane** [comment]
てことでこの issue は close できますね。
