### ISSUE TITLE
3.4 以降の base64 モジュールの「原文の」問題(+ stdtypes)

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#714]
issue というよりは報告と質問、という感じなのですけれど、base64 (と stdtypes)に rst の原文の問題があって、 [issue25706](http://bugs.python.org/issue25706) あげたら1時間ちょいで対応してもらえました。指摘したのは base64 モジュールについてだけだったんですけど、stdtypes にも同じ問題があったようで、一緒に直したみたいです。

ここからは質問です。このように原文が更新された場合、翻訳プロジェクトの原文の更新って、どうなるんでしょう? 何か明示的なアクションって出来ますか? (Transifex は一週間ほど前に始めたばかりでまだあまり熟知出来てません。) それとも単に待てば良い?

**Comment by hhsprings** [comment]
c-api/arg.rst もですね。どうやって見つけたんだろう? grep で見つかるようなもんでもなかろうに…。

**Comment by methane** [comment]
Python 3.4 を放置して 3.5 で最新版の pot を上げたのでそちらで対応をおねがいします。

**Comment by hhsprings** [comment]
発端の issue としては close してしまいます。(今見返したら対応箇所そのものは未訳になっていたりする。マイナーバージョンがあがって原文が更新された? のかあるいはワタシがそのときに作業をしないままだったのか…。後者ならチョンボだなぁ…。)
