### ISSUE TITLE
about.rst (2.7) の issue tracker の指し先

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#716]
[2.7 翻訳の(部分的)Transifex](https://bitbucket.org/pydocja/py27/pull-requests/6/logging-gettext/)を記念して…、ちょっと今後の作業の練習も兼ねて about を更新してみたのですが、ここも issue tracker の指し先が Google Code を指したままでした。

ので、[Transifex](https://www.transifex.com/python-doc-ja/python-27/translate/#ja/about/)に新しいものを入れてみました。(3系は about に入れてるのではないのですね。一応旧訳を尊重して括弧で訳注する形にしましたが。)

**Comment by hhsprings** [comment]
あら? 「稲田さんも訳した」と Transifex で警告受けます。何が起こってるんでしょう?

**Comment by hhsprings** [comment]
あ、「Download for use」で持ってきて上書きアップロードしてしまったからか…。次からはちゃんとロックします。この警告、どうやって消せばいいのでしょうね?

**Comment by methane** [comment]
多分時間が経てば消えると思います。

Transifex 昨日は調子悪かったみたいなのでまだ様子見中

**Comment by artakase** [comment]
ちょっと気になったのですが、Transifex のロック機能は今も存在しているのでしょうか？
翻訳用にダウンロードしても、ロック中の表示が出なくなったような気がします。

**Comment by hhsprings** [comment]
警告は消えました。Transifex は昨晩いっぱい使えなかったですが、今日は「やや不調」程度で一応使えてます。

ところでどなたかが 3.4 po を 2.7 に上書きしませんでした? msgid がたまたま一致してればいいんですが、2.7 とはまったく合わないものもあるので、この作業はマズいんじゃないかと思いますが。

**Comment by methane** [comment]
翻訳済みの po ファイルについては何もしてません。
pot ファイルは、翻訳メモリからの翻訳適用がアップロード時に起こるのではないかと思い
再度アップロードしたので、そのせいかもしれません。

**Comment by methane** [comment]
翻訳メモリからの適用については、やはりアップロード時に行われるようで、
しかも変化のないファイルのアップロードではダメみたいでした。

初回アップロード後に他のプロジェクトとの翻訳メモリの統合を行ったので
なかなか適用されていなかったのですが、サポートに連絡して実行してもらいました。
今は70%以上が翻訳されてますね。
@hhsprings さんに更新していただいた物以外にも、翻訳率が98%以上のファイルは
po 化しても良いかもしれません。。。

**Comment by hhsprings** [comment]
翻訳率が98%以上のファイルの po 化、賛成です。急に翻訳率があがって驚いたですが、ワタシも 100% になったものなら乗り換えてしまえばいいよな、と思ってました。c-api が割と 100% になりましたね。稲田さんはじめメンバの方には手間かけさせてしまっているな、と最初思っていましたが、結果としては Transifex のおかげで、今後劇的に負荷を減らすことに貢献出来た気がしています。もう 2.7 には時間かけたくないですよね、出来るだけ。(今時点で 2.7 は 72%、3.4 は 77% ですね。)

ところで「2.7 メンテナンスリリースでの更新」に関係するものを手動で保守しながら「自動で取り込まれた」ものとの差異をみていると、ところどころ 3 系での誤訳を見つけているので、ときどき 2.7 と 3 系の差異を見たほうがいいだろうと思っています。(po 化で原文に更新したものについてはレポジトリの rst を復元して、となるでしょうけど。)

昨日実施した urllib2 が 3系から取り込んだ訳では 2.7 で正しく訳出出来ていたのに「誤訳に直されていた」のを発見しました。前に「make sure」の訳について指摘したことがある気がしますが、どうもわざわざ「確認する」に直していたようで。2.7 urllib2 では元の正しい訳を採用しています。また、3 系に「コピー」する際に、rest が反応するマークアップを意識せずに空白を取り去っているものが結構ありました。「``」や「*」の前後にあった空白がなくなっているなど。かなりの量気付いてますが、量が多かったので 3 系ではまだ直せてません。まぁこれは地道に気付いたものを直していくしかないですね。(PO 一個単位ならダウンロードして一括では出来ますが、串刺しで一括は Transifex 管理なので面倒でしょうから。)

**Comment by hhsprings** [comment]
2.7 で最新化した方が良いもの、は、2.7 メンテナンスリリースで入ったもののうち「What's new で明記されているもの(ほとんどセキュリティ関連)」、が基本だと思うのですが、PO だけで対応出来ないものもありました。library/xml.rst がそれで、ここに「XML の脆弱性」が書かれていて、xmlrpclib.rst、pyexpat.xml など複数がこれを参照するようになっています。

ワタシとしてはこれはやっておいたほうがいいと思っているのですが、どうしましょう? (PR あげるにも rst の更新方針がまだ理解出来てないのでよくわかりません。) 関連する部分の最新化はちょっとずつ進めておきます。

「XML の脆弱性」を指すようになった箇所は全部で 6 箇所(うち一つは対応済みの xmlrpclib)ありますが、なんだかんだ 3.x 系には酷似した記述が大量にあるので、最初の「和訳 rst ⇒ PO」さえ踏ん張ってしまえば、未訳になった箇所の翻訳は楽だったりするので、そんなに大量の時間はかからないと思ってます。

**Comment by methane** [comment]
xml.rst や ensurepip.rst など、翻訳側に抜けていた（原文側で追加されていた）ファイルを追加しました。翻訳も反映されています。
