### ISSUE TITLE
xmlrpclib (2.7) / xmlrpc.client (3.x) で訳してはいけないかもしれないもの(methodSignature内)

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#717]
2.7 メンテナンスリリースに関係する xmlrpclib の最新化対応していて気付いたことです。

「methodSignature」内で

> シグネチャは単に”文字列, 配列” となります。パラメータが三つの整数で戻り値が文字列の場合は”文字列, 整数, 整数, 整数”

と訳されているのですが、これは実際に methodSignature を呼び出した場合に「シグニチャ」として返される出力を説明している気がするので、 "string, array"、"string, int, int" でないと意味がないのかな、という気がしています。試そうと思ったのですが signature を返すサーバの簡単なサンプルが見つからなかったのでまだ確認出来てないです。(ただし意味は通じるので致命傷とも思わないですが。)

もうひとつは「class xmlrpclib.ServerProxy」の表での説明。気付いた方がおられたのでしょう、「整数」などと 2.7 では訳されていたものが、3.x では原文の ":const:`integers`" に戻されています。多分これも 3.x 訳が正解なのだろうと思っていますが、動かしての確認が出来ていないので自信はないです。

大した話ではないのでのんびり考えればいいかなと思いますが、書いておかないとワタシが忘れてしまいそうなので、一応あげました。

**Comment by methane** [comment]
> 試そうと思ったのですが signature を返すサーバの簡単なサンプルが見つからなかったのでまだ確認出来てないです。(ただし意味は通じるので致命傷とも思わないですが。)

Python の標準ライブラリの xmlrpc.server (2.7 では SimpleXMLRPCServer) では、 system.methodSignature はサポートしてないみたいですね。

http://xmlrpc.scripting.com/spec.html
こっちにも methodSignature は乗ってないし、 Python で実装されたり規格化されるまえに xmlrpc 自体が
人気がなくなって立ち消えになった可能性…

正解を探すこと自体無意味に思えます。

**Comment by methane** [comment]
> もうひとつは「class xmlrpclib.ServerProxy」の表での説明。気付いた方がおられたのでしょう、「整数」などと 2.7 では訳されていたものが、3.x では原文の ":const:integers" に戻されています。多分これも 3.x 訳が正解なのだろうと思っていますが、動かしての確認が出来ていないので自信はないです。

これも特に正解はないと思います。この　integers が指すのは、 int とか long とかのことであって、 integers という名前の定数が xmlrpc.client や xmlrpclib に有るわけではなさそうなので。

**Comment by methane** [comment]
methodSignature とかの資料はこっちにありました。
http://xmlrpc-c.sourceforge.net/introspection.html
型は xmlrpc の方で決められてるものなので、 `string, int` が正解のようです。

**Comment by hhsprings** [comment]
ひとまず表のほうはそのまま (訳されたまま) とし、 http://docs.python.jp/2.7/library/xmlrpclib.html#xmlrpclib.ServerProxy.system.methodSignature と http://docs.python.jp/3.5/library/xmlrpc.client.html#xmlrpc.client.ServerProxy.system.methodSignature 部分だけ「シグネチャは、メソッドが使用する最上位のパラメータにのみ適用されます。例えばあるメソッドのパラメータが構造体の配列で戻り値が文字列の場合、シグネチャは単に"string, array" となります。パラメータが三つの整数で戻り値が文字列の場合は"string, int, int, int"となります。」としました。

この次のパラグラフにも「non-array」が「配列以外」としてあって悩んだですが、こっちは当座そのままに。

**Comment by hhsprings** [comment]
close します。
