### ISSUE TITLE
デザインと歴史 FAQ 辞書はどのように実装されているのですか の誤訳

### ISSUE THREAD

**Issue by fujiisat** [python-doc-ja/python-doc-ja#718]
原文 Compared to B-trees は  "B 木にコンパイルされることで" ではなく "B 木と比べて" ではないでしょうか。
3.4, 3.3, 2.7 でそうなっています

**Comment by methane** [comment]
ご報告ありがとうございます。
Transifex 上で修正したのでしばらくしたら 3.3, 3.4 では直ると思います。
2.7 の対応は対応方法を考えますのでお待ちください。

**Comment by hhsprings** [comment]
すいません、脇からちょっとだけしょーもない話(しょーもなくもｌないですが本題ではない話)させてください。

実はこれワタシ、「気付いたのに気付かなかった」という節穴やらかしてしまったのです。実は元の和訳 rst を po に変換して 2.7 Transifex に放り込む際に、diff (WinMerge)で 3.x から自動で取り込まれたはずのものが「見えて」いたんです。とても違和感があって、その場で英文読んだつもりが、そこでも「Compiled」にみえてしまったようで…、結果 2.7 Transifex には「Compiled」バージョンが放り込まれるハメになりました。

2.7 に随分 po 化して放り込む際に、色んな箇所で 3 系からの取り込みとの差異が見えました。出来る限り3系を尊重しましたが、「3系の方が間違っている」ものも結構あって、直せるものはその場で直しましたが結構そのまま放置したものもあります。ちょっとあとで全体見直そうかなと思ってます。

**Comment by hhsprings** [comment]
いや…失礼、違いますね。「2.7 rst では間違っていなかった」⇒「ので今サイトで見えている 2.7 は間違っていない」⇒「差異がみえて、誤った方をワタシが採用してしまって、2.7 Transifex が誤りの方が入った」が正解ですね。なので「節穴」というより、ワタシの作業ミスです、2.7 Transifex に関しては。

**Comment by methane** [comment]
2.7もこのページは Transifex ベースになり修正が反映されました。
