### ISSUE TITLE
2.7 リファレンス datamodel __hash__ の訳

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#719]
メモです。「e.g. by switching to a value-based concept of equality instead of the default identity based equality」が「例えば、値ベースの同値関係から同一性ベースの同値関係に変更する」、つまり正反対の意味に訳されてます。

reference/datamodel は Transifex 化完了してるので Transifex ではあとで直しておきます。

(3 系には該当箇所はありません。)

**Comment by hhsprings** [comment]
Transifex での修正、やっときました。

**Comment by methane** [comment]
datamodel は Transifex が有効になったはずなので閉じます。
