### ISSUE TITLE
csv.reader の「2.5 で変更」部分 (と What's New の該当部分)

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#720]
今回もどちらかと言えばメモです。(かつかなりどうでもいい。今更誰の注意喚起にもならない内容なので。)

Transifex で見えている未訳として多く残っている「What's New」(What's old?)を少しずつ訳していくなかで、対応するリファレンスとの関係を気にしながら訳しているのですが、その中で、どうにも自力で解決出来ないものがあり、 issue としてあげておきます。

「As a consequence, if newlines embedded within fields are important, the input should be split into lines in a manner that preserves the newline characters.」という表現、ここ、単に「改行コードが CR であれ NL であれ CR NL であれそのままフィールドに保存されます」と言っているだけなんじゃないか、という気がしている(ので今のところ What's New ではこちらの訳出)んですが、元のリファレンスでの訳出「入力は改行文字を保存するような仕方で複数行に分割されなければなりません。 」という訳が間違っていると思うほどの自信もない、という状態です。

仮に間違いだとして、わざわざ直したからって今更誰の得にもならないことなのでリファレンスは直さなくていいと思っていますが、今時点で What's New と解釈にズレがある、ということはメモしておかないと忘れ去られるので一応。(どなたか私の解釈にツッコミ入れてくれたら幸いです。)

**Comment by methane** [comment]
これかな https://hg.python.org/cpython/rev/fa65e3425a4c

**Comment by hhsprings** [comment]
をっと。下らないのに付き合わせてしまってなんかすんません。(個人的に今「What's old」が訳してあると結構便利(特に人への説明に)、と思って作業しはじめたんで、かなり古い話を引っ張り出すハメになるんですね。)

そうか、これ、C か…。あ、News の表現がわかりやすいですね。「previously it only allowed \n to be quoted」ということは、ワタシの解釈の方が合ってる気がする。

**Comment by methane** [comment]
んー。これ内部実装の話をしているのであって、「そのままフィールドに保存されます」という話をしているのでは無いと思います。
csv.reader 内部で行分割＆結合するとき、以前は改行をフラグにして、後で \n を挿入していたのを、改良版では実際の改行コード (\r, \n, \r\n) をそのまま残すようにしたという説明をしているようです。

What's New の編集は大変な重労働で、「エンドユーザーからみてどう変わったか」という視点で
書かれているとは限らず、コミットログに書いてる実装者向けの解説がそのまま載ってしまうことが
多いんですよね。
原文から乖離して、出力(パース結果)に改行コードが維持されるようになったという風に訳を変えてしまうのもありだと思います。

**Comment by hhsprings** [comment]
What's New では確かそう訳してたような…。あとで見ときます。リファレンスのほうは時間みつけて PO 化して直そうかなと思います。

そういえば PO 化済んだものは逐一言ったほうがいいですか? たまに一気にやるときがあって、そのときに割と何したかメモもしないままやってしまうので、どれが今作業したものかわかんなくなることもあって。

以下蛇足。
What's New がコミットログそのまま、のもの、ありますねぇ。一番イケてないのはその表現がそのままリファレンスの .versionmodified とかに複製されたときだったりしますね。何言ってるのかさっぱりわからないことが結構ありますね…。(逆もあって、リファレンスで書かれた内容と表現が少し違っていたためにリファレンス側の誤訳に気付いたのはありました。個人的には若干表現が違っている方が助かる。翻訳丸々コピーのメリットより、言いたいことが表現違いではっきりするほうが。)

**Comment by hhsprings** [comment]
対応中。ついでに見つけたもの。

メモ： 「13.1.4. writer オブジェクト」の最初のパラグラフは続くパラグラフの出だしとの重複。ただし訳は最初のパラグラフが多分正解。

**Comment by hhsprings** [comment]
メモ： 「class csv.excel_tab」の説明が excel クラスを指していた。3.x で修正されたものが Transifex で自動で取り込まれたらしい。

**Comment by hhsprings** [comment]
メモ： 完全にするためには「```:ref:`sequence <collections-abstract-base-classes>````」の参照先も最新化(Transifex化有無問わず)しないとダメ?

**Comment by hhsprings** [comment]
とりあえず 2.7 の library/csv の Transifex を完成させておきました。
●元の「the input should be split into lines in a manner which preserves the newline characters.」は、単に「should be」が「べき」ではなくて「はず」とするだけで良いと思うので、そうしてあります。
●「13.1.4. writer オブジェクト」部分は 3.x で直されていたようで、それを採用出来ました。
●「excel_tab」も同じく。
●最後の ref の問題はそのうち…。(sequence が本来ハイパーリンクになるはず。)
