### ISSUE TITLE
po ファイルのマージ、あるいは ~3.4 の終了

### ISSUE THREAD

**Issue by methane** [python-doc-ja/python-doc-ja#721]
3.5 の pot のアップロードを後回し後回しにしているのですが、その理由の一つに、
一度アップロードしてしまったら訳の訂正対象が増えてしまうという問題があります。

誤訳があった場合や、 3.4 / 3.5 両方で原文に同じ訂正が入った場合に、 Transifex 上での
更新作業を 3.4 と 3.5 の両方で行わなければなりません。
実際には 3.4 だけでなく 3.3 もどうするのか決めてないので、 3.3 も更新作業対象になるかもしれません。もちろん 2.7 の Transifex 化した部分もです。

この問題今後どの方向で行くか考えたいなーという issue です。

1. サポートしてるすべてのバージョンの pot をマージし、 Transifex 上のプロジェクトを 1 つにまとめる。
2. 人間は新しい方を更新するようにし、同一ファイルの同一キーで新しいバージョンの訳文が更新されたら古い方を追従する作業は自動化する
3. 翻訳をメンテするバージョンを 2.7 と 3系最新版だけに限定し、それ以外のバージョンは無視する。

僕が一番楽なのは仕組みを何も作らなくていい3番ですが、そろそろ Transifex を使って sphinx
ドキュメントの翻訳をしてるプロジェクトが当プロジェクト以外にもたくさん出てきている気がするので、
すでにこの問題を1番か2番 (あるいはもっと良い方法) で解決している実運用例があれば真似したい。

**Comment by hhsprings** [comment]
「更新作業を 3.4 と 3.5 の両方で」。これ、最近ずっと翻訳作業してて毎度感じます。2.7 と共通だと今でも 2.7、3.3、3.4 全部直すのが筋ですが、3.3 はどうしても後回しにしてしまいます。

最近ずっと思っていたのは、
・3 系は最新だけで普通事足りるはず(原文に間違いがないなら .versionadded 等でわかるはず)
・2.7 だけはやはり 3 とは同じではないので別管理が良いはず (Unicode 周りの差異はやはり多い)
ということで、仕組みの面だけでなく 3つ目の案が読者にとっても良いのではないかと感じています。

Transifex の suggesion も「原文の差異」はわかっても翻訳の差異がわかる UI になっていないので、3.4 で直したものを別バージョンに更新するの、大変なんですよねぇ…。(特に rest からみで空白だけ入れたような修正なんかは目がしょぼしょぼします。)

量が多いときは po をダウンロードして WinMerge で差異を見て一気にマージする、なんてことをしてます。いずれこれを 2.7、3.3、3.4 で「やらないとなぁ」と思ってました。当然かなりのパワーが必要なので、ほかにすることがあるなら後回しになってしまいますね。

1つめの案は魅力的にも思うんですが、ただ、翻訳する際に Transifex の UI だけをみて作業するということって、実際合理的でも便利でもないと思うんです。翻訳結果を逐次確認して前後関係を見ながら作業した方が、結果的には効率的と思います。pot をマージして Transifex の UI をみると、rst との関係がわかりにくくなくなるんじゃないかと思うので、あまり良くないかなと思います。

2つめは出来るなら嬉しいですかねぇ。今は元が未訳の場合だけ流し込まれてるんですよね。

個人的には「3案 + 2案」が可能ならありがたいです。自動で更新されるとしても結局はやはり目でみて確認したいので、3.3があればやはり「確認」したくはなりますから。

**Comment by hhsprings** [comment]
「案4」というのもあるかもしれないです。

「サイトに公開するのは 2.7 と 3 最新のみ」 + 「Transifex 管理は今あるものはそのまま」。

この場合、「更新対象は 2.7 と 3 最新のみ」とし、3 の最新でないものは、「そこにいるけれども基本放置」。翻訳作業者にわかりやすくはない (知らないとつい触ってしまいそう) んですが、「最新ではない 3 は Sugession のためだけにある」と考えてしまうと。特に何か新しいシカケを考えずにやる現実解としてはあるいは悪くないかもしれないかなと。

**Comment by methane** [comment]
案3はメンテする（誤訳の修正などに対応する）かどうかについてだけ述べていて、Web公開やTransifexプロジェクトをどうするかはそれに付随する選択肢なので、その案4は案3の実装例の1つでしかありません。

Transifex 上のプロジェクトをどうするかはまだ調べてみないとわかりませんが、Web版の公開を
停止するつもりはありません。
本家も、メンテナンスしてないバージョンのドキュメントの公開を止めてないので。 https://docs.python.org/3.2/

**Comment by methane** [comment]
案2は msgmerge で可能な気がしますが、案2にしろ案3にしろ、とりあえず人間の作業による 3.3 の翻訳更新は停止しましょう。

**Comment by methane** [comment]
とりあえず当面は案3でいくということでいったん close します。
