### ISSUE TITLE
2.7 Transifex の PO と原文 rst のリビジョンの対応が合っていない

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#722]
What’s New in Python 2.5 で気付いています。ほかはまだ確認出来てません。

**Comment by methane** [comment]
はい。勢いでやってたのでその辺どう管理するかが今の課題です。

**Comment by hhsprings** [comment]
原則としてリリースバージョンに対応してると良いのでしょうねぇ、きっと。とはいえ…今 2.7 だと多分 2.7.11dev なんですよね? ものによっては dev 版で先行しときたいというのもあるのかもなぁ…。

ちなみに What's New だけならあまり気にしなくていいだろうとは思っています。全てのバージョンに同じものがいるので、今であれば 3.4/ 3.5/ から読めるので。

**Comment by methane** [comment]
リビジョン 57fea6f75ac2 から pot の生成と rst のコピーの両方を行いました。
原文から無修正でコピーできるファイルを tools/potlist に置いて、それを元に一括でコピーできるようになってます。

**Comment by methane** [comment]
> 原則としてリリースバージョンに対応してると良いのでしょうねぇ、きっと。とはいえ…今 2.7 だと多分 2.7.11dev なんですよね? ものによっては dev 版で先行しときたいというのもあるのかもなぁ…。

Python3 の翻訳では、翻訳中原文に問題を見つけて本家に対応してもらった場合に docs.python.org のドキュメントはすぐに更新されるので、翻訳側も修正された原文に対して翻訳したいということで、リリースバージョンでの固定化はしてませんでした。

Python 2.7 はリリースバージョン固定でも良いかもしれません。

**Comment by methane** [comment]
Python 3.5 も pot の再生成が終わりました。
