### ISSUE TITLE
LateXBuild について

### ISSUE THREAD

**Issue by e-kwsm** [python-doc-ja/python-doc-ja#724]
* wiki の [LateXBuild](https://github.com/python-doc-ja/python-doc-ja/wiki/LateXBuild) の内容が少し古いです (現行は Tex Live 2015)  
環境の導入に関しては LaTeX を使おうとしている人には不要かもしれませんが
* [ここ](https://github.com/python-doc-ja/python-doc-ja/wiki/LateXBuild#windows-%E3%81%A7%E3%81%AF-w32tex-%E3%81%A8%E3%81%84%E3%81%86%E6%97%A5%E6%9C%AC%E8%AA%9E-tex-%E3%83%87%E3%82%A3%E3%82%B9%E3%83%88%E3%83%AA%E3%83%93%E3%83%A5%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%8C%E5%8F%A4%E3%81%8F%E3%81%8B%E3%82%89%E3%81%82%E3%82%8B%E3%82%88%E3%81%86%E3%81%A7%E3%81%99)や[ここ](https://github.com/python-doc-ja/python-doc-ja/wiki/LateXBuild#%E5%AE%9F%E9%9A%9B%E3%83%91%E3%83%83%E3%82%B1%E3%83%BC%E3%82%B8%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%AE-homebrew-%E3%81%AF-mactex-%E3%81%AE%E5%88%A9%E7%94%A8%E3%82%92%E6%8E%A8%E5%A5%A8%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%82%88%E3%81%86%E3%81%A7%E3%81%99)，[ここ](https://github.com/python-doc-ja/python-doc-ja/wiki/LateXBuild#%E3%82%82%E3%81%A1%E3%82%8D%E3%82%93-jarticle-%E3%82%84-jreport-%E3%82%82%E5%88%A9%E7%94%A8%E3%81%A7%E3%81%8D%E3%81%BE%E3%81%99%E3%81%8C-jbook-%E3%81%AF%E5%8B%95%E4%BD%9C%E3%81%97%E3%81%BE%E3%81%9B%E3%82%93)あたりがなぜか見出し1になっています

**Comment by methane** [comment]
見出しレベルが1になってるのは、 Google からの自動変換の結果ですね。

個人的には、 chm と PDF は面倒なので、chm => docset, PDF => ePub に移行してしまいたいです。
ePub はリーダーがすごい広まってて、 iBook で Sphinx の ePub が開けないとか問題はあるものの
タブレットでリフローされるとかのメリット多いので PDF の置き換えは行けそうだと思ってます。

chm の方は、 Mac の Dash みたいなアプリが Windows でも使いやすい Electron アプリで出てこないかなー、
と他力本願な願望を抱いてます。

**Comment by methane** [comment]
見出しレベルはざっくり直してみました。

**Comment by e-kwsm** [comment]
>見出しレベルはざっくり直してみました。

どうもありがとうございます．

>個人的には、 chm と PDF は面倒なので、chm => docset, PDF => ePub に移行してしまいたいです。

試していないのですが，Pandocはどうでしょうか．

**Comment by methane** [comment]
>> 個人的には、 chm と PDF は面倒なので、chm => docset, PDF => ePub に移行してしまいたいです。

> 試していないのですが，Pandocはどうでしょうか．

どういう意味でしょうか？
chm => docset, PDF => ePub というのは、移行という意味であって変換ではないので、
ここで Pandoc の出る幕はないと考えています。

**Comment by e-kwsm** [comment]
すいません，勘違いでした
