### ISSUE TITLE
http://docs.python.jp/2.7/library/functions.html のテーブルからのハイパーリンク

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#725]
偶然気付いたので…。

リンク先が rest のマークアップの関係でおかしくなるものは原文でも結構多いので、原文が直ってないなら放置しようかとも思ったのですが、原文は修正されているようで。たとえば repr が repr モジュールに飛んでしまうのですね。

たとえば repr の場合
```
:func:`repr`
```
ではなく
```
|func-repr|_
…
.. |func-repr| replace:: ``repr()``
…
.. _func-repr:
.. function:: repr(object)
```
に修正されてます。

これも Transifex 化した方が楽かもしれませんね。どっかで時間みつけたら…。

**Comment by hhsprings** [comment]
対応中。Transifex は 90 % ちょい。

**Comment by hhsprings** [comment]
メモ。
compile の訳で suggestion で自動で入った訳が多分間違っている。現 2.7 訳「コードオブジェクトは exec 文により実行したり、 eval() で評価したりすることができます。 」「AST オブジェクトへの、また、 AST オブジェクトからのコンパイルの方法は、 _ast モジュールのドキュメントを参照下さい。」は正解だが、これと違っていた。3.x 訳がおかしい?

**Comment by hhsprings** [comment]
メモ。
input で、「This function does not catch user errors.」部分のニュアンスが随分変わっている。ただ、「.. note::」でなくなったのは「74721 (98c574ba45fc) Clean-up docs for input() (2012-02-02)」だが、原文のニュアンスはほとんど変わっていない。現在の 2.7 訳「警告 この関数はユーザのエラーに対して安全ではありません ! この関数は、入力は有効な Python の式であると期待しています; 入力が構文的に正しくない場合、 SyntaxError が送出されます。式を評価する際にエラーが生じた場合、他の例外も送出されるかもしれません。 (一方、この関数はまさに、ときどき熟練者がすばやくスクリプトを書く際に必要とするものです)」は随分昔の内容のままだったんではないか?
少なくとも最新を訳しても「この関数はユーザエラーを捕捉しません。入力が構文的に正しくない場合、 :exc:`SyntaxError` が送出されます。式を評価する際にエラーが生じた場合、他の例外も送出されるかもしれません。」になるだけ。全然ニュアンスが違う。

**Comment by hhsprings** [comment]
メモ。
int 訳の「the conversion truncates towards zero」の suggestion で入るもの(たぶん 3.x 訳)は「0 へ向かう方向へ切り詰め」がベター。「0 の方へ」でも伝わらないわけではないけれど。

**Comment by hhsprings** [comment]
メモ。
同じく int 訳「A base-n literal consists of the digits 0 to n-1, with ``a`` to ``z`` (or ``A`` to ``Z``) having values 10 to 35. 」は改善必要。「基数 n のリテラルは 0 から n-1 の数字で構成され、値 10-35 を持つ ``a`` から ``z`` (または ``A`` から ``Z``) を含みます。」は実態を表現出来ていない。とても表現しにくいが 0 から n-1 は各桁で表現出来る幅のことを言っているので…。数学的に級数で表現してしまいたいくらい…。どうするか…?

**Comment by hhsprings** [comment]
メモ。
同じく int 訳。「Base 0 means to interpret the string exactly as an integer literal, so that the actual base is 2, 8, 10, or 16.」は原因⇒結果と訳すとオカシイ。「基数 0 を渡すと、文字列を、実際の基数 2, 8, 10, 16 のどれかで整数リテラルとして正確に解釈します。」程度の意味。(真面目に英語解読として説明するなら、so that は「～となるように」くらいの意味合い。)

**Comment by hhsprings** [comment]
メモ。
同じく int 訳。「Base 0 means to interpret the string exactly as an integer literal, so that the actual base is 2, 8, 10, or 16.」を「基数 0 はコードリテラルとして正確に解釈することを意味します。その結果、実際の基数は 2, 8, 10, 16 のどれかです。」と訳してある(たぶん3.x訳)が、2.7 訳は少しわかりやすく「基数 0 を渡すと、文字列を、実際の基数 2, 8, 10, 16 のどれかで整数リテラルとして正確に解釈します。」としておく。3.x 訳は特に間違いということでもないが、日本語として少々通りが悪いので。

**Comment by hhsprings** [comment]
メモ。
long の訳。「Python 整数として表現可能な十進の数でなければなりません。」は 2.7 の原文の最初の版からも乖離していた模様。2011年11月時点でも既に「 If the argument is a string, it must contain a possibly signed number of arbitrary size, 」。もちろん2進、8進、16進文字列を受け取れるようになっているのだから、「十進の」は入っていたらダメ。
ここの新しい訳は「文字列または数値 *x* から長整数オブジェクトを構築して返します。引数が文字列の場合は、任意サイズの符号付の数を表していなければなりません。空白で囲まれていても構いません。 *base* 引数は :func:`int` のものと同じように解釈され、また、 *x* が文字列の時だけ与えることができます。文字列以外の引数では通常整数、長整数、浮動小数点数を与えることが出来、同じ値としての長整数を返します。浮動小数点数から整数への変換では、(ゼロに向かう方向へ) 切り詰められます。引数が与えられなければ ``0L`` を返します。」とした。

**Comment by hhsprings** [comment]
一応のメモ。file のシグニチャ。間違ってたの? かつて「bufsize」。最新では「buffering」。

**Comment by hhsprings** [comment]
これも一応のメモ。reload の説明のニュアンスが変わっている。以前は sys などのリロードだけは悪くない、といっていた。いまではそれらも「お勧めできない」と言っている。

**Comment by hhsprings** [comment]
**Transifex で 100% に** しておきました。上でメモしたもの以外でも 3.x からの suggestion の方を採用したものなどで多少変わってます。

**Comment by methane** [comment]
library/functions.rst を transifex に移行すれば良いんですよね？

**Comment by methane** [comment]
やりました。
