### ISSUE TITLE
3.5.1 で「原文」リンクが消えている

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#726]
これは意図してでしょうか? 3.5 の Transifex 化が入ったタイミングあたりで消えたような。(2.7 では残ってます。) 確かこれ、テンプレートに手を入れてましたよね。

原文へのリンクは非常にありがたい機能だったので、出来れば復活して欲しいです。

**Comment by methane** [comment]
追加しておきました。次回のビルドから反映されると思います。

**Comment by hhsprings** [comment]
ありがとうございますぅ。
