### ISSUE TITLE
2.7 の library/weakref 、 library/copy_reg 、library/binascii 最新化

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#728]
タイトルにあげた 3 つ以外も少しずつ PO 化進めてるので、Transifex が 100% になったものは結構増えてます。この 3 つだけ特別にあげたのは最新化以外の特筆すべき点があるからです。

●library/weakref - 「WeakValueDictionary」の注釈に誤りがあり、修正 (3.xでは元々修正されていた)。
●library/copy_reg - 「*function* should return ...」部分の訳が「タプルです」で終わっていたのを、「返さなければなりません」と修正(これは 3.5 でも)。また Classic style class が「標準クラス」となっていた。2.2 までの名残? 「旧スタイルクラス」に修正。
●library/binascii - 「Convert binary data to a line of ASCII characters in base64 coding. The return value is the converted line, including a newline char. The length of *data* should be at most 57 to adhere to the base64 standard.」となっていた原文が、結構ニュアンスの違う「Convert binary data to a line of ASCII characters in base64 coding. The return value is the converted line, including a newline char. The newline is added because the original use case for this function was to feed it a series of 57 byte input lines to get output lines that conform to the MIME-base64 standard. Otherwise the output conforms to :rfc:`3548`.」に、2.7、3.x ともに変わっていた。base64 と MIME-base64 を区別して説明するようになってわかりやすくなったと思う。(訳出は苦労したが。)

どれも致命的というわけではないのでこれだけを大慌てで差し替える必要はなく、どこかのタイミングで一気に差し替えるのでもいいと思いますが、現時点で公式ドキュメントとしてみえているものについての問題点はあげておいたほうが良いと思うので一応。

**Comment by hhsprings** [comment]
オマケというか。2つ。
●library/tabnanny で、「If *file_or_dir* is ...」部分で「checking」が「変更」と訳されていて、これは普通に「チェック」とすべきと思うので、2.7、3.x ともに修正。
●非推奨モジュールなのでどうでもいいんですが、library/dircache に typo 「:mod:`durcache`」。

**Comment by hhsprings** [comment]
●library/netrc - 2.7.6 で追加された POSIX パーミッションのチェック

**Comment by methane** [comment]
翻訳率100%を po 化するの、目でやってたので、 API 叩くツールを作るまで待ってください。
（transifex-client にはその機能はなかった）

**Comment by hhsprings** [comment]
のんびりやってますのでのんびり対応してくださいませ。ちまちま問題見つけてはいますが、今のところ致命的というほどのものは見つけてません。(library/unicodedata での原文の更新は技術的には大問題でしょうが、誰もこんなの気にしてないと思いますし。)

**Comment by hhsprings** [comment]
メモ: library/tokenize の tokenize.tokenize の最初の引数の説明の「completion」が「補完」と訳されていたが、これは「完了」でなければならない。(completion を補完と訳すことが多いのは「中途入力を完了させる(⇒補って完成させる⇒補完)」だから。けれどもここは本来の「完了」の意味。) なお、「旧インターフェイス」部分なのでこれ自体はまぁどうでもよいといえばどうでもよい。ただ、tokenize.generate_tokens に同じ原文が追加されているのに翻訳に対応がなく、訳を正しくした上で tokenize.generate_tokens に追加。

**Comment by methane** [comment]
先ほど po ファイルの string が空なメッセージが存在しないファイルを翻訳完了ファイルと
判断するスクリプトで一斉に transifex 化しました。半日以内に反映されていると思います。

**Comment by hhsprings** [comment]
スクリプトまで用意してもらっておいてちょっと申し訳ないのですが、なんとなくずっと中途半端でイレギュラーなのもイヤだなと思って、この際「全部やっちまえ」モードで「全部」やってます。

1. library は idle だけ残っているがこれはどうやら 3.5 と完全に(たぶん)同じらしいので、TRANSIFEX 管理でよいと思う
2. library の re の一つだけ翻訳できない (翻訳キーが「\n」になっている)
3. c-api があと5つで終わる
4. whatsnew は未訳が残ってても誰も困らないだろう

てわけで、明日遅くあたりにでももう一度のぞいてもらえれば、「全部を TRANSIFEX 管理」していい状態になってると思います。

**Comment by methane** [comment]
翻訳率がすごく上がっていてびっくりしました。
こちらはあまり翻訳に参加できてないのですが、頑張ってください。

**Comment by hhsprings** [comment]
ハイ。
大変は大変なんですが、元々の訳があるので、3.x で新しく訳を付けるよりは多少は早く出来てます。(わずかですが翻訳キーが同じで 3.5 で未訳だったものが結構入ったので、3.5 の翻訳率もまぁまぁ上がってると思います。-> ただし 2.7 訳で問題があってもワタシが気付かなかったものはそのまま継承されてしまったという問題はないではないですが。)

**Comment by hhsprings** [comment]
close、でいいですよね? (全部が Transifex されたと認識しています。)
