### ISSUE TITLE
impl-detail:: 部分を翻訳すると 「CPython implementation detail: 」が消える

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#729]
「.. impl-detail::」に対応する翻訳を入れると「CPython implementation detail: 」が消える、という問題です。(未訳だと出てくれる。)

これ、まだ問題なのか問題でないのか未確定です。関係するものが(多分)まだ公式レポジトリ側で原文 rst への置き換えされたものがないので、ローカルでしかみていません。今自分のローカル PC では Sphinx 1.2.3 で作業しているのが関係しているのかしていないのか、切り分け出来てないです。[#723](https://github.com/python-doc-ja/python-doc-ja/issues/723) に似てる気がします。(2.7 だけの問題なのかどうかもまだみてません。) ⇒ ローカルにチェックアウトした py27 ソースを最新化してないせいかどうかもまだみてない。

library/imp などにこれがあります。これの rst 差し替えしてみて再現するなら問題、しないならクローズ出来る問題、ということに。再現する場合に「手で **CPython 実装の詳細:** を入れてまわる」…ことはしたくないですね、出来れば。

**Comment by methane** [comment]
FYI: 今は Sphinx 1.3.4 を使ってます。

**Comment by hhsprings** [comment]
自分が関係した issue を整理しようかと思ってこれを見直してみたのですが、サイトでも同じなのですね。[sys._debugmallocstats](http://docs.python.jp/3.5/library/sys.html#sys._debugmallocstats) ([原文](https://docs.python.org/3.5/library/sys.html#sys._debugmallocstats)) など。

「など」と言ってますが実際は 20 箇所程度のようなので、「気にしない」と言ってしまえばそれまでかもしれません。ただし 2.7 ではスタイルとしてボックスで囲まれるのに対して 3.x ではフラットな表示なので、太字の「CPython implementation detail: 」見出しが消えるのはマズいですね…。

**Comment by methane** [comment]
@tk0miya
Directive.run メソッドで "CPython implementation detail:" というテキストを追加しているのですが、
これによる変更は i18n で上書きされてしまうものなのでしょうか？

ref: https://github.com/python-doc-ja/cpython-doc-intl/blob/intl-3.5/Doc/tools/extensions/pyspecific.py#L99-L120

**Comment by hhsprings** [comment]
一筋縄ではいかなそうですかね。
該当箇所全部が問題となるわけでもなくて、文章に「CPython 固有です」みたいに書かれている部分は実用上は問題なかったりするので、ちょっと全部洗い出して問題となる部分、そうでない部分全部調べてみます。

**Comment by hhsprings** [comment]
ひとまずシンプルに rst から全部拾い上げてみます。判断はこの次のコメントにて(といっても一つずつチェックするので結構時間はかかりますが)。おそらく「CPython」が含まれているものはひとまずあまり気にしなくともよく、入っていないものは「当座」訳の工夫するなど必要、という感じになるのではないかと。問題となるものが少ないようなら、慌てて対応する必要もないのかなと。(とはいえすぐに目に入った「library/functions.rst:640」は、これは「CPython implementation detail:」という見出しなしではまったく意味不明なのは自明ですね…。)
<h2>2.7.12</h2>
<table>
<tr><td>library/dis.rst:15</td><td>Bytecode is an implementation detail of the CPython interpreter!  No guarantees are made that bytecode will not be added, removed, or changed between versions of Python.  Use of this module should not be considered to work across Python VMs or Python releases.</td></tr>
<tr><td>library/functions.rst:640</td><td>This is the address of the object in memory.</td></tr>
<tr><td>library/functions.rst:1573</td><td>:func:`xrange` is intended to be simple and fast.  Implementations may impose restrictions to achieve this.  The C implementation of Python restricts all arguments to native C longs ("short" Python integers), and also requires that the number of elements fit in a native C long.  If a larger range is needed, an alternate version can be crafted using the :mod:`itertools` module: ``islice(count(start, step), (stop-start+step-1+2*(step<0))//step)``.</td></tr>
<tr><td>library/imp.rst:239</td><td>The import internals identify extension modules by filename, so doing ``foo = load_dynamic("foo", "mod.so")`` and ``bar = load_dynamic("bar", "mod.so")`` will result in both foo and bar referring to the same module, regardless of whether or not ``mod.so`` exports an ``initbar`` function. On systems which support them, symlinks can be used to import multiple modules from the same shared library, as each reference to the module will use a different file name.</td></tr>
<tr><td>library/inspect.rst:366</td><td>getsets are attributes defined in extension modules via :c:type:`PyGetSetDef` structures.  For Python implementations without such types, this method will always return ``False``.</td></tr>
<tr><td>library/inspect.rst:379</td><td>Member descriptors are attributes defined in extension modules via :c:type:`PyMemberDef` structures.  For Python implementations without such types, this method will always return ``False``.</td></tr>
<tr><td>library/inspect.rst:615</td><td>This function relies on Python stack frame support in the interpreter, which isn't guaranteed to exist in all implementations of Python.  If running in an implementation without Python stack frame support this function returns ``None``.</td></tr>
<tr><td>library/math.rst:374</td><td>The :mod:`math` module consists mostly of thin wrappers around the platform C math library functions.  Behavior in exceptional cases follows Annex F of the C99 standard where appropriate.  The current implementation will raise :exc:`ValueError` for invalid operations like ``sqrt(-1.0)`` or ``log(0.0)`` (where C99 Annex F recommends signaling invalid operation or divide-by-zero), and :exc:`OverflowError` for results that overflow (for example, ``exp(1000.0)``).  A NaN will not be returned from any of the functions above unless one or more of the input arguments was a NaN; in that case, most functions will return a NaN, but (again following C99 Annex F) there are some exceptions to this rule, for example ``pow(float('nan'), 0.0)`` or ``hypot(float('nan'), float('inf'))``.</td></tr>
<tr><td>library/stdtypes.rst:208</td><td>Objects of different types except numbers are ordered by their type names; objects of the same types that don't support proper comparison are ordered by their address.</td></tr>
<tr><td>library/stdtypes.rst:842</td><td>If *s* and *t* are both strings, some Python implementations such as CPython can usually perform an in-place optimization for assignments of the form ``s = s + t`` or ``s += t``.  When applicable, this optimization makes quadratic run-time much less likely.  This optimization is both version and implementation dependent.  For performance sensitive code, it is preferable to use the :meth:`str.join` method which assures consistent linear concatenation performance across versions and implementations.</td></tr>
<tr><td>library/stdtypes.rst:1719</td><td>While a list is being sorted, the effect of attempting to mutate, or even inspect, the list is undefined.  The C implementation of Python 2.3 and newer makes the list appear empty for the duration, and raises :exc:`ValueError` if it can detect that the list has been mutated during a sort.</td></tr>
<tr><td>library/stdtypes.rst:2132</td><td>Keys and values are listed in an arbitrary order which is non-random, varies across Python implementations, and depends on the dictionary's history of insertions and deletions.</td></tr>
<tr><td>library/sys.rst:465</td><td>This function should be used for internal and specialized purposes only. It is not guaranteed to exist in all implementations of Python.</td></tr>
<tr><td>library/sys.rst:490</td><td>The :func:`gettrace` function is intended only for implementing debuggers, profilers, coverage tools and the like.  Its behavior is part of the implementation platform, rather than part of the language definition, and thus may not be available in all Python implementations.</td></tr>
<tr><td>library/sys.rst:943</td><td>The :func:`settrace` function is intended only for implementing debuggers, profilers, coverage tools and the like.  Its behavior is part of the implementation platform, rather than part of the language definition, and thus may not be available in all Python implementations.</td></tr>
<tr><td>library/sys.rst:960</td><td>This function is intimately bound to CPython implementation details and thus not likely to be implemented elsewhere.</td></tr>
<tr><td>library/threading.rst:31</td><td>In CPython, due to the :term:`Global Interpreter Lock`, only one thread can execute Python code at once (even though certain performance-oriented libraries might overcome this limitation). If you want your application to make better use of the computational resources of multi-core machines, you are advised to use :mod:`multiprocessing`. However, threading is still an appropriate model if you want to run multiple I/O-bound tasks simultaneously.</td></tr>
<tr><td>library/types.rst:247</td><td>In other implementations of Python, this type may be identical to ``GetSetDescriptorType``.</td></tr>
<tr><td>library/weakref.rst:75</td><td>Other built-in types such as :class:`tuple` and :class:`long` do not support weak references even when subclassed.</td></tr>
<tr><td>library/__builtin__.rst:37</td><td>Most modules have the name ``__builtins__`` (note the ``'s'``) made available as part of their globals.  The value of ``__builtins__`` is normally either this module or the value of this modules's :attr:`__dict__` attribute.  Since this is an implementation detail, it may not be used by alternate implementations of Python.</td></tr>
<tr><td>reference/datamodel.rst:60</td><td>CPython currently uses a reference-counting scheme with (optional) delayed detection of cyclically linked garbage, which collects most objects as soon as they become unreachable, but is not guaranteed to collect garbage containing circular references.  See the documentation of the :mod:`gc` module for information on controlling the collection of cyclic garbage. Other implementations act differently and CPython may change. Do not depend on immediate finalization of objects when they become unreachable (ex: always close files).</td></tr>
<tr><td>reference/datamodel.rst:749</td><td>Because of the way CPython clears module dictionaries, the module dictionary will be cleared when the module falls out of scope even if the dictionary still has live references.  To avoid this, copy the dictionary or keep the module around while using its dictionary directly.</td></tr>
<tr><td>reference/executionmodel.rst:130</td><td>Users should not touch ``__builtins__``; it is strictly an implementation detail.  Users wanting to override values in the builtins namespace should :keyword:`import` the :mod:`__builtin__` (no 's') module and modify its attributes appropriately.</td></tr>
<tr><td>reference/expressions.rst:727</td><td>An implementation may provide built-in functions whose positional parameters do not have names, even if they are 'named' for the purpose of documentation, and which therefore cannot be supplied by keyword.  In CPython, this is the case for functions implemented in C that use :c:func:`PyArg_ParseTuple` to parse their arguments.</td></tr>
<tr><td>reference/simple_stmts.rst:219</td><td>In the current implementation, the syntax for targets is taken to be the same as for expressions, and invalid syntax is rejected during the code generation phase, causing less detailed error messages.</td></tr>
<tr><td>reference/simple_stmts.rst:962</td><td>The current implementation does not enforce the latter two restrictions, but programs should not abuse this freedom, as future implementations may enforce them or silently change the meaning of the program.</td></tr>
<tr><td>using/cmdline.rst:13</td><td>Other implementations' command line schemes may differ.  See :ref:`implementations` for further resources.</td></tr>
</table>

<h2>3.5.2</h2>
<table>
<tr><td>library/codecs.rst:966</td><td>Some common encodings can bypass the codecs lookup machinery to improve performance.  These optimization opportunities are only recognized by CPython for a limited set of aliases: utf-8, utf8, latin-1, latin1, iso-8859-1, mbcs (Windows only), ascii, utf-16, and utf-32.  Using alternative spellings for these encodings may result in slower execution.</td></tr>
<tr><td>library/dis.rst:15</td><td>Bytecode is an implementation detail of the CPython interpreter.  No guarantees are made that bytecode will not be added, removed, or changed between versions of Python.  Use of this module should not be considered to work across Python VMs or Python releases.</td></tr>
<tr><td>library/doctest.rst:284</td><td>Prior to version 3.4, extension modules written in C were not fully searched by doctest.</td></tr>
<tr><td>library/functions.rst:655</td><td>This is the address of the object in memory.</td></tr>
<tr><td>library/inspect.rst:403</td><td>getsets are attributes defined in extension modules via :c:type:`PyGetSetDef` structures.  For Python implementations without such types, this method will always return ``False``.</td></tr>
<tr><td>library/inspect.rst:414</td><td>Member descriptors are attributes defined in extension modules via :c:type:`PyMemberDef` structures.  For Python implementations without such types, this method will always return ``False``.</td></tr>
<tr><td>library/inspect.rst:1074</td><td>This function relies on Python stack frame support in the interpreter, which isn't guaranteed to exist in all implementations of Python.  If running in an implementation without Python stack frame support this function returns ``None``.</td></tr>
<tr><td>library/inspect.rst:1216</td><td>This function relies on the generator exposing a Python stack frame for introspection, which isn't guaranteed to be the case in all implementations of Python. In such cases, this function will always return an empty dictionary.</td></tr>
<tr><td>library/math.rst:445</td><td>The :mod:`math` module consists mostly of thin wrappers around the platform C math library functions.  Behavior in exceptional cases follows Annex F of the C99 standard where appropriate.  The current implementation will raise :exc:`ValueError` for invalid operations like ``sqrt(-1.0)`` or ``log(0.0)`` (where C99 Annex F recommends signaling invalid operation or divide-by-zero), and :exc:`OverflowError` for results that overflow (for example, ``exp(1000.0)``).  A NaN will not be returned from any of the functions above unless one or more of the input arguments was a NaN; in that case, most functions will return a NaN, but (again following C99 Annex F) there are some exceptions to this rule, for example ``pow(float('nan'), 0.0)`` or ``hypot(float('nan'), float('inf'))``.</td></tr>
<tr><td>library/statistics.rst:216</td><td>Under some circumstances, :func:`median_grouped` may coerce data points to floats.  This behaviour is likely to change in the future.</td></tr>
<tr><td>library/stdtypes.rst:641</td><td>Currently, the prime used is ``P = 2**31 - 1`` on machines with 32-bit C longs and ``P = 2**61 - 1`` on machines with 64-bit C longs.</td></tr>
<tr><td>library/stdtypes.rst:1192</td><td>While a list is being sorted, the effect of attempting to mutate, or even inspect, the list is undefined.  The C implementation of Python makes the list appear empty for the duration, and raises :exc:`ValueError` if it can detect that the list has been mutated during a sort.</td></tr>
<tr><td>library/sys.rst:121</td><td>This function is specific to CPython.  The exact output format is not defined here, and may change.</td></tr>
<tr><td>library/sys.rst:496</td><td>This function should be used for internal and specialized purposes only. It is not guaranteed to exist in all implementations of Python.</td></tr>
<tr><td>library/sys.rst:519</td><td>The :func:`gettrace` function is intended only for implementing debuggers, profilers, coverage tools and the like.  Its behavior is part of the implementation platform, rather than part of the language definition, and thus may not be available in all Python implementations.</td></tr>
<tr><td>library/sys.rst:1076</td><td>The :func:`settrace` function is intended only for implementing debuggers, profilers, coverage tools and the like.  Its behavior is part of the implementation platform, rather than part of the language definition, and thus may not be available in all Python implementations.</td></tr>
<tr><td>library/sys.rst:1091</td><td>This function is intimately bound to CPython implementation details and thus not likely to be implemented elsewhere.</td></tr>
<tr><td>library/sys.rst:1294</td><td>This is a CPython-specific way of accessing options passed through :option:`-X`.  Other implementations may export them through other means, or not at all.</td></tr>
<tr><td>library/threading.rst:324</td><td>In CPython, due to the :term:`Global Interpreter Lock`, only one thread can execute Python code at once (even though certain performance-oriented libraries might overcome this limitation). If you want your application to make better use of the computational resources of multi-core machines, you are advised to use :mod:`multiprocessing` or :class:`concurrent.futures.ProcessPoolExecutor`. However, threading is still an appropriate model if you want to run multiple I/O-bound tasks simultaneously.</td></tr>
<tr><td>library/types.rst:181</td><td>In other implementations of Python, this type may be identical to ``GetSetDescriptorType``.</td></tr>
<tr><td>reference/datamodel.rst:39</td><td>For CPython, ``id(x)`` is the memory address where ``x`` is stored.</td></tr>
<tr><td>reference/datamodel.rst:70</td><td>CPython currently uses a reference-counting scheme with (optional) delayed detection of cyclically linked garbage, which collects most objects as soon as they become unreachable, but is not guaranteed to collect garbage containing circular references.  See the documentation of the :mod:`gc` module for information on controlling the collection of cyclic garbage. Other implementations act differently and CPython may change. Do not depend on immediate finalization of objects when they become unreachable (so you should always close files explicitly).</td></tr>
<tr><td>reference/datamodel.rst:692</td><td>Because of the way CPython clears module dictionaries, the module dictionary will be cleared when the module falls out of scope even if the dictionary still has live references.  To avoid this, copy the dictionary or keep the module around while using its dictionary directly.</td></tr>
<tr><td>reference/executionmodel.rst:175</td><td>Users should not touch ``__builtins__``; it is strictly an implementation detail.  Users wanting to override values in the builtins namespace should :keyword:`import` the :mod:`builtins` module and modify its attributes appropriately.</td></tr>
<tr><td>reference/expressions.rst:704</td><td>An implementation may provide built-in functions whose positional parameters do not have names, even if they are 'named' for the purpose of documentation, and which therefore cannot be supplied by keyword.  In CPython, this is the case for functions implemented in C that use :c:func:`PyArg_ParseTuple` to parse their arguments.</td></tr>
<tr><td>reference/simple_stmts.rst:231</td><td>In the current implementation, the syntax for targets is taken to be the same as for expressions, and invalid syntax is rejected during the code generation phase, causing less detailed error messages.</td></tr>
<tr><td>reference/simple_stmts.rst:863</td><td>The current implementation does not enforce the two restrictions, but programs should not abuse this freedom, as future implementations may enforce them or silently change the meaning of the program.</td></tr>
<tr><td>using/cmdline.rst:13</td><td>Other implementations' command line schemes may differ.  See :ref:`implementations` for further resources.</td></tr>
</table>

**Comment by hhsprings** [comment]
本質的には「directive でダイレクトにテキストを追加している CPython プロジェクトが悪い」のか「Sphinx の i18n に考慮不足がある」のかということなのでしょうけれど、対応に時間がかかりそうなら教えてください。最低でも上の表の「×」の部分は害にもなると思うので仮で「**CPython 実装の詳細:**」を補っておくなどしたほうが良いと思うので。

**Comment by hhsprings** [comment]
タイトルが相応しくなくなってきたのでタイトル変えました。

**Comment by methane** [comment]
仮対応はやめてください。翻訳メモリにノイズが増えるので。

**Comment by methane** [comment]
https://github.com/python-doc-ja/cpython-doc-intl/commit/b48d25f19552800793a1369550201db4fac412b7

http://docs.python.jp/3.5/library/sys.html#sys._debugmallocstats

versionchanged ディレクティブを参考に修正してみました。
良さそうなら upstream にパッチ投げます。
ただし sphinx extension 部分の多言語化の方法がわからないので、 versionchagned
ディレクティブと違って "**CPython implementation detail:**" 部分が翻訳されないのの
解決方法が分からないんですよね。どこかで聞いてみます。

**Comment by hhsprings** [comment]
ありがとうございますぅ。確認出来ました。

「見出しが消える」だと「致命傷」(のものもある)ですが、翻訳されない方は少なくとも致命傷ではないので…個人的にはまぁこのままでも当面良いのだろうなとは思います。

ちなみにその場合の「翻訳」って、どこですることになるんでしょうかね? 個々の rst からは独立した翻訳キーですものね。

**Comment by hhsprings** [comment]
問題がなさそうであれば 2.7 への適用もお願いします、ということでこの issue そのものは close して、「"CPython implementation detail:" 部分が翻訳されない」は[別 issue](https://github.com/python-doc-ja/python-doc-ja/issues/744) として残しておきます。毛色が違うと思うので。

**Comment by tk0miya** [comment]
@methane 反応遅れてごめんなさい。その修正で良さそうです。

>ただし sphinx extension 部分の多言語化の方法がわからないので、 versionchagned
>ディレクティブと違って "CPython implementation detail:" 部分が翻訳されないのの
>解決方法が分からないんですよね。どこかで聞いてみます。

`ImplementationDetail.run()` の中で
```
        label = sphinx.locale.translators['sphinx'].gettext(self.label_text)
```
というふうに翻訳をとりだそうとしているので、 `sphinx.po` を作って Sphinx が参照できるようにしてください。
`ja/LC_MESSAGES/sphinx.po` が入ったディレクトリへのパスを `conf.py` の `locale_dirs` に指定すれば ok だったはずです。

**Comment by methane** [comment]
@tk0miya 確認ありがとうございます。この修正で本家の方に投げてみます。

`sphinx.po` に入れるのは 1981c119e864fac7 でやってみました。
ダミーのテンプレートを用意して `make gettext` で `sphinx.pot` に抽出させています。
ちょっとハック感あふれてるので、もしこれよりもきれいな方法があったら教えてください。

**Comment by tk0miya** [comment]
@methane もうそっちも解決してたんですね。ちゃんと見てませんでした。

Sphinx では babel の extract_message を使って翻訳対象のメッセージを抽出していると聞いたことがあります。
http://babel.pocoo.org/en/latest/setup.html

どういう仕組みで対象の文字列リソースを抽出しているのかを把握していないのですが、これが使えるかもしれません。
(予想ですが `_("...")` という文字列をピックアップしているのかもしれません。それであれば `sphinx.locale:_()` を使うと良さそうです)
