### ISSUE TITLE
PyTypeObject.tp_members の説明の誤記

### ISSUE THREAD

**Issue by osamu0329nakamura** [python-doc-ja/python-doc-ja#732]
ドキュメント http://docs.python.jp/3/c-api/typeobj.html#c.PyTypeObject.tp_members
に、「配列の各要素ごとに、__メソッドデスクリプタ__ の入った要素が型の辞書・・・」とありますが、
原文には、a member descriptor とあるので、正しくはメンバデスクリプタでしょう。

**Comment by e-kwsm** [comment]
[Transifex (3.5)](https://www.transifex.com/python-doc-ja/python-35/) で修正しました．ご報告ありがとうございます．

**Comment by osamu0329nakamura** [comment]
ドキュメントに反映されていることを確認しました。ありがとうございます。
