### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by yoshrc** [python-doc-ja/python-doc-ja#735]
http://docs.python.jp/3/howto/logging.html#loggers
の三段落目の箇条書きのふたつ目が

> Logger.addHandler() と Logger.removeHandler() は、ハンドラオブジェクトをロガーオブジェクトから追加または削除します。ロガーオブジェクトにハンドラオブジェクトを追加または削除します。

となっており、同じ意味の文が反復しています。

**Comment by methane** [comment]
ありがとうございます。修正しました（反映には半日ほどかかります）
