### ISSUE TITLE
基本的なワークフローについてご質問

### ISSUE THREAD

**Issue by ShunSakurai** [python-doc-ja/python-doc-ja#736]
※2016/5/27 編集しました

最近グループに参加した者です。よろしくお願いいたします。
ドキュメント翻訳の基本的なことがわかっておらず、管理者の方に以下の6点をお伺いしたく思っています。

### Transifex の仕組みについて

Wikiなどを読んで、[ソースのGitHub](https://github.com/python/cpython/tree/master/Doc)からPOファイルというものを作成して、Transifexに読み込んでいるということまではわかりました。また、[Sphinx](http://www.sphinx-doc.org/en/stable/)というツールも使っていることがわかりました。

その作業は、どの程度の頻度で、どのような順番で行ってくださっているのでしょうか？
また、Transifexで翻訳した訳文は、どの程度の頻度で[オンラインドキュメント](http://docs.python.jp/3/)に反映されているのでしょうか？過去のIssueを見ていると、半日ほどかかるということでしょうか？

このあたりの簡単な流れを[HowToTransifex](https://github.com/python-doc-ja/python-doc-ja/wiki/HowToTransifex)などにまとめていただけると、非常にありがたいです。

### 原文が更新された場合の対応について

1つ目の質問に関連しているのですが、原文が大きく更新されている箇所を発見しました。
mathモジュールのfloor/ceil関数に関する記述が間違っていたのが、修正されています。

この場合、Transifexに入っているデータはまだ元のままなのですが、訳文のみ訂正することは可能でしょうか？
それとも、次にデータがインポートされるまで待った方がいいでしょうか？

以下は、変更箇所についての情報です。

> 英語版リンク: https://docs.python.org/3.5/library/stdtypes.html#numeric-types-int-float-complex
> 日本語版リンク: http://docs.python.jp/3/library/stdtypes.html#numeric-types-int-float-complex
> 
> Before:
> the greatest integral float <= *x*
> x 以下の最大の整数値を持つ浮動小数点数です
> 
> After:
> the greatest integral <= *x*
> x 以下の最大の整数(値)(です/を返します)
> 
> 変更された時のコミット: https://github.com/python/cpython/commit/116588fd16404271cbd30938fe32def1e816c557#diff-7498e907ba97646df434a0eb583c6909
> 
> ```
> >>> import math
> >>> x = 1.23
> >>> y = math.floor(x) # 1
> >>> type(x)
> <class 'float'>
> >>> type(y)
> <class 'int'>
> #実際に返されるのは'int'であることがわかります
> ```

### スタイルガイドについて

既存の訳を参考にしながら翻訳を進めているのですが、

- 全角文字と半角文字の間にスペースを入れるかどうか
- 括弧や約物は半角か、全角か
- 言葉遣い (「〜を参照してください」なのか、「〜を参照」なのか)

など、方針に迷うことがあります。
今のところは、周り方の訳文に合わせたり、IT翻訳業界で一般的な表記を使って翻訳を進めています。

従うべきガイドラインなどはありますでしょうか？

### レビューアについて

Transifexを見たところ、現在専属のレビューアはいらっしゃらないようです。これは、人数や分量から、レビューに割ける人員が確保できないからでしょうか？それとも、レビュー後に一般の翻訳者が翻訳を修正できなくなるような問題があるからでしょうか？

### Issueの報告について

GitHubで報告すべきIssueは、他の方の翻訳に修正が必要な場合には必ず出さなければならないものでしょうか？
また、その場合、該当箇所の翻訳を担当された方をparticipantに追加する必要/方法はありますでしょうか？

大変申し訳ないのですが、docを読んでPythonの勉強をしながら、「チュートリアル」「Python のセットアップと利用」「ライブラリーリファレンス（の途中まで）」を読み進める中で、誤訳や分かりづらい表現を勝手に多数直してしまいました。

必要がありましたら、すべて元に戻した上で、Issueに報告いたします。

### JapaneseとJapanese(Japan)について

Transifexのチームには、JapaneseとJapanese(Japan)という2つのグループがあるようです。前者の方が参加人数が多いようなのでこちらに参加したのですが、これらの違いを教えていただけますでしょうか？

以上、よろしくお願いいたします。

**Comment by methane** [comment]
個別に回答していきます。

## Transifex の仕組みについて

> その作業は、どの程度の頻度で、どのような順番で行ってくださっているのでしょうか？
また、Transifexで翻訳した訳文は、どの程度の頻度でオンラインドキュメントに反映されているのでしょうか？過去のIssueを見ていると、半日ほどかかるということでしょうか？

python.jp 上のドキュメントは今のところ私が管理していて、現状は以下のようになっています。
ただし、予告なく変更する可能性があるので、「更新には半日ほどかかります」とぼかした回答をしています。Web上で Last Updated が1日以上遅れていたら自動ビルドがコケてる可能性が高いので教えてください。（自動監視を作るのをサボってるので…）

> このあたりの簡単な流れをHowToTransifexなどにまとめていただけると、非常にありがたいです。

問題を見つけては適宜調整しているので、書いてもいつの間にか古くなって間違った情報になると思います。
翻訳作業に影響する部分をピンポイントに絞って書くのであれば可能だと思いますが…。

crontab -l

```
13 */4 * * * ~/local/bin/nightly.sh > ~/var/log/nightly.log 2>&1
```

local/bin/nightly.sh

```
echo "----"
date
echo "Python 3.5"
cd ~/python_doc/py35
git pull origin intl-3.5
cd Doc
tx pull -l ja
mkdir -p build/html build/doctrees
sphinx-build -D language=ja -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . build/html
rsync -rlCK --delete build/html/ ****

echo "----"
date
echo "Python 2.7"
cd ~/python_doc/py27
hg pull -u
tx pull -l ja
mkdir -p build/html build/doctrees
sphinx-build -A versionswitcher=1 -E -d build/doctrees . build/html
rsync -rlCK --delete build/html/ ****

date
echo "end"
```

**Comment by methane** [comment]
## 原文が更新された場合の対応について

> 1つ目の質問に関連しているのですが、原文が大きく更新されている箇所を発見しました。
> mathモジュールのfloor/ceil関数に関する記述が間違っていたのが、修正されています。
>
> この場合、Transifexに入っているデータはまだ元のままなのですが、訳文のみ訂正することは可能でしょうか？
> それとも、次にデータがインポートされるまで待った方がいいでしょうか？

待ってください。 Transifex 上で原文と乖離する訳文を追加してしまうと、翻訳メモリの誤学習による弊害があります。

原文の更新は、僕が時間があって気が向いた時に行われます。 3.5.1 のようなポイントリリースがされると「そろそろやらないとな」という気になる以外はほぼ不定期です。
ご報告いただいて「そろそろやらないとな」という気になったのでそのうちやります。

**Comment by methane** [comment]
## スタイルガイドについて

ガイドラインはありません。どこかにそのまま再利用しても良いガイドラインがあれば教えてください。

現状は、読みやすく、技術的に間違いがなく、上下の段落と著しく文体が変わっていないのであれば、問題はないと考えています。

**Comment by methane** [comment]
## レビューアについて

> Transifexを見たところ、現在専属のレビューアはいらっしゃらないようです。これは、人数や分量から、レビューに割ける人員が確保できないからでしょうか？それとも、レビュー後に一般の翻訳者が翻訳を修正できなくなるような問題があるからでしょうか？

前者です。
間違った訳は原文よりも悪い（信頼できない翻訳率100%より、信頼できる翻訳率30%の方が有益）ので、自信がないなら、その部分は飛ばして翻訳するか、MLにて相談してみてください。

**Comment by methane** [comment]
## Issueの報告について

Transifex で直接修正して頂いてかまいません。

## JapaneseとJapanese(Japan)について

後者、消したつもりでしたが、残ってましたか…また消しておきます。

日本語については、利用されてる地域ごとに翻訳を分ける必要性は皆無だと考えています。

**Comment by ShunSakurai** [comment]
methane様、

大変詳しく、また分かりやすくご説明いただきありがとうございます。

### スタイルガイドについて

ガイドラインについては、「これをすぐにそのまま適用できる」といったものは残念ながら知りません。
有名なガイドラインとしては、
[Microsoft スタイルガイド](https://www.microsoft.com/Language/ja-jp/StyleGuides.aspx)
[JTF 日本語標準スタイルガイド（翻訳用）](https://www.jtf.jp/jp/style_guide/pdf/jtf_style_guide.pdf)
また、個人的に親しんでいるガイドとして
[Gengo スタイルガイド(日本語)](https://gengo.com/wp-content/uploads/2014/02/style-guide-ja.pdf)
などがありますが、どれも細則まで読んでしまうと、かなり時間が取られてしまいます。

推奨するのは、
JTF 日本語標準スタイルガイドの「12 の基本ルール」や、
Gengo スタイルガイドの「1〜5」くらい
基本的なスタイルを決めてしまって、それだけを最低限守るということです。

ただし、既存の訳を手作業で修正すると膨大な時間がかかるので、現実的でないかもしれません。

### Issueの報告について

明確なご回答ありがとうございます。「間違った訳は原文よりも悪い」は本当におっしゃる通りだと思います。
明らかな修正はそのままTransifexで行い、疑問がある時だけ、Issueを作成するか、MLに投稿させていただきます。

### その他

また、以下の質問についてご回答いただいた内容は、私のような新参者が入った時に非常に重要です。

- 原文が更新された場合の対応について
- スタイルガイドについて
- レビューアについて
- Issueの報告について

これらをもし
トップページ: https://github.com/python-doc-ja/python-doc-ja/ または
HowToTransifex: https://github.com/python-doc-ja/python-doc-ja/wiki/HowToTransifex
などに掲載していただけたら大変ありがたいです。


最後に、お手数をおかけしますが、原文の更新と、Japanese(Japan)の削除をよろしくお願いいたします。
