### ISSUE TITLE
if only か、those ~ which か

### ISSUE THREAD

**Issue by ShunSakurai** [python-doc-ja/python-doc-ja#737]
URL: http://docs.python.jp/3/library/filecmp.html

原文
Note that via :meth:`__getattr__` hooks, all attributes are computed lazily, so there is no speed penalty if only those attributes which are lightweight to compute are used.

元の訳文
:meth:`__getattr__` フックを経由すると、全ての属性をのろのろと計算するため、速度上のペナルティを受けないのは計算処理の軽い属性を使ったときだけなので注意してください。

直訳
:meth:`__getattr__` フックを経由すると、すべての属性は遅延して計算されることに注意してください。そのため、計算処理が軽量な属性のみを使用した場合、速度上のペナルティは発生しません。

提案訳
:meth:`__getattr__` フックを経由すると、すべての属性は遅延計算されます。そのため、計算が軽量に行える属性しか使用しない場合、速度は低下しません。

以下の2点を変更しようかと考えています。

- computed lazily

ここでのlazyは、後で必要な時に、という意味ではないかと思います。
[遅延評価](https://ja.wikipedia.org/wiki/%E9%81%85%E5%BB%B6%E8%A9%95%E4%BE%A1) にあるように、「遅延」という訳を当てようと考えています。

- if only those attributes which are lightweight to compute are used.

元の訳では
if only /// those attributes / which are lightweight to compute // are used.
と区切って考えられているようですが、those ~ which ... (... の ~) というまとまりで考えて、
if /// only those attributes / which are lightweight to compute // are used.
と区切るべきでないかと思いました。

特に後者について、100%の自信がないため、どなたかに確認してお返事をいただけたら幸いです。

**Comment by e-kwsm** [comment]
> ここでのlazyは、後で必要な時に、という意味ではないかと思います。
> 遅延評価 にあるように、「遅延」という訳を当てようと考えています。

lazy は「遅延」でいいと思います．ただ，「遅延計算」は「遅延評価」ほどメジャーでなく，「どれくらい遅れているかの計算」に使われることが多いようです．

> 元の訳では
> if only /// those attributes / which are lightweight to compute // are used.
> と区切って考えられているようですが、those ~ which ... (... の ~) というまとまりで考えて、
> if /// only those attributes / which are lightweight to compute // are used.
> と区切るべきでないかと思いました。

その区切りで合っていると思います．
個人的には「軽量な属性のみを使用した場合」の方が好きです．

**Comment by methane** [comment]
"via :meth:__getattr__ hooks, " は、「〜すると」よりも「〜によって」などの方が良いと思います。
「すると」だと、利用側の利用手順によって使われたり使われなかったりするかのように読めますが、
実際には常に（最初の属性アクセスでは）利用されるからです。
また、語順を変えて「全ての属性」を先に持ってきた方が判りやすい日本語になると思います。
英語の語順を守ると、日本語として不自然に倒置法が多くなるからです。

lazy については、「遅延評価」は「オンデマンド」「ジャストインタイム」みたいな
「最初に必要になった時に初めて評価される」という意味で通ると思いますが、「遅延」だけだと
「タスクキューに積んで非同期処理する」「レプリケーションにかかる時間だけ結果が見えるのに
時間がかかる」みたいな意味にも取れることがあります。今回の場合は遅延だけでも誤解されない
のでいいと思います。

"Note that" は「〜注意してください」と訳すと元のヒント程度の意味よりも強く取られがちなので、
知らないと危険がある場合を除いて省略してもいいと思います。

**Comment by methane** [comment]
> 元の訳では
> if only /// those attributes / which are lightweight to compute // are used.
> と区切って考えられているようですが、those ~ which ... (... の ~) というまとまりで考えて、
> if /// only those attributes / which are lightweight to compute // are used.
> と区切るべきでないかと思いました。

どちらかというと

If //// only // those attributes / which are lightweight to compute /// are used

だと思います。(only のほうが are used より先に結びつく)
 those ~ which でひとつの関係代名詞になっていて、
「計算が軽い属性」（元は複数形だけど日本語だと違いなし）なので、
「計算が軽い属性だけを利用した場合は」かな。

**Comment by methane** [comment]
ということで私の提案

> Note: すべての属性は、 :meth:`__getattr__` フックを利用して遅延評価されるので、計算が軽い属性のみを利用する場合は、重い属性を計算するためのペナルティを受けません。

「重い属性を計算するための」を補足してみました。

**Comment by ShunSakurai** [comment]
素晴らしいご指摘ありがとうございます。

> 「遅延計算」は「遅延評価」ほどメジャーでなく
> 「〜すると」よりも「〜によって」などの方が良い
> 語順を変えて「全ての属性」を先に持ってきた方が判りやすい

自分では思いつきませんでした。2点目は元の訳に引きづられてしまいました。

> 「重い属性を計算するための」を補足

ありがとうございます。意味がより明確になりますね。
ただし、この場合は「遅延評価することにより、従来属性の計算に必ずかかっていた速度のペナルティが、属性がすべて軽い場合に限っては、ゼロになる（または小さくなる）」ということが言いたいと思うので、単に「属性を計算するための速度のペナルティ」としました。

また、「速度のペナルティ」というと、日本語読者は「スピード違反？」と一瞬よくわからず止まってしまうと思ったので、「速度の低下」と意訳しました。

いただいたご意見を踏まえて、以下のように訳すことにします。

すべての属性は :meth:`__getattr__` フックによって遅延評価されるので、計算が軽い属性のみを使用した場合は、属性の計算による速度の低下は起こりません。

ありがとうございました！
