### ISSUE TITLE
15.1. 表現エラー の誤訳

### ISSUE THREAD

**Issue by blue-9** [python-doc-ja/python-doc-ja#739]
http://docs.python.jp/3/tutorial/floatingpoint.html#representation-error

[原文]
Note that since we rounded up, this is actually a little bit larger than 1/10;

[訳]
丸め値を 1 増やしたので、この値は実際には 1/10 より少し小さいことに注意してください;

とありますが、「1/10より少し小さい」ではなく、「1/10より少し大きい」ではないでしょうか？

ご確認のほどよろしくお願いいたします。

**Comment by methane** [comment]
ありがとうございます。修正しました。
1日以内にサイトに反映されると思います。
