### ISSUE TITLE
unittestモジュールの誤訳 (fixture)

### ISSUE THREAD

**Issue by kmaehashi** [python-doc-ja/python-doc-ja#740]
いつもドキュメントのメンテナンスありがとうございます。

「クラスとモジュールの修正」節に「修正」という単語が数回出てきますが、これは「fixture」（テストフィクスチャ）の誤訳と思われましたのでご報告します。

http://docs.python.jp/3/library/unittest.html?highlight=unittest#class-and-module-fixtures
http://docs.python.jp/2.7/library/unittest.html?highlight=unittest#id13

**Comment by methane** [comment]
報告ありがとうございます。
Transifex 上で修正しました。(1日以内に反映されると思います)

**Comment by hhsprings** [comment]
すいませんこれ、まだ残ってません? 2.7 に「詳しくは `クラスとモジュールの修正`_ を参照してください。」を少なくとも発見。修正した、はず、なのですよね? 「フィクスチャ」に置換されるべき、ということでいいですよね? 見直しておきましょうか?

**Comment by methane** [comment]
Transifex を確認したら一箇所だけ残ってました（修正済み）。
が、サイトの方にはたくさん残ってますね。

build/doctrees に翻訳済みのほうがキャッシュされて再利用されてる可能性があるので、
ビルドスクリプトでそれを消すようにしてみました。手動でスクリプトをkickしたので
しばらくお待ちください。

**Comment by hhsprings** [comment]
了解です。
