### ISSUE TITLE
「Python » [プルダウン]  ドキュメント »」の「Python」のリンク先

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#741]
大昔に、確かまだ主役が2.7だった頃に、この「Python」部分、https://www.python.org/ ではなく http://www.python.jp/ を指すように変えてもらったことがありました。Transifex の範疇外になるのでむつかしいですかね? 利用者にはおそらくこれがベストだとは思うのですが。

**Comment by hhsprings** [comment]
あ、2.7 は .jp を指してる…。

**Comment by methane** [comment]
www.python.jp は www.python.org を翻訳したサイトではないし、もうリンクは org に向けてしまっても良いような…

**Comment by methane** [comment]
すごーくゆっくりですが、本家の docs の方でも他の言語をホスティングする話は出ているので、
多言語対応外のhtmlテンプレート部分を日本向けにカスタマイズするのは必要最低限にしたいです。

**Comment by hhsprings** [comment]
そうですよね…。そういう気はしてはいました(多言語ホスティングの話はワタシも気付いてました)。

実はこれに似た話はほかにもいくつか見つけていて、たとえばちょっと性質は違いますが「バグを見つけたら?」が翻訳プロジェクトに言及していなかったりもして、利用者にとってはどうなんだろうか、とは思うものの、これは Transifex だけでやろうとすれば「訳注」の形でしか補えなくて毎度悩ましいなぁとも思ってもいます。うーん、でもこれは都度都度考えるのかな…。

あ、もとの「.org 指しちゃえばいい」問題については個人的には御意です。一貫性がないのはマズい。

**Comment by cocoatomo** [comment]
既に言語ドロップダウンでのリンクが整備されているのでclose
