### ISSUE TITLE
(largely) drop-in replacementの訳について

### ISSUE THREAD

**Issue by ShunSakurai** [python-doc-ja/python-doc-ja#742]
xwhhspringsさんと Transifex のメッセージで話し合いましたが、皆さんのご意見も頂戴したいと思い、Issue Trackerに挙げさせていただきます。

Doc URL: http://docs.python.jp/3/distributing/index.html
Transifex URL: https://www.transifex.com/python-doc-ja/python-35/translate/#ja/distributing--index/68469779

原文: `setuptools`_ is a (largely) drop-in replacement for :mod:`distutils` first published in 2004.
現在の訳文: `setuptools`_ は :mod:`distutils` (の大部分)をそのまま置き換える後継プロジェクトで、2004 年に最初に公開されました。
解釈: setuptoolsの登場によって、distutilsの生態系の一部は変わってしまうけれど、ほとんどは維持される。

Transifexで履歴をご覧いただくとわかるように、drop-inの訳がかなり揺れています。

xwhhspringsさんは、http://ejje.weblio.jp/sentence/content/drop-in を例示してくださり、drop-in には「差し込む」「落とし込む」「プラグイン」と近いニュアンスがあり、「(不足分を補いつつ)丸ごと置換出来る」という「役割/貢献」について言っているという解釈で当初の訳をされていました。

私は、最初は http://ejje.weblio.jp/content/drop-in の日本語訳と http://www.thefreedictionary.com/drop-in でしか調べておらず、thefreedictionary の形容詞用法の一つ目の訳 "Provided for short-term use" を盲目的に当てはめてしまっていました。
その後、xwhhsprings さんからご意見をいただいて http://ejje.weblio.jp/content/drop-in を見直したところ、Wiktionary英語版の "fit to substitute some element in a complex system without changes to the existing infrastructure" という説明が非常にしっくりきました。

以上のような経緯から、現在は上記のような訳にしてありますが、本当にその理解で良いのか、ご相談させていただきたく思います。また、もう少し正確な訳、より良い表現がありましたら、ぜひご提案いただきたいです。

お手数をおかけいたしますが、よろしくお願いいたします。

**Comment by methane** [comment]
drop-in replacement とはかなり高い API 互換性を持っていて、置き換えてもそのまま使えるという意味でよく使われていて、ここでもその意味で使われていると思います。つまり、

```
from distutils import setup

setup(name="mypackage",
      version="1.0.2",
      ...
)
```

この `from distutils` を `from setuptools` に置き換えてもそのまま動く、という意味だと思います。

**Comment by ShunSakurai** [comment]
methane さん、非常に明快なご説明ありがとうございます。
大変よくわかりました。そうすると、「そのまま置き換える」という言葉も使えそうですが、もっと適切な表現がありそうですね。

setuptools_ は :mod:distutils (の大部分)をそっくりそのまま置き換える後継プロジェクトで

くらいしか思いつきませんが、いかがでしょう。明日くらいまでご意見を募集して close したいと思います。

**Comment by hhsprings** [comment]
> setuptools_ は :mod:distutils (の大部分)をそっくりそのまま置き換える後継プロジェクトで

これがいいかなぁ。

にしてもワタシの最初の訳はなにを考えていたのだろう? 「雰囲気」で訳しちゃったのだろうか。悩ましい訳だったことは確かです。(Transifex 側でコメントしたとおり、ほんとうに自分で訳したのかは全然覚えてはいないんですが。)

**Comment by ShunSakurai** [comment]
ありがとうございます！
昨日類語辞典をパラパラ見てみたら、「まるごと」がいい気がしたのでそうしました。
setuptools_ は :mod:distutils (の大部分)をまるごと置き換える後継プロジェクトで

closeします。
