### ISSUE TITLE
チュートリアル15.1の(or Perl, C, C++, Java, Fortran, and many others)...の訳について

### ISSUE THREAD

**Issue by Hirugao** [python-doc-ja/python-doc-ja#743]
原文では (or Perl, C, C++, Java, Fortran, and many others) となっているが、
日本語訳では(あるいは Perl、 C、 C++、Japa、Fortran 、およびその他多く)と、
java->japaになっています。
細かいこと言ってすみません。^^;

**Comment by methane** [comment]
ありがとうございます。 3.5 で修正しました。
