### ISSUE TITLE
ディレクティブ「impl-detail::」の見出し「CPython implementation detail:」を翻訳出来ない

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#744]
発端の issue は [#729](https://github.com/python-doc-ja/python-doc-ja/issues/729)。もとの issue は「CPython implementation detail:」そのものが消えてしまう問題だったが消える問題は解消。今回のこちらの issue はその見出しの翻訳が出来ない、という問題。致命傷とは言えない問題と思うが一応。

**Comment by methane** [comment]
fixed

**Comment by methane** [comment]
ごめんなさい、直ってなかった。

**Comment by hhsprings** [comment]
こちらのほうの issue は全然慌てる必要はないと思ってるのですが(というか個人的には問題だとさえ思ってなかったりしますが)、直りそうなのですか? (もしくはひょっとして「別 issue として上げなおし」に惑わされてしまったとか? だとしたらすいません。紛らわしいことして。)

**Comment by methane** [comment]
コード上は直したつもりです。
Transifex 上でも sphinx.po に反映されてます。
最新ビルドで sphinx.po の翻訳の取得が skip されてしまっていました。
タイミングの問題かもしれないので次回（深夜1時頃）の更新を待ってみます。

（そして完全に無関係だけど about.html にハングルが混ざっているのを見つけてしまった…
悪気はなさそうだったので Transifex 上で元に戻すだけにとどめておいたけど、繰り返されたら
何か対策が必要…）

**Comment by hhsprings** [comment]
あ、sphinx.po というのがいたのか…。初めて気付いたかもしれない。みました。これの一番上ですね。了解です。

**Comment by hhsprings** [comment]
ハングルはさすがにまったく読めないのでGoogle翻訳してみたら「この記事は、Pythonのドキュメントを主な目的として作成されたドキュメントプロセッサの `Sphinx`を利用して、` reStructuredText`形式のソースから生成されました。」でした :-/ どうでもいいですね。

**Comment by hhsprings** [comment]
2.7 は OK のようです。([using/cmdline)](http://docs.python.jp/2.7/using/cmdline.html)。
3.5 はまだ確認出来ない…。([using/cmdline)](http://docs.python.jp/3.5/using/cmdline.html)。

**Comment by hhsprings** [comment]
あ、ビルド中ですね。3.5 も行ってます。([library/dis](http://docs.python.jp/3.5/library/dis.html))

**Comment by methane** [comment]
2.7 の方は pyspecific という拡張が 3.5 と違うし、そもそもソースツリーをなるべく
upstream と同じにするというのを放棄しているので、 gettext を使わずに解決してしまっています。

3.5 の方は python.jp 上の作業ツリーで sphinx.pot が dirty で git の更新に失敗していました。
先程手動で直しました。
