### ISSUE TITLE
採用する Sphinx バージョンについてのメモ (ePub・chm に関係)

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#747]
今のところ何かしらアクションが必要だ、という話でもないのですが、ずっと気になっていたことでもあるので。

[#724](https://github.com/python-doc-ja/python-doc-ja/issues/724#issuecomment-168914957)、[#664](https://github.com/python-doc-ja/python-doc-ja/issues/664)、[#621](https://github.com/python-doc-ja/python-doc-ja/issues/621) など、たまーに、しかも繰り返して起こる要望についての「決定打」はまだないのだろうなぁ、とは思うのですが、「ePub でよくね?」に関してはそういえばここ半年以内に Sphinx で状況が変わっていたことを思い出しました。[version 1.4 で EPub3 Builder が追加](https://github.com/sphinx-doc/sphinx/pull/1779) されたのですよね。以前個人的に Windows で使える EPub ビューワを調べたことがあるんですが、「EPub 3 ならいいのに!」というビューワがありました。(EPub 2 を読めないビューワがあった。)→ **追記:** 「EPub 3 ならいいのに!」は(多分) Google の [Play Books](https://play.google.com/books)。1.3 までの epub ビルダの出力は NG。

今の翻訳プロジェクトで採用している 1.3.4 というのは、これは upstream がそうだから、ですか? ワタシ自身も新しい Sphinx を試してもいないのでなんともいえないですけれど、「新しくして何かハッピーになれそうだ」ということなら、つまり「EPub 3 でハッピーになれそうだ」ということであれば、これが [#724](https://github.com/python-doc-ja/python-doc-ja/issues/724#issuecomment-168914957) で言う「chm => docset, PDF => ePub へ移行」を後押ししたりはしないだろうか? と思いました。

chm をリプレイスするもの、は現実的なものは今のところないのでしょうね。これが一定の需要があるのは「インターネットに行けない環境でオフラインで読む必要がある開発者に配る」というニーズからと思っていますが、何かこれに近いものがあると良いのですがね。(ちなみに PDF へのニーズも根っこはほぼ同じで、「Microsoft Word でなければならないが PDF ならギリおっけー」という企業が多いから、です、たぶん。)

ちょっと本家の tracker みても Sphinx のバージョンについて言及している issue があるのかないのかよくわからない(検索すると全然関係ないものが大量にヒットしてしまう)ので、本家がどういうプランを持ってるのかがわからないですねぇ…。というか…、年末(?)にとうとう[本家が GitHub に引越してくる(はず)](http://www.youtube.com/watch?v=YgtL4S7Hrwo&t=9m27s)のでもっとわかりやすくなるのかなぁ。

すいません、なんかとりとめのない issue で。

**Comment by methane** [comment]
docs.python.jp で利用している sphinx は 1.4.6 にバージョンアップしてあります。
sphinx の開発者が日本人なので、人柱役も兼ねて積極的に新しいバージョンを使うことにしています。

http://docs.python.jp/3/
現在利用している Sphinx のバージョンは、このページの一番右下を見れば確認できます。

**Comment by hhsprings** [comment]
あ、そうなのですね。気付きませんでした。てことは「EPub 3 での配布」というのも「人柱」的にハッピー(誰の?)ですね、きっと。

**Comment by hhsprings** [comment]
メモ:

- 3.5.2 の locale なしのまま(つまり原文の)ビルダを epub3 に変えてみたが Google の Play Books はやはり NG。なんで?
- 同じ生成物を chrome 拡張の Readium で読めたが、「copy の entity 定義がない(たぶん &#copy; のこと)」というエラーが出ている
- [idpf の EPUB Validator (beta)](http://validator.idpf.org/)にかけたかったが受け付けてくれない(ERR_EMPTY_RESPONSE)。サイズ制限は超えてないのに…。(4MB なので全然制限に引っかかってない。)
- [www.epubconversion.com の ePub Validator](https://www.epubconversion.com/ePub-validator-iBook.php)が使えた。28個のエラー。Readium が指摘してくる copy も含まれている。Play Books で読めないのがこれのせいなのかどうかは「全部直してみないとわからない」のかな??

というわけで、すぐに「ePub 3 でいいんじゃね?」、というわけにもいかなそうですね。

**Comment by hhsprings** [comment]
Sphinx 1.5 (と DocUtils 1.3) という組み合わせで html5 ビルダのプランがあることがわかりました。ということはそれを待てば epub3 配布も夢ではないのかな、と。(ただし CPython ドキュメント固有の問題が若干わかっているので、それはそれとして CPython 本家に直してもらう必要あり。)

**Comment by hhsprings** [comment]
[CPython の方で措置しなければならないもの](https://github.com/hhsprings/nothing.but.only.for.some.kind.of.collabo/wiki/Sphinx-epub%EF%BC%8DCPython-%E3%81%AE%E6%96%B9%E3%81%A7%E6%8E%AA%E7%BD%AE%E3%81%97%E3%81%AA%E3%81%91%E3%82%8C%E3%81%B0%E3%81%AA%E3%82%89%E3%81%AA%E3%81%84%E3%82%82%E3%81%AE)。Sphinx チームの方の動きと同調しないとヘンなことになるので、タイミングを見計らって…。

**Comment by methane** [comment]
移行が完全に完了するまでは epub3_description と epub_description に同じ値を代入したらダメでしょうか？ > conf.py

**Comment by hhsprings** [comment]
そうかもしれませんね。ただ conf.py だけでなくまだ sphinx なのか cpython なのかわからないのが一つあるので、本家にあげるのはちょっと待つつもりです。

というかあれです、実際「翻訳プロジェクトへの適用→upstreamへ」の流れの方が理想的に思えてるんですが、どう思いますか?

**Comment by hhsprings** [comment]
補足です。epub3_description については、もともと今の CPython 本家で記述していないので、「sphinx 1.5 公式」が epub_description を採用するのを待てるなら、両方記述するのは意味がない、となります。翻訳プロジェクトとして先行して pre 1.5 を使うつもりがない限りは。

**Comment by hhsprings** [comment]
「Windows でインターネットに行けないので chm」な人たちにとって、「CPython として docset 配布 + [zeal](https://zealdocs.org/download.html)」は代わりとなりうるだろうか?

はじめて使ってみて感動しました。特に最近 docs.python.jp が重い気がしていたので。軽い、速い、使いやすい。

というわけで、「epub3 と docsets のみ配布」、が現実味を帯びてきた気が。

**Comment by methane** [comment]
zeal の存在は知っていたのですが、昔使ったときは、 Linux の gtk のせいもあって
あんまり完成度高くないイメージだったんですよね。今は Windows ではいい感じでしょうか。
それなら chm の代わりにはアリだと思います。 Mac の Dash は使いやすいですし。

オフラインといえば Linux では devdocs.io というオフライン対応Webアプリがあるんですが、
あれは docset じゃなかった。 Python には対応してるんですが、翻訳ドキュメントも
対応してくれるかなぁ。

**Comment by hhsprings** [comment]
[動画](https://www.youtube.com/watch?v=z44Dh87GlXc&t=1m44s)にしてみました。というかダウンロードとインストールが並列で動いてるだけでちょっと感動したりもしました。他愛もないことかもしれないですが。

zeal は linux 版も試してみようかな…。今手持ちなのは Fedora と CentOS か…。

**Comment by hhsprings** [comment]
ちょっとだけ悲しいお知らせです。原文でやったのと同じノリで locale を適用してみたら、新たな問題が増えました。

一つは「翻訳作業者の作業」に関係してます。あらら…。^G なんて制御文字を入れてしまった人、ハイパーリンクの rest の書き方を間違えてしまった人、2箇所。epub 3 配布を正とする場合は今より気をつけないといけませんね。(場所がわかったらあとで transifex で直しておきます。)

もう一方は sphinx-intl かもしれない。locale 入れずにやった際は出なかった「Error while parsing file 'Duplicate ID 'id2''」が多発。もちっと調べてから sphinx の ML に挙げます。

先が長いな、やっぱり。

**Comment by hhsprings** [comment]
いや…、「翻訳作業者の問題」ではないかも。intl 通さないと警告で無視されるハイパーリンクが、無視されずに置換されてそのまま流し込まれてしまう、ということか…。たとえば
```gettext
#: ../../library/subprocess.rst:479
msgid ""
"If specified, *env* must provide any variables required for the program to "
"execute.  On Windows, in order to run a `side-by-side assembly`_ the "
"specified *env* **must** include a valid :envvar:`SystemRoot`."
msgstr "*env* を指定する場合、プログラムを実行するのに必要な変数すべてを与えなければなりません。Windows で `Side-by-Side アセンブリ <side-by-side assembly>`_ を実行するためには、*env* は正しい :envvar:`SystemRoot` を **含まなければなりません** 。"
```
原文は「問題ありだが epub では問題がないようにみえてしまう」ということなんですね。

id重複の問題も「翻訳の問題」のものがありそうです:
```html
<p>上記のように、:c:member:<a href="#id1"><span class="problematic" id="id2">`</span></a>~Py_buffer.buf`はメモリブロック内のどの場所でも指すことが可能です。エクスポーターはこの関数を使用することによってバッファの妥当性を確認出来ます。</p> <!-- error pos (482) -->
```
これ、rest インラインマークアップの前後に空白入れ忘れてますね。うーん、これらを全部つぶしてからじゃないと sphinx の問題かどうかわからない。キツい…。

**Comment by hhsprings** [comment]
#751、[sphinx-users-jp](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/sphinx-users-jp/jZ5Iggvf5zk)。

**Comment by hhsprings** [comment]
ただのメモ: [CPython 翻訳からインラインマークアップの間違いを検出したい](https://github.com/hhsprings/nothing.but.only.for.some.kind.of.collabo/wiki/CPython-翻訳からインラインマークアップの間違いを検出したい)

**Comment by hhsprings** [comment]
さらにメモ: [CPython 原文と翻訳のリンクターゲットの差異を検出したい](https://github.com/hhsprings/nothing.but.only.for.some.kind.of.collabo/wiki/CPython-原文と翻訳のリンクターゲットの差異を検出したい)

ただこれは(sphinx-users-jp ML での稲田さんの発言を発端にはしているものの)この issue とはちょっとかけ離れてきたか…。(epubバリデーションの点数を上げる、これにはリンクチェックも時々やるといいよね、という発想なのでワタシ的には地続きではあるけれども。)

**Comment by cocoatomo** [comment]
特に進展が無いのでclose
