### ISSUE TITLE
Google Groups のほうの python-doc-jp

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#748]
まさについさっき気付いたのですが。

記憶が正しければ…[python-doc-jp](https://groups.google.com/forum/#!forum/python-doc-jp) は翻訳プロジェクトのための ML、でしたよね? (移行から半年以上経って既に忘却しつつある…。)

ちょっと「ワタシがそうだったので」で断言するのも乱暴なんですが、Google Group の機能がデフォルトでメールを送ってくれない(「My Settings」→「Membership and email settings」→「Email delivery preference」のデフォルトが「Don't send」)ために、質問があったことに気付かなかった方が多かった、ということはないですか?

6月に「Jupyter/IPython Notebook化したPythonチュートリアル(暫定版)」なんてのが来てますが、私は全然気付きませんでした。今これに誰一人反応していないのが「誰も気付かなかった」からなのか「誰も反応しようと思わなかった」なのか定かではないですが、少なくとも内容としては翻訳プロジェクト参加者が何かしら反応しても良い内容なのかなと思いました。(まぁ「ここでやることじゃないでしょうね」という答えにはなる気はしますが。)

現状として [python-doc-jp](https://groups.google.com/forum/#!forum/python-doc-jp) が受け皿として機能していないのかな、と思います。たぶん誘導の仕方を改善するか、「プロジェクト参加者が積極的に ML を活用する」かどちらかをしないといけないのかなぁと思います。

**Comment by methane** [comment]
少なくとも私は、気づいていた上で、返信を作文するコストを払う気になるほど
興味を惹かれなかったので反応しませんでした。

記憶が正確ではないかもしれませんが、更新＆メンテナンスする方法が考えられてない上に、
メンテナンスを丸投げするつもりなのかな？と思った気がします。

**Comment by hhsprings** [comment]
ワタシも気付いた上で当時反応しただろうかといえば正直「？」です(書いた本人には申し訳ないが私にとっても「無責任な投稿」が第一印象なのは同じ)。ただ、それはそれとしても、今のこの Google Group の意味、については、えーとこれは多分稲田さんが、ということではなく、「プロジェクト参加者で」コンセンサスを作っておいた方がいいのかな、とは思いました。

**Comment by hhsprings** [comment]
うーん。読めば読むほど「絶対反応したくないなぁ、ほっとこ」と思ったに違いない、と思えてきた。皆そうだったんですかね。そもそもこの半年でたった3件しか動いてない ML なので、何か結論的なことを言うのは早いのかもしれないですね。

**Comment by hhsprings** [comment]
なんか考えるのが馬鹿らしい「タイミング」な気がしてきました。急に活発になるような事件でも起これば価値がある議論かもしれないですが、今はどうでもいいかもしれない。そのときになったら考える、でも多分良いのでしょうね。なので今これが open になってる意味はなさそうなので、close します。すいません、無駄なこと考えさせてしまって。
