### ISSUE TITLE
https 使いたい。あわよくば http2 使いたい

### ISSUE THREAD

**Issue by methane** [python-doc-ja/python-doc-ja#749]
## 前提: python.jp の役割は増やさない

http2 を使うなら apache は良くなくて、手前に nginx とか入れることになるけど、
ぶっちゃけ面倒。
## 案1: python.jp の前に CloudFlare を置く

無料プランで実現できそう。
http://qiita.com/superbrothers/items/95e5723e9bd320094537
https://support.cloudflare.com/hc/en-us/articles/214820528-How-to-Validate-a-Let-s-Encrypt-Certificate-on-a-Site-Already-Active-on-CloudFlare

デメリットは、 Let's Encrypt の更新をサボると見れなくなる。
## 案2: github pages

docs.python.jp は当面 http で維持しつつ、 python-doc-ja.github.io で同じサイトを立ち上げる。
*.github.io なら github が https 化してくれる。

デメリットは、 docs.python.jp という本家のURLと対称性が良いドメインを捨てることになる。
## 案3: 現状維持

docs.python.org で多言語対応するのを気長に待つ。

**Comment by methane** [comment]
案4: Google Firebase hosting

**Comment by cocoatomo** [comment]
@methane python.jp が https になったのに伴い自然と解決, ということでクローズ?

**Comment by methane** [comment]
はい。CDNはとりあえず見送り。
