### ISSUE TITLE
wiki/HowToTransifex 「reST の インラインマークアップ を参照してください。」→ 404 Not Found

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#750]
細かい話なのですが、[HowToTransifex](https://github.com/python-doc-ja/python-doc-ja/wiki/HowToTransifex) で http://docs.python.jp/2/documenting/rest.html#inline-markup を指してます(404 Not Found)。

昔の py27 をみると確かに documenting/ がいて building.rst、fromlatex.rst、index.rst、intro.rst、markup.rst、rest.rst、sphinx.rst、style.rst、jptranslation.rst がいますが、今いなくなっていますね。

気になっているのは Wiki の方よりはむしろ documenting/ がいなくなっていることの方で、おそらくこれは間接的にはワタシの「py27 PO 化」が影響したのですよね?

あまり昔のことは良く理解できていないのですが、この documenting/ に対して「"Documenting Python"」の翻訳です」と言っており、これは CPython プロジェクト本体とは別のドキュメントだったのでしょうか?

なおワタシの手許にもこれらは残っていますし、履歴から復元したりも出来るのでしょうけれども、これらをなんらか別の場所に復活させるのが良いのか、新しい Sphinx ドキュメントにリンクした方が良いのかはワタシには良くわからないですが、あるいは復活させるなら単に Wiki にコピーしてしまうという手もあったりするのかな、とも思ったりはしますし…あと「今となっては廃れてしまっている説明」のチェックと修正のコストも馬鹿にならないよな、と思うと、単に「適切に新しい Sphinx ドキュメントにリンク先を見つけた方が早い」のかもしれない、とも思います。

いずれにしてもこれらは「翻訳作業者向け」ドキュメントと思うので、あまり優先度は高くないのだとは思いますが一応。

**Comment by methane** [comment]
昔は Python のドキュメントの一部だったのですが、今は devguide の方に移動しています。
https://docs.python.org/devguide/

**Comment by hhsprings** [comment]
ありがとうございます、理解できました。

問題の「documenting/」は単一の [documenting.html](https://docs.python.org/devguide/documenting.html) になってますね。Wiki からはここへ飛ばすということですかね。ひとまず。

**Comment by hhsprings** [comment]
なんで見つけられなかったんだろうと思ったら、[docs.python.org](https://docs.python.org/3/)の index からのリンクがなく  [www.python.org/doc/](https://www.python.org/doc/) (または [www.python.org/](https://www.python.org/)) からのリンクしかないからなのですね。今翻訳プロジェクト公式の日本語リソースからはどこからも辿れないんですね…。

**Comment by cocoatomo** [comment]
特に進展も無いのでclose
