### ISSUE TITLE
誤記 (テキストふぁいる)

### ISSUE THREAD

**Issue by kmaehashi** [python-doc-ja/python-doc-ja#752]
http://docs.python.jp/2/glossary.html#term-file-object

> ファイルオブジェクトには3つの種類があります: バイナリファイル、バイナリバッファ、テキストふぁいる。

**Comment by hhsprings** [comment]
「ふぁいる」の問題とインラインマークアップを Transifex で修正しました。

が、元々の「aw binary files, buffered binary files and text files.」が「バイナリファイル、バイナリバッファ、テキストファイル」でいいのかちょっと。全体で統一されてるならいいのかな…。

**Comment by hhsprings** [comment]
3.x訳「ファイルオブジェクトには3つの種類があります: 生のバイナリーファイル、バッファされたバイナリーファイル、そしてテキストファイルです。 これらのインターフェースは :mod:`io` モジュール内で定義されています。 ファイルオブジェクトを作成する標準的な方法は :func:`open` 関数を利用することです。」を採用しました。こちらの訳出の方が普通だとは思う。

**Comment by cocoatomo** [comment]
Python 2.7 の方も同じ訳文を適用しました.

ビルドされた HTML で修正が確認できたら, issue をクローズします.

**Comment by cocoatomo** [comment]
2.7 でも修正された訳文が適用されていることを確認しました.
