### ISSUE TITLE
誤記 (urllib.parse)

### ISSUE THREAD

**Issue by kmaehashi** [python-doc-ja/python-doc-ja#753]
http://docs.python.jp/2/library/urllib.html#module-urllib

> 注釈:  urllib モジュールは、Python 3 で urllib.request, urllib.parse, urllib.parse に分割されて名称変更されました。

最後の ``urllib.parse`` は ``urllib.error`` の誤記と思います。

**Comment by hhsprings** [comment]
Transifex で修正しました。数時間程度でサイトに反映されるはず。

**Comment by kmaehashi** [comment]
:+1: ありがとうございます！
