### ISSUE TITLE
インラインマークアップ、ハイパーリンクターゲットの「原文の方の」誤りメモ

### ISSUE THREAD

**Issue by hhsprings** [python-doc-ja/python-doc-ja#754]
これを読まれるどなたも当座何も反応しなくて結構です。

現在 [CPython 原文と翻訳のリンクターゲットの差異を検出したい](https://github.com/hhsprings/nothing.but.only.for.some.kind.of.collabo/wiki/CPython-%E5%8E%9F%E6%96%87%E3%81%A8%E7%BF%BB%E8%A8%B3%E3%81%AE%E3%83%AA%E3%83%B3%E3%82%AF%E3%82%BF%E3%83%BC%E3%82%B2%E3%83%83%E3%83%88%E3%81%AE%E5%B7%AE%E7%95%B0%E3%82%92%E6%A4%9C%E5%87%BA%E3%81%97%E3%81%9F%E3%81%84) なんてことをチマチマとチェック・修正しています。このチェックで原文が間違ってる箇所があったので、本家に報告する必要があると思っていますが、今見つけた一箇所ということでなく、報告はまとめて、としたいので、ここに列挙していきたい、ということです。

とりあえず2つ。
- whatsnew 内に剥き身の「<code>2**31</code>」のようなのがあって、これはクオートしなければならない。(翻訳も同じ。) 2箇所。
- FAQ/extending に原文では :c:func:`PyListSize` を指している箇所がある(これは原文の誤り)。翻訳では正しく :c:func:`PyList_Size` を指している。

**Comment by hhsprings** [comment]
補足。これで見つかるものは基本的に「めったに致命傷じゃない」ので、躍起になって探して回る必要はないです。ワタシが個人的に「epub バリデーションの点数をあげたい」というゴールに向けての作業の一貫としてノンビリやってます。

**Comment by hhsprings** [comment]
What's New in 3.4 内。
原文:
```
The module supports new :mod:`~stat.ST_MODE` flags, :mod:`~stat.S_IFDOOR`, :attr:`~stat.S_IFPORT`, and :attr:`~stat.S_IFWHT`. (Contributed by Christian Hiemes in :issue:`11016`.)
```

翻訳:
```
モジュールは新たに :func:`~stat.filemode` フラグの :mod:`~stat.S_IFDOOR`, :attr:`~stat.S_IFPORT`, :attr:`~stat.S_IFWHT` をサポートします。 (Contributed by Christian Hiemes in :issue:`11016`.)
```

これはアタシだわ…。ご丁寧に Transifex のコメントに説明入れてた:
```
原文の「new :mod:`~stat.ST_MODE` flags」は多分間違いと思うので「:func:`~stat.filemode` フラグ」にしておいた。(まず ST_MODE は「モジュール」ではないと思う、というのが根拠だけれど、プラットフォーム固有モジュールの可能性があるのでこれはなんとも言えない。ほんとにあるモジュールかも。つまり間違いではない可能性があるのだが、ただ、むろん :func:`~stat.filemode` が正しいのは自明で、「library/stat.html#stat.filemode」での versionchanged とも整合する。つまり原文と表現が違っても少なくとも実害はなにもない。)
```

What's New の間違いって割とどうでもいいてのもあるしなぁ…。(結構 What's old を頻繁に更新されると翻訳側で弱るというのもあるし。)

**Comment by cocoatomo** [comment]
特に進展が無いのでclose
