### ISSUE TITLE
math.fsum の loss of precision は「桁落ち」ではありません

### ISSUE THREAD

**Issue by metanest** [python-doc-ja/python-doc-ja#757]
『Python 標準ライブラリ』の§9.2.1にあるmath.fsumの解説文中にある「桁落ち」ですが、ここの原文 loss of precision が言及している「精度のロス」は、桁落ち（cancellation）のことではありません。
sumの計算を使うような例、たとえば数値積分などで刻みを極端に細かくしたとすると、部分和に対して増加分が極端に小さくなり、桁落ちではなく「情報落ち」が著しくなります（「積み残し」等と表現されます）。fsumは、その「積み残し」分を「拾って保存しておいて、適切に(部分)和に反映する」という手法を実装しています。
ですので、ここは原文を直訳にして「精度のロス（loss of precision）」としたほうが良いかと思われます。

（以下については、翻訳の問題ではないので、以上について反映していただければ、そのままこのissueはクローズしていただいてかまいません）

なお、翻訳の問題ではないのですが（英語版の時点からの問題として）、コード例として示されている「10個の0.1の総和」は誤解を招く恐れがあります。例として、

```
import math

for i in range(1, 11):
    x = [0.1] * i
    print(float(i)/10.0, math.fsum(x))
```

これを実行すると、次のようになることでわかると思うのですが、

```
0.1 0.1
0.2 0.2
0.3 0.30000000000000004
0.4 0.4
0.5 0.5
0.6 0.6000000000000001
0.7 0.7000000000000001
0.8 0.8
0.9 0.9
1.0 1.0
```

このようにfsumは、必ずしも「理想的な0.1」を「理想的に足した結果」を返してくれるものではありません。0.1は通常の浮動小数点表現方式で表現する限り誤差が避けられず、2のべきより少し小さい倍のあたり（ 3 とか 6, 7 とか）の所ではその影響が出てきます。10倍が単に運が良いというだけなのですが、知識の無い読者が誤解するおそれがあります。

**Comment by methane** [comment]
ありがとうございます。とりあえず翻訳の方は提案されたとおり「精度のロス」に修正しました。
サンプルは確かに指数部が大きく違う数の総和にした方が良さそうですね。

**Comment by metanest** [comment]
後から気がついたんですが、チュートリアルの§15.1の直前のあたりにも同じような箇所がありました http://docs.python.jp/3/tutorial/floatingpoint.html#representation-error

**Comment by cocoatomo** [comment]
指摘された箇所を修正しました.
「桁落ち」→「精度のロス」
「落ちた桁」→「失われた数字」

次回のビルド後に確認します.

**Comment by cocoatomo** [comment]
改めて読み直して「落ちた桁」→「失われた桁」の方にしました.

**Comment by cocoatomo** [comment]
修正の反映が確認できたのでクローズします.
