### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by maru8m** [python-doc-ja/python-doc-ja#759]
http://docs.python.jp/2/library/glob.html
s/不貞/不定

http://docs.python.jp/3/library/glob.html
では問題ないようです。

**Comment by e-kwsm** [comment]
[transifex の Python 2.7](https://www.transifex.com/python-doc/python-27/translate/#ja/library--glob/) を修正しました

**Comment by e-kwsm** [comment]
反映されました
http://docs.python.jp/2/library/glob.html?highlight=%E4%B8%8D%E5%AE%9A

**Comment by cocoatomo** [comment]
翻訳が直っているようなのでクローズします.
