### ISSUE TITLE
transifex 上の更新が反映されない

### ISSUE THREAD

**Issue by e-kwsm** [python-doc-ja/python-doc-ja#760]
[transifex の Python 3.5](https://www.transifex.com/python-doc/python-35/dashboard/) の翻訳を行いましたが，ここ数日の更新が[ドキュメント](http://docs.python.jp/3.5/index.html)に反映されていません．
まだ 3.6 には移行していませんよね？

**Comment by methane** [comment]
はい、 Python 3.6 とは別件で、 python.jp の移管を気に自動ビルドの手順を見直し中で、
まだ再開できていません。

**Comment by e-kwsm** [comment]
2 系もですか？ (#759)

**Comment by methane** [comment]
はい。

**Comment by cocoatomo** [comment]
この件に関し Google Group の方で情報共有していますので, よろしければそちらも参照してください.

https://groups.google.com/forum/#!topic/python-doc-jp/EB35cDL62_g

**Comment by e-kwsm** [comment]
分かりました．お返事ありがとうございます．

**Comment by e-kwsm** [comment]
#762
