### ISSUE TITLE
Wiki/HowToBuild の内容が現状に即していない?

### ISSUE THREAD

**Issue by taotao54321** [python-doc-ja/python-doc-ja#761]
未訳部分を少し翻訳してみたのですが、アップロード前に HTML 出力を確認したいと思い [HowToBuild](https://github.com/python-doc-ja/python-doc-ja/wiki/HowToBuild) を見てみたところ、どうも内容が現状に即していないようでした。具体的には:

* Doc/requirements.txt が存在しない
* make html の前に conf.py の設定が必要

Transifex や Sphinx のドキュメントを読んで試行錯誤してみましたが、現在の正しい手順は以下のような感じでよいのでしょうか?

```shell
$ pyvenv . # 必要なら

$ git clone https://github.com/python-doc-ja/cpython-doc-intl
$ git checkout intl-3.5 # 自動で行われるので不要?

$ pip install Sphinx
$ pip install transifex-client

$ tx pull -l ja # 要アカウント

$ echo "locale_dirs = ['locale/']" >> conf.py
$ echo "gettext_compact = False" >> conf.py
$ echo "language = 'ja'" >> conf.py

# Doc/locale/ja/LC_MESSAGES/*.po を翻訳

$ make html
```

とりあえず以上の手順で確認を行いつつ library/mmap.po を翻訳して Web からアップロードしてみました。見た感じ正しく反映されているようですが、誤りなどあったらすみません。
※既に翻訳されている部分で気になった点も少し修正したのですが、Transifex 上では反映されませんでした。これは Transifex の Web エディタ上で提案として入力する必要があるということでしょうか。

手元で HTML 出力を確認する方法がわからないと、マークアップの誤りがないか心配になったりして新規参加者にとっては辛いので、お時間があるときにでも内容を更新していただければと思います。

**Comment by cocoatomo** [comment]
> ※既に翻訳されている部分で気になった点も少し修正したのですが、Transifex 上では反映されませんでした。これは Transifex の Web エディタ上で提案として入力する必要があるということでしょうか。

これについては #760 にもあるように, 自動ビルドの仕組みを整備中なので自動反映できていない状態です.
もう少々お待ちください.

私は詳しく把握しているわけではないですが, 実施されたビルド手順でたぶん大丈夫だと思います.

**Comment by cocoatomo** [comment]
@taotao54321 

HowToBuild のページを直しました.
確認をお願いします.
https://github.com/python-doc-ja/python-doc-ja/wiki/HowToBuild

**Comment by cocoatomo** [comment]
@taotao54321 
いったんこの issue を閉じます.
何か問題があれば再度 open していただければと.

**Comment by e-kwsm** [comment]
wiki/[翻訳手順](https://github.com/python-doc-ja/python-doc-ja/wiki/HowToTransifex) などで 3.5 のままの箇所がありますが，編集権がない (?) のか修正できません．
ご対応願います．

**Comment by cocoatomo** [comment]
@e-kwsm 
[HowToTransifex](https://github.com/python-doc-ja/python-doc-ja/wiki/HowToTransifex) を修正しました.
差分: https://github.com/python-doc-ja/python-doc-ja/wiki/HowToTransifex/_compare/7f77c4c0d8f3b23f083a8f3286f065e6d278a0a6...c4b8512b591f95b40608e6bb15965f8e4df105de

ご確認ください.

[memo](https://github.com/python-doc-ja/python-doc-ja/wiki/memo) はただのメモなので 3.5 はそのまま放置してあります.

**Comment by e-kwsm** [comment]
ありがとうございます．

[QandA どのバージョンを翻訳していますか？](https://github.com/python-doc-ja/python-doc-ja/wiki/QandA#%E3%81%A9%E3%81%AE%E3%83%90%E3%83%BC%E3%82%B8%E3%83%A7%E3%83%B3%E3%82%92%E7%BF%BB%E8%A8%B3%E3%81%97%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%81%8B)  で

>Python 2.7 と、 Python 3 の最新リリース版です。 (2016年6月現在は 3.5 です)

となっていますが，こちらもお願いします．

**Comment by cocoatomo** [comment]
修正しました.

**Comment by e-kwsm** [comment]
ありがとうございます．
