### ISSUE TITLE
py27 github pages の作成

### ISSUE THREAD

**Issue by methane** [python-doc-ja/python-doc-ja#762]
py35 の方は cron 仕込みました。 (まだこれから初回の実行が走るまで完成したとは言えません)

python.jp で実行しているタスクは以下のとおりです。

```
$ crontab -l
...
7 1-23/4 * * * ~/.local/bin/nightly
57 1-23/4 * * * ~/.local/bin/nightly2

# transifex から py35-locale に取り込み
$ cat nightly
#!/bin/bash

export PATH=$HOME/.local/bin:$PATH

set -Ceux

cd ~/work/py35-locale
git pull
tx pull -lja
git commit -av -m "auto commit"
git push origin master

# github pages から nginx のドキュメントの更新
$ cat nightly2
#!/bin/bash
set -Ceux
export PATH=$HOME/.local/bin:$PATH

cd /var/www/html/doc/3.5
git pull
```

これ以外はすべて Travis へ移行しました。 (cron も Travis のベータ機能があるのですが、まだ1日1回しか動かせないので)

同じ仕組みが 2.7 でも動くように、 @cocoatomo さんに py27 の整備をお願いしてもいいでしょうか？

* py27-locale 単体で tx pull が出来るように、 .tx/config を cpython-intl から py27-locale に移動する。(設定ファイル内の相対パスの一括置換が必要)
* py27 という名前のリポジトリを作って github pages にする。(ルートディレクトリに `.nojekyll` というファイルが必要)
* py27-locale の push で Travis が動くように、 Travis と .travis.yml の設定。 (py27 に push するために、TOKEN作って travis encrypt で暗号化しています)

**Comment by cocoatomo** [comment]
> 同じ仕組みが 2.7 でも動くように、 @cocoatomo さんに py27 の整備をお願いしてもいいでしょうか？

OKです.

**Comment by cocoatomo** [comment]
> py27 という名前のリポジトリを作って github pages にする。(ルートディレクトリに .nojekyll というファイルが必要)

https://github.com/python-doc-ja/py27 というレポジトリが既にありますが, 内容を見ると原文の .rst ファイルが置いてあるのですが, これはどんな役割のレポジトリなのでしょうか?

**Comment by methane** [comment]
Python 2.7 があとから gettext 化対応したので、そっちの原文ですね。
py27-intl にリネームしておきました。

**Comment by cocoatomo** [comment]
日本語版用に置き換えている index.html (tools/templates/indexcontent.html かな) などが必要です.
現在のドキュメントをビルドしている環境から日本語版用のファイルをコピーしようと思ってますが, https://github.com/python-doc-ja/py27-intl から取ればいいですか?

**Comment by methane** [comment]
はい、今のドキュメントは py27-intl をベースにビルドしています。

**Comment by cocoatomo** [comment]
py27の環境整備があらかた終わりました.
後はpy27用のスクリプトをcronに登録するだけです.
py35の真似をして以下のようなスクリプトで良いと思います.

```bash
$ cat nightly_27 
#!/bin/bash

export PATH=$HOME/.local/bin:$PATH

set -Ceux

cd ~/work/py27-locale
git pull
tx pull -lja
git commit -av -m "auto commit"
git push origin master

$ cat nightly2_27
#!/bin/bash
set -Ceux
export PATH=$HOME/.local/bin:$PATH

cd /var/www/html/doc/2.7
git pull
```

**Comment by methane** [comment]
ありがとうございます。cron 仕込み終わりました。
