### ISSUE TITLE
cpython-doc-intlのintl-27ブランチに.tx/configが無い

### ISSUE THREAD

**Issue by cocoatomo** [python-doc-ja/python-doc-ja#763]
Docの下にpy27-localeと同じものを作る。pathが違ってるはずなので注意。

**Comment by methane** [comment]
使わなくなったのでなくても良いですよ。
むしろ intl-35 から消したほうが upstream の差分減るので良いかと。

**Comment by cocoatomo** [comment]
了解です。じゃあ、同じ意味のファイルは複数管理しない方針で、intl-35の.txを消しましょう。
