### ISSUE TITLE
誤記：Python チュートリアル » 9.クラス

### ISSUE THREAD

**Issue by yambe2002** [python-doc-ja/python-doc-ja#765]
「9.2. Python のスコープと名前空間」に『最束縛』が３つありますが、『再束縛』の誤記かと思います。
(原文はrebind)

https://docs.python.jp/3/tutorial/classes.html

**Comment by cocoatomo** [comment]
誤植報告ありがとうございます.

訳文の「最束縛」を「再束縛」に修正しました.

次のドキュメントビルドの結果を確認してから issue を閉じます.

**Comment by cocoatomo** [comment]
3箇所とも直っていました.
