### ISSUE TITLE
json.loads の引数の型

### ISSUE THREAD

**Issue by mjyuta** [python-doc-ja/python-doc-ja#766]
http://docs.python.jp/3/library/json.html#json.loads

> Changed in version 3.6: s can now be of type bytes or bytearray. 

の訳、

> バージョン 3.6 で変更: s は bytes 型か、 bytearray 型になりました。

ですが、 依然として `str` 型も使えるので、
「 s には bytes 型と、 bytearray 型も許されるようになりました。」
などが適当かと思います。

**Comment by cocoatomo** [comment]
報告ありがとうございます.
確かにこれは誤訳ですね. 翻訳例もいただきありがとうございます.

訳文を修正したので, 次回のビルドの HTML を見て直っていることを確認してからクローズすることとします.

**Comment by cocoatomo** [comment]
HTMLに修正が反映されたのを確認しました。
