### ISSUE TITLE
union typeの訳語

### ISSUE THREAD

**Issue by eldesh** [python-doc-ja/python-doc-ja#768]
python3.6.1の型ヒントについてのドキュメントについて。

> 直和型; Union[X, Y] は X または Y を表します。
> https://docs.python.jp/3/library/typing.html#typing.Union

のようになっていますが、`union` は直和(direct sum)ではないので修正するべきだと思います。
挙動としても `Union[int, str, int] == Union[int, str]` となるようなので直和ではなく`和`ですね。
替わりに使用する訳語としては`合併型`がいいと思います。

**Comment by methane** [comment]
直和型で検索してみてください。
すでに広まってる訳語なので、あえて区別するべき違いがない限りは従うべきだと思います。

2017/07/18 午後11:58 "eldesh" <notifications@github.com>:

**Comment by methane** [comment]
https://blog.miz-ar.info/2015/01/union-types/

ごめんなさい、それも踏まえたご指摘ですね。失礼しました

2017/07/19 午前0:06 "INADA Naoki" <songofacandy@gmail.com>:

**Comment by cocoatomo** [comment]
確かに (一般に使われる用語の) 直和型ではないので別の訳語にするべきですね.

union は難しい英単語でもないですし,「ユニオン型」と訳してもよいと思っていますが, いかがでしょうか?

**Comment by atsuoishimoto** [comment]
ユニオン型 +1

**Comment by eldesh** [comment]
そうですね。
私も「ユニオン型」でいいかなと思います。

**Comment by cocoatomo** [comment]
原文に "union", 訳文に「直和」を含むものを検索して修正しました.

https://www.transifex.com/python-doc/python-36/translate/#ja/$/108417870?qt=%E7%9B%B4%E5%92%8C&q=union
