### ISSUE TITLE
引用符が鉤括弧に置き換えられてしまう

### ISSUE THREAD

**Issue by cocoatomo** [python-doc-ja/python-doc-ja#771]
(shimizukawa 氏による報告)

https://docs.python.org/ja/3/library/functions.html#print のドキュメントで、引用符が鉤括弧に置き換えられてしまっている。
![image 1](https://user-images.githubusercontent.com/223050/31239440-0c0107d4-aa38-11e7-9fde-7f827b4f1d7b.png)

http://docs.python.jp/3/library/functions.html#print では、この現象は起きていない。

これは docutils の smart quotes によるもの。

**Comment by methane** [comment]
これどこで直すのが良いんでしょうね。
docutils か sphinx か。

**Comment by methane** [comment]
`docutils` の設定を直してもらうにしても、これ、 Sphinx の設定ファイルからは設定できなくて、
`docutils.conf` を修正してもらう必要がある？？？

**Comment by cocoatomo** [comment]
(https://pythonjp.slack.com/archives/C3QH8PTAS/p1507191806000103 より転載)

sphinx project rootに `docutils.conf` を置いて内容を以下のように書けばOK
```
[restructuredtext parser]
smart_quotes:no
```
see: http://docutils.sourceforge.net/docs/user/config.html#smart-quotes

**Comment by cocoatomo** [comment]
https://github.com/sphinx-doc/sphinx/pull/3875

https://pythonjp.slack.com/archives/C3QH8PTAS/p1507265612000072

**Comment by shimizukawa** [comment]
@methane はい。docutils.confを書き換える（なければ新規に作る）必要があります。

とりあえず、sphinx-1.6.3でSphinx側で直してあるので、sphinx-1.6.3以降にバージョンあげれば、docutils.confには手を付けなくて大丈夫。

**Comment by JulienPalard** [comment]
Fixed by upgrading sphinx to the latest version.

**Comment by cocoatomo** [comment]
@JulienPalard Thanks for your fix.

ref. https://github.com/python/docsbuild-scripts/pull/33
