### ISSUE TITLE
Sphinx のアップグレード (1.4.9 → 1.6.4)

### ISSUE THREAD

**Issue by cocoatomo** [python-doc-ja/python-doc-ja#773]
(作業記録のための issue です。)

#772 の問題を解決するために Sphinx のバージョンを 1.4.9 から 1.6.4 に変更する。

その際、ビルド結果がどのような影響を受けるかを差分を取って確認する。

**Comment by cocoatomo** [comment]
Sphinx 1.4.9 と 1.6.4 をそれぞれインストールした仮想環境を作り、そこで現時点のドキュメントと飜訳でビルド。それらの diff を取って、変化した部分を確認。

python-doc-ja/cpython-doc-intl intl-3.6 ブランチ: 87caf1ccad1457387bec57579fc742af3f2b703b
python-doc-ja/py36-locale master ブランチ: bab830c675f74748be229d36fafa6a900855786b

**Comment by cocoatomo** [comment]
@methane Sphinx 1.4.9 と Sphinx 1.6.4 でビルドした HTML どうしの差分をいくつかピックアップして, 原因を調べました.
#774 の smart quotes 以外は問題無いと判断して, Sphinx 1.6.4 に上げようと思います.

そこで, 差分への対処が問題無いかレビューしてもらえると助かります.

**Comment by methane** [comment]
本家の方も 1.6.4 すでに使ってるのでやっちゃってください。

**Comment by cocoatomo** [comment]
Python 2.7, 3.6 の両方のドキュメントで Sphinx のバージョンを 1.6.4 にアップグレード完了。
