### ISSUE TITLE
引用符から鉤括弧への変換に不具合がある

### ISSUE THREAD

**Issue by cocoatomo** [python-doc-ja/python-doc-ja#774]
ref. https://github.com/sphinx-doc/sphinx/issues/4142

HTML へのビルドを行うと、この訳文 (https://github.com/python-doc-ja/py36-locale/blob/master/ja/LC_MESSAGES/bugs.po#L122) に含まれる `"Title"` が `」Title」` に変換されるという不具合がある。
#771 のと類似の事象だが、こちらは段落の文字列なので Sphinx 1.6.4 でも smart quotes による変換対象となってしまう。

**Comment by cocoatomo** [comment]
日本語で smart quotes を使うのは問題があるので、この機能を無効にすることで対応するつもりでいる。

具体的には、Sphinx プロジェクトのルートディレクトリに次の内容を含む `docutils.conf` ファイルを設置する。

```
[restructuredtext parser]
smart_quotes:no
```

ref. http://docutils.sourceforge.net/docs/user/config.html#smart-quotes

**Comment by cocoatomo** [comment]
@methane 対応方法について問題無いか確認してもらえますか?

**Comment by methane** [comment]
これ、同じディレクトリで複数言語をビルドしている場合に、日本語だけで smart_quotes:no する方法はありますか？

**Comment by cocoatomo** [comment]
方法が1つ見付かりました。

`docutils.conf` に書けるオプションとして `smartquotes_locales` があり、ここには引用符の置き換えに使う文字列が言語ごとに指摘できます。

`docutils.conf` に以下の内容を記述して、日本語で引用符の置き換えに使う文字を `""''` (二重引用符、二重引用符、単引用符、単引用符) に設定すれば、実質的に変換しない動作が実現できます。

```
[restructuredtext parser]
smartquotes_locales: ja: ""''
```

これは括弧についてだけの設定なので、 `---`, `--`, `...` には smart quotes による変換がかかります。
(`smart_quotes:no` とするよりもこちらの方が良いと思います。)

## 実験結果

repository URL: https://github.com/python-doc-ja/cpython-doc-intl.git
commit hash: 87caf1ccad1457387bec57579fc742af3f2b703b
OS: macOS 10.13
Python ver.: 3.6.3
Sphinx ver.: 1.6.4
docutils ver.: 0.14
.po ファイルは日本語のみ用意。


### 日本語、smart quotes 有効、docutils.conf 無し
ビルドコマンド: `sphinx-build -j4 -D language=ja -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . ./_build/html`

#### 画面キャプチャ
![screen shot 2017-10-15 at 15 35 29](https://user-images.githubusercontent.com/223050/31582461-8c90d9dc-b1be-11e7-8ae3-29e8cc0f2295.png)

### フランス語、smart quotes 有効、docutils.conf 無し
ビルドコマンド: `sphinx-build -j4 -D language=fr -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . ./_build/html-fr`

#### 画面キャプチャ
![screen shot 2017-10-15 at 15 39 28](https://user-images.githubusercontent.com/223050/31582479-187a20ca-b1bf-11e7-8060-b598f56ecf58.png)

### 日本語、smart quotes 有効、docutils.conf 有
ビルドコマンド: `sphinx-build -j4 -D language=ja -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . ./_build/html-conf`

#### 画面キャプチャ
![screen shot 2017-10-15 at 15 41 47](https://user-images.githubusercontent.com/223050/31582489-6b4555b8-b1bf-11e7-83da-e4d76193b630.png)

### フランス語、smart quotes 有効、docutils.conf 有
ビルドコマンド: `sphinx-build -j4 -D language=fr -D locale_dirs=locale -D gettext_compact=0 -A versionswitcher=1 -E -d build/doctrees . ./_build/html-fr-conf`

#### 画面キャプチャ
![screen shot 2017-10-15 at 15 42 45](https://user-images.githubusercontent.com/223050/31582495-87f55690-b1bf-11e7-93e2-b2aa4d6934a1.png)

**Comment by JulienPalard** [comment]
Opened a PR on cpython after a full test build: https://github.com/python/cpython/pull/4006

**Comment by cocoatomo** [comment]
問題が全て解決したのでクローズ
