### ISSUE TITLE
TYPO: Module-3 -> Modula-3

### ISSUE THREAD

**Issue by shimarisu** [python-doc-ja/python-doc-ja#776]
Python チュートリアル 9.クラス
においてスペルミスがありました。
https://docs.python.jp/3/tutorial/classes.html

**Module-3** にあるような、オブジェクトのメンバをメソッドから参照するための短縮した記法は使えません: メソッド関数の宣言では、オブジェクト自体を表す第一引数を明示しなければなりません。

ご確認お願いいたします。

**Comment by cocoatomo** [comment]
報告ありがとうございます.

該当箇所を修正しておきました.
12/7 中には修正が反映される予定です.
