### ISSUE TITLE
gettext.translation の翻訳が間違っている

### ISSUE THREAD

**Issue by tk0miya** [python-doc-ja/python-doc-ja#778]
`gettext.translation` の翻訳が本文と真逆になっているように思えます。
https://docs.python.org/3.6/library/gettext.html#gettext.translation

原文では

>If multiple files are found, later files are used as fallbacks for earlier ones.

となっている箇所が、翻訳では

>複数のファイルが発見された場合、後で見つかったファイルは前に見つかったファイルの代替でと見なされ、後で見つかった方が利用されます。

となっています。

原文ではあとで見つかったファイルは「フォールバック」として用いられるとあるので、先に見つけたファイル(gettext のメッセージカタログ)に訳文が見当たらない場合に、あとで見つかったファイルを使うように読めます。

また、続く文章はコードと照らし合わせて読んでみると、設定方法ではなく単に実装を説明しているようです。ですので、ここは

>代替の設定を可能にするには、 copy.copy() を使ってキャッシュから翻訳オブジェクトを複製します

から

>代替の設定のために、 copy.copy() を使ってキャッシュから翻訳オブジェクトを複製します。

に変更するのはどうでしょうか。

※ 「 `gettext` モジュールは」「`translation()` 関数は」のように主語を補ったほうが読みやすいかも、と思いました。

**Comment by cocoatomo** [comment]
報告ありがとうございました.

以下の訳について誤解の無いように訳し直しました.

* "fallback"
* "To allow setting the fallback"

正午過ぎに .po ファイルを管理するレポジトリが更新されますので,
できればそちらで確認をお願いします.
(docs.python.org の更新は数日かかってしまうようです.)

https://github.com/python/python-docs-ja/blob/3.6/library/gettext.po#L245

> ※ 「 gettext モジュールは」「translation() 関数は」のように主語を補ったほうが読みやすいかも、と思いました。

これについては他の箇所とも雰囲気を合わせたいので, いったん保留しています.
新しい訳文を読んでみて主語を補った方が読みやすいと感じた場合は, この issue に続けてコメントしてください.

**Comment by cocoatomo** [comment]
.po ファイルが更新されました。
ご参照ください。

https://github.com/python/python-docs-ja/blob/893807f72227eb0c06baad18177e51d138b2d8d3/library/gettext.po#L245

**Comment by tk0miya** [comment]
ありがとうございます。理解しやすくなりました！
