### ISSUE TITLE
threading.Condition の誤訳

### ISSUE THREAD

**Issue by msakai** [python-doc-ja/python-doc-ja#782]
https://docs.python.org/3.6/library/threading.html#threading.Condition
> If the lock argument is given and not None, it must be a Lock or RLock object

https://docs.python.jp/3/library/threading.html#threading.Condition
> lock を指定して、 None の値にする場合、 Lock または RLock オブジェクトでなければなりません。

「None ではない値にする場合」だと思います。

**Comment by cocoatomo** [comment]
報告ありがとうございます.

```
*lock* に ``None`` でない値を指定した場合
```

という訳に修正しておきました. (reST マークアップはそのまま)

およそ1日後, threading.po ファイルの [このあたり](https://github.com/python/python-docs-ja/blob/3.6/library/threading.po#L938) に修正が反映される予定です.
