### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by k-tahiro** [python-doc-ja/python-doc-ja#784]
https://docs.python.jp/3/library/re.html?highlight=re#re.regex.match
s/パタンー/パターン/

2.7と3.5でも同様の表現になっています。
https://docs.python.jp/2.7/library/re.html?highlight=re#re.RegexObject.match
https://docs.python.jp/3.5/library/re.html?highlight=re#re.regex.match

ご確認よろしくお願いします。

**Comment by cocoatomo** [comment]
報告ありがとうございます.

翻訳を修正したので, 数日後には反映されているはずです.
翻訳カタログで確認する場合は次のあたりを見てください.

2.7 https://github.com/python/python-docs-ja/blob/2.7/library/re.po#L1077
3.6 https://github.com/python/python-docs-ja/blob/3.6/library/re.po#L1501

issue は閉じますが, 修正に不備があれば再度開いてください.
