### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by inabajunmr** [python-doc-ja/python-doc-ja#785]
https://docs.python.jp/3/tutorial/appetite.html
「シェルスクリプトやバッチファイルよりも多くの機構がり」→「機構があり」

**Comment by atsuoishimoto** [comment]
ありがとうございます。修正しました。

**Comment by cocoatomo** [comment]
修正されているのを確認しました。
https://github.com/python/python-docs-ja/commit/a30a8f2c1f71f5fcb31528f9003e79ccf6bf9d54

報告と修正ありがとうございました。
