### ISSUE TITLE
datetime の書式の誤訳

### ISSUE THREAD

**Issue by mashabow** [python-doc-ja/python-doc-ja#786]
誤訳の報告はこちらでよいでしょうか？

https://docs.python.jp/3/library/datetime.html#strftime-and-strptime-behavior
> `%y` 0埋めした10進数で表記した世紀ありの年。

s/世紀あり/世紀なし/ のようです。

**Comment by cocoatomo** [comment]
報告ありがとうございました. 修正しておきました.
