### ISSUE TITLE
return の訳語

### ISSUE THREAD

**Issue by sueki743** [python-doc-ja/python-doc-ja#787]
https://docs.python.jp/3/reference/datamodel.html#emulating-numeric-types の__add__から__or__までの説明の文章に
> NotImplemented を送出しなければなりません。

とありますが、原文 https://docs.python.org/3.6/reference/datamodel.html#emulating-numeric-types を見ると
> it should return NotImplemented.

とあり、この訳としては
> NotImplemented を返さなければなりません。

が適切ではないでしょうか。（「送出しなければなりません」だと`raise NotImplemented`が必要だと見受けられるため）

**Comment by cocoatomo** [comment]
報告ありがとうございました。

>  NotImplemented を返すべきです。

に修正しました。
