### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by yagays** [python-doc-ja/python-doc-ja#789]
"alias"がtypoしてたので報告します🙏
「別名づけ(ailias) 」→「別名づけ(alias) 」

https://docs.python.org/ja/3/tutorial/classes.html#a-word-about-names-and-objects

**Comment by taketakeyyy** [comment]
ありがとうございます。修正しておきました。
次回ビルド時に直ると思います。

https://www.transifex.com/python-doc/python-36/translate/#ja/tutorial--classes/108422897

**Comment by cocoatomo** [comment]
修正が反映されているのを確認しました.
