### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by kanjirz50** [python-doc-ja/python-doc-ja#790]
[9.5.継承](https://docs.python.org/ja/3/tutorial/classes.html#inheritance)にtypoがあったため、報告します。

以下の太字の部分は誤字かと思われます。

> 派生クラスのインスタンス化では、特別なことは何もありません。 DerivedClassName() はクラスの新たなインスタンスを生成します。メソッドの参照は次のようにして**い**解決されます。

**Comment by cocoatomo** [comment]
報告ありがとうございます.

> 次のようにして**い**解決されます。

を

> 次のようにして解決されます。

に修正しました.
