### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by sammiya** [python-doc-ja/python-doc-ja#791]
[Python のローカルとグローバル変数のルールは何ですか？](https://docs.python.jp/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python) の次の強調箇所は typo かと思います.

> Python では、関数内で参照されるだけの変数は暗黙的にグローバル**に**です。

**Comment by cocoatomo** [comment]
報告ありがとうございます。

> Python では、関数の中からしか参照されていない変数は暗黙的にグローバルとされます。

と全体的に修正しておきました。
