### ISSUE TITLE
URL typo

### ISSUE THREAD

**Issue by kuri8ive** [python-doc-ja/python-doc-ja#793]
# 概要
URLにtypoが存在

# 問題のある箇所 (URLで指定すること)
https://github.com/python/python-docs-ja/blob/3.7/tutorial/index.po#L44

# 問題の詳細
httpsのはずがhttsになっている

# 修正案
`"Python Web サイト(htts://www.python.org) は、 Python "`
↓
`"Python Web サイト(https://www.python.org) は、 Python "`

**Comment by taketakeyyy** [comment]
こんにちは。ありがとうございます。
修正しておきました。

https://www.transifex.com/python-doc/python-newest/translate/#ja/tutorial--index/108423191
