### ISSUE TITLE
unittest.TestLoader.discover の誤訳

### ISSUE THREAD

**Issue by isofurabon** [python-doc-ja/python-doc-ja#794]
# 概要
原文を正しく翻訳できていない。

# 問題のある箇所
 https://docs.python.jp/3/library/unittest.html#unittest.TestLoader.discover
第二段落目

# 問題の詳細
翻訳
> 開始ディレクトリがトップレベルディレクトリでない場合は、トップレベルディレクトリが**分離できなくてはいけません。**

原文
> If the start directory is not the top level directory then the top level directory **must be specified separately.**

# 修正案
トップレベルディレクトリ**を個別に指定しなければなりません。**

**Comment by taketakeyyy** [comment]
こんにちは。ありがとうございます。

確かに、おっしゃる通りの訳にすべきと思いましたので、以下のように修正しました。

> すべてのテストモジュールはプロジェクトのトップレベルからインポート可能である必要があります。開始ディレクトリがトップレベルディレクトリでない場合は、トップレベルディレクトリを個別に指定しなければなりません。

https://www.transifex.com/python-doc/python-newest/translate/#ja/library--unittest/108418653?q=text%3Aspecified
