### ISSUE TITLE
Logging HOWTOの訳を修正

### ISSUE THREAD

**Issue by yuji38kwmt** [python-doc-ja/python-doc-ja#796]
# 概要

https://docs.python.org/ja/3/howto/logging.html#logging-to-a-file

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/howto/logging.html#logging-to-a-file

>If you want to set the logging level from a command-line option such as:

```
--log=INFO
```

# 問題の詳細
「If you want to set the logging level from a command-line option such as:」の和訳が次のようになっていました。

```
コマンドラインのオプションからログレベルを変更した場合、以下の様に入力してください:

--log=INFO
```

しかし、「ログレベルを変更した場合`--log=INFO`を入力する」のではなく、「`--log=INFO`のようなコマンドラインオプションでログレベルを変更する」ので、和訳が間違っています。

# 修正案
以下のような和訳が良いと思います。

>以下のように、コマンドラインのオプションからロギングレベルを変更した場合は、

# 質問
Transifexで以下のように修正しました。これで良いでしょうか？

https://www.transifex.com/python-doc/python-newest/translate/#ja/howto--logging/139144975?q=text%3A'If+you+want+to+set+the+logging+level+from+a+command-line+option+such+as'

**Comment by cocoatomo** [comment]
こちらはissueを報告する場ですので、なにが問題なのかを書いてください。
(特にそれについて書かずにTransifex上で修正をされたようなので、いったん前の訳文に戻してあります。)

**Comment by yuji38kwmt** [comment]
@cocoatomo 失礼いたしました。「問題の詳細」に「和訳が間違っている」旨を記述しました。

**Comment by yuji38kwmt** [comment]
3/12にリリースされた3.7.3rc1では、和訳が以下のようになっておりまして、問題ない訳でした。
>次のようなコマンドラインオプションでログレベルを設定したいと考え:

https://docs.python.org/ja/3.7/howto/logging.html#logging-to-a-file

したがって、このIssueはcloseにさせていただだきます。

**Comment by yuji38kwmt** [comment]
3/12にリリースされた3.7.3rc1では、和訳が以下のようになっておりまして、問題ない訳でした。

次のようなコマンドラインオプションでログレベルを設定したいと考え:

https://docs.python.org/ja/3.7/howto/logging.html#logging-to-a-file

したがって、このIssueはcloseにさせていただだきます。
