### ISSUE TITLE
core developers の訳が「中心開発者」「コア開発者」で揺れている

### ISSUE THREAD

**Issue by yoichi** [python-doc-ja/python-doc-ja#797]
# 概要

core developers の訳が「中心開発者」となっていて不自然

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/test.html

# 問題の詳細

ページ先頭の注釈の「ドキュメント化されているのは Python の中心開発者のためです。」で、
core developers の訳として「中心開発者」とされていますが、不自然な日本語と感じました。
同じく core developers の訳としては
https://docs.python.org/ja/3/library/pickletools.html
では「コア開発者」という訳が使われており、こちらのほうが自然と感じました。

# 修正案

中心開発者→コア開発者

**Comment by NicHON** [comment]
リンク先の翻訳部分を確認しました。
賛成です。

原文の「core developers」はPythonそのものを開発する人、ということですね。
Python開発者、というとPythonを利用して開発する人と区別つきません。また、ウェブ検索したところ、暗号資産を開発する人もコア開発者と記載されていました。
（ざっと調べた程度なので、URLを省略します）

以上から、賛成です。

一方で、他言語の開発者についてはなんと訳されているのか、調べてみようとも思います。
もし、良いのがあれば、それを案にあげるかもしれません。

**Comment by aiotter** [comment]
報告ありがとうございます。
core developersの表記が「中心開発者」「コアデベロッパー」「コア開発者」と表記ゆれがあったため、「コア開発者」に統一しました。
修正箇所は次の2ページです。
- https://docs.python.org/ja/3/library/test.html
- https://docs.python.org/ja/3/library/typing.html

**Comment by aiotter** [comment]
まだ表記ゆれがあったので追加で次のページの翻訳も更新しました。
- https://docs.python.org/ja/3.7/whatsnew/3.0.html
- https://docs.python.org/ja/3.7/whatsnew/3.3.html
