### ISSUE TITLE
collections.deque.rotate()のTypo

### ISSUE THREAD

**Issue by kerroggu** [python-doc-ja/python-doc-ja#798]
# 概要
collections.deque.rotate()の説明文中のTypo。

# 問題のある箇所 
https://docs.python.org/ja/3/library/collections.html#collections.deque

# 問題の詳細
"rotate(n=1)"の説明にTypoがあります。
"deque が空でないときは、 deque をひとつ右にローテートすることは d.appendleft(d.pop()) と同じで、 deque をひとつ左にローテートすることは d.appendleft(d.popleft()) と同じです。"

# 修正案
英語verと同様に"deque をひとつ左にローテートすることは d.append(d.popleft()) と同じです。"と修正することを提案します。

**Comment by cocoatomo** [comment]
報告ありがとうございます。
提案の通り修正しました。

**Comment by kerroggu** [comment]
修正ありがとうございました！


2019年5月11日(土) 10:02 cocoatomo <notifications@github.com>:
