### ISSUE TITLE
README.md のリンク先が docs.python.jp になっている

### ISSUE THREAD

**Issue by miau** [python-doc-ja/python-doc-ja#799]
docs.python.org の日本語の問題をどこに報告すべきか迷ってしまったので、 [日本語訳 Pythonドキュメントを移転しました - python.jp](https://www.python.jp/news/20190227_docs_moved.html) に相当する案内が README.md にもあると良いと思いました。

**Comment by cocoatomo** [comment]
報告ありがとうございます!

リンク先については修正しました。

報告先の情報ですが、ここにある [問題報告](https://github.com/python-doc-ja/python-doc-ja/blob/master/README.md#%E5%95%8F%E9%A1%8C%E5%A0%B1%E5%91%8A) という記載では不足でしょうか?

**Comment by miau** [comment]
ご対応ありがとうございます。

> 報告先の情報ですが、README.mdにある [問題報告](https://github.com/python-doc-ja/python-doc-ja/blob/master/README.md#%E5%95%8F%E9%A1%8C%E5%A0%B1%E5%91%8A) という記載では不足でしょうか?

説明不足ですみません。経緯としては

1. https://docs.python.org/ja/ に翻訳に関わる問題を見付ける
2. ページ右下の [バグを見つけたら?](https://docs.python.org/ja/3/bugs.html) を見るが、翻訳に関する報告の情報はない
3.  「python ドキュメント 日本語」でググるとこの github ページに辿り付いたが、ドキュメントの URL が docs.python.jp となっており、公式ドキュメントと別プロジェクトなのかも？と勘違いする
4. 移転の情報を見付け、ここで報告する形で問題がないことを知る

という流れでした。今回リンク先を修正いただいたので、今後同じ状況になった方も 3. で迷うことなく報告できると思います。
