### ISSUE TITLE
sys.float_info.min の説明が正しくない

### ISSUE THREAD

**Issue by miau** [python-doc-ja/python-doc-ja#800]
# 概要

sys.float_info.min の説明が正しくない

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/sys.html#sys.float_info

# 問題の詳細

`min` の説明は「float が表現可能な最小の正の値」となっていますが、 非正規化数で `sys.float_info.min` よりも小さい値を表現できるため、正しくありません。

[Pythonの浮動小数点数float型の範囲（最大値・最小値） | note.nkmk.me](https://note.nkmk.me/python-sys-float-info-max-min/) で例示されていました。

[英語版](https://docs.python.org/3/library/sys.html#sys.float_info) も「minimum positive normalized float」となっていますので、これに従うのが良いかと思います。

# 修正案

そのまま訳すと「最小の正の正規化float」ですが、なんとなく「正の正規化floatの最小値」のほうが自然な気もします。

**Comment by cocoatomo** [comment]
報告ありがとうございます。
「正規化 float の最小の正の値」に修正しておきました。
