### ISSUE TITLE
asyncio.wait_forの翻訳の修正提案

### ISSUE THREAD

**Issue by aiotter** [python-doc-ja/python-doc-ja#801]
# 概要
asyncio.wait_forの翻訳が誤解を生むように思うので修正を提案します

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/asyncio-task.html#asyncio.wait_for

# 問題の詳細
`Wait for the aw awaitable to complete with a timeout.`を`aw awaitable が、タイムアウトで完了するのを待ちます。`と翻訳されていますが、このwithはcompleteではなくwaitにかかり、「awが完了するのをタイムアウト付きで待つ」という意味だと思います。

# 修正案
`aw awaitable が、完了するかタイムアウトになるのを待ちます。`

**Comment by cocoatomo** [comment]
https://github.com/python/cpython/blob/master/Lib/asyncio/tasks.py
その通りでした。このコメントにはっきり書かれていました。

Transifexで訳文の修正をお願いします。

**Comment by cocoatomo** [comment]
https://github.com/python/cpython/blob/65aa64fae89a24491aae84ba0329eb8f3c68c389/Lib/asyncio/tasks.py
その通りでした。このコメントにはっきり書かれていました。

Transifexで訳文の修正をお願いします。

**Comment by aiotter** [comment]
了解しました。訳文を差し替えておきます。

**Comment by aiotter** [comment]
修正しました。
