### ISSUE TITLE
コンテキスト、コンテキストマネージャの表記ゆれ

### ISSUE THREAD

**Issue by tk0miya** [python-doc-ja/python-doc-ja#802]
# 概要

context および contextmanager の表記ゆれを見つけました。

* コンテキスト
* コンテクスト
* コンテキストマネージャ
* コンテクストマネージャ
* コンテクスト管理者

# 問題のある箇所 (URLで指定すること)

>返されたオブジェクトは、コンテクスト管理者として使用することができます (with文とコンテキストマネージャ を参照)。

https://docs.python.org/ja/3/library/tempfile.html#tempfile.TemporaryDirectory

>3.3.9. with文とコンテキストマネージャ
>3.4.4. 非同期コンテクストマネージャ (Asynchronous Context Manager)

https://docs.python.org/ja/3/reference/datamodel.html#context-managers

# 問題の詳細

同上

# 修正案

いずれかの表記に統一するのがよいと思います。
私見ですがコンテキストの方が日本語表記では一般的と考えます。

Google での検索結果
* [コンテキスト](https://www.google.com/search?q=%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9%E3%83%88&oq=%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AD%E3%82%B9&aqs=chrome.1.69i57j0j69i61j0l3.3008j0j4&sourceid=chrome&ie=UTF-8): 約 5,690,000 件
* [コンテクスト](https://www.google.com/search?q=%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AF%E3%82%B9%E3%83%88&oq=%E3%82%B3%E3%83%B3%E3%83%86%E3%82%AF%E3%82%B9%E3%83%88&aqs=chrome..69i57j0l5.6293j0j4&sourceid=chrome&ie=UTF-8): 約 1,480,000 件

**Comment by cocoatomo** [comment]
1. 訳文に「コンテクスト」が含まれる
2. 訳文に「スト管理者」が含まれる
3. 原文に "context" が含まれ、訳文に「コンテク」が含まれる

という条件で絞って検索し、全て「コンテキスト」に寄せました。

Transfex project の glossary にも「コンテキスト」を訳語とするよう明記しました。

**Comment by tk0miya** [comment]
ありがとうございます!!
