### ISSUE TITLE
ver3.5のsocketに脱字/表記ゆれ

### ISSUE THREAD

**Issue by Krout0n** [python-doc-ja/python-doc-ja#804]
# 概要
18.1. socket — 低水準`ネットワークインターフェー`と脱字をしている。タイトルも同様。また、他のバージョン(3.6.9など)では`ネットワークインターフェイス`となっていて表記ゆれがある。
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3.5/library/socket.html
# 問題の詳細
同上
# 修正案
3.5のを `ネットワークインターフェイス`に修正する。

**Comment by cocoatomo** [comment]
申し訳ありませんが、人手の都合上 ver3.5 についてはメンテナンスを打ち切っていますので、修正は行いません。

ver3.6, ver3.7については修正します。

**Comment by cocoatomo** [comment]
Google 検索の結果
- インターフェース: 約 35,200,000 件
- インターフェイス: 約 24,200,000 件

より、「ネットワークインターフェース」にする

**Comment by cocoatomo** [comment]
遅くなりましたが、 ver 3.6, 3.7, 3.8, 3.9 について、"network interface" を「ネットワークインターフェース」に統一しました。
