### ISSUE TITLE
Inaccurate explanation of ArgumentParser.add_argument()'s name-or-flags

### ISSUE THREAD

**Issue by tsekine354** [python-doc-ja/python-doc-ja#805]
# 概要
argparse library の `add_argument()` における説明の、２番めの文が不正確。

https://bugs.python.org/issue37761 で登録したけどrepoが違うとcloseされたので、それと同じ内容です。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/argparse.html#name-or-flags
の２番目の文「そのため、add_argument() の第1引数は、フラグのリストか、シンプルな引数名のどちらかになります」

# 問題の詳細
原文は

> The first arguments passed to add_argument() must therefore be either a series of flags, or a simple argument name.

であり、

- first argument**s** となってて、第一引数ではなく、最初の方の（キーワード付きでない）引数（複数可）
- とれる値は a series of flags であって、フラグのリストではない

直訳すれば「add_argument()に渡される最初の引数群は、一連のフラグか、さもなければ単純な引数名でなければなりません」となります。

# 修正案
ちょっと分りやすく「翻訳」する方法が思いつきません。原文を無視して「位置引数」とか「キーワード引数より前」とかの説明を追加しないと無理そうな気がします。

**Comment by cocoatomo** [comment]
報告ありがとうございます。

> そのため、 :meth:`~ArgumentParser.add_argument` に初めに渡される引数は、一連のフラグか、単一の引数名のどちらかになります。

と、修正しました。
この文章はレファレンスなので、位置引数やキーワード引数の説明についてはそれ用の場所で行うべきとし、ここでは追加しないことにしました。
