### ISSUE TITLE
cooperative schedulingが強調スケジューリングと訳されている

### ISSUE THREAD

**Issue by kanaihiroki** [python-doc-ja/python-doc-ja#806]
# 概要

cooperative schedulingが強調スケジューリングと訳されています。
正しくは協調スケジューリングだと思います。

# 問題のある箇所 (URLで指定すること)

* 日本語訳

https://docs.python.org/ja/3/library/asyncio-task.html#asyncio.Task
> イベントループは強調スケジューリングを使用します。つまり、イベントループは同時に 1 つの Task のみ実行します。 Task が Future の完了を待っているときは、イベントループは他の Task やコールバックを動作させるか、 IO 処理を実行します。

* 英語原文

https://docs.python.org/3/library/asyncio-task.html#asyncio.Task
> Event loops use cooperative scheduling: an event loop runs one Task at a time. While a Task awaits for the completion of a Future, the event loop runs other Tasks, callbacks, or performs IO operations.

# 問題の詳細

上記の通りです。

# 修正案

概要に記載のとおりです。

**Comment by osamu0329nakamura** [comment]
修正しました。
