### ISSUE TITLE
”object"が”属性”と訳されている

### ISSUE THREAD

**Issue by SeishiSano** [python-doc-ja/python-doc-ja#807]
# 概要
objectが属性と訳されている
# 問題のある箇所 (URLで指定すること)
日本語訳
https://docs.python.org/ja/3/reference/datamodel.html
”3.1. オブジェクト、値、および型”の第2パラグラフ先頭

英語原文
https://docs.python.org/3/reference/datamodel.html
”3.1. Objects, values and types”の第2パラグラフ先頭

# 問題の詳細
Every object→すべての属性は
と訳されており意味が通じない
# 修正案
”すべての属性は”→”すべてのobjectは”

**Comment by osamu0329nakamura** [comment]
報告ありがとうございます。修正案の object は「オブジェクト」に変更して指摘箇所を ``すべてのオブジェクトは`` に修正しました。
