### ISSUE TITLE
bytearray.strip などにおける「ASCII の空白文字」について

### ISSUE THREAD

**Issue by msakai** [python-doc-ja/python-doc-ja#808]
# 概要

「ASCII の空白文字（訳注: 半角スペース）」とあるが、実際には半角スペース以外の空白文字も含まれる。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/stdtypes.html?#bytearray.strip
https://docs.python.org/ja/3/library/stdtypes.html?#bytearray.rstrip
https://docs.python.org/ja/3/library/stdtypes.html?#bytearray.lstrip

> chars が省略されるか None の場合、 ASCII の空白文字（訳注: 半角スペース）が除去されます。

原文:
> If omitted or None, the chars argument defaults to removing ASCII whitespace.

# 問題の詳細

ここでの「ASCII の空白文字」は半角スペースのみでなく、`isspace()` が真になるASCIIの他の文字も含まれるようです。

https://docs.python.org/ja/3/library/stdtypes.html?#bytearray.isspace では
> ここでの ASCII 空白文字とはシーケンス b' \t\n\r\x0b\f' に含まれるバイト値です (半角スペース、タブ、ラインフィード、キャリッジリターン、垂直タブ、フォームフィード) 。

と書かれており、ここで定義された「ASCII の空白文字」について言及していると考えるべきだと思います。

# 修正案

「（訳注: 半角スペース）」を削除

原文も ASCII whitespace characters などと修正したほうが親切な気がします。

**Comment by osamu0329nakamura** [comment]
「（訳注: 半角スペース)」を削除し、同ドキュメント内の「ASCIIの空白文字」を「ASCII 空白文字」に統一しました。
一方で、「ASCII 空白文字」だとSPC 0x20と誤認されそうなので、翻訳メンバの方々、他によい案があったら提案をお願いします。
しばらくしてコメントなければ Close します。

**Comment by cocoatomo** [comment]
丁寧に対応するなら訳注を「(訳注: 空白文字の定義については :meth:`bytearray.isspace` を参照。)」という文言に差し替えるのでもいいかもしれません。
他により直接的に「空白文字」の定義が書かれている箇所があれば、そこへのリンクで置き換えるのもありです。

これで決定ではないので、率直な感想をください。

**Comment by cocoatomo** [comment]
ver 3.7 は osamu0329nakamura さん、ver 3.6, 3.8 は私の案で修正しておきました。
問題があればreopenしてください。
