### ISSUE TITLE
「unittest.mock --- モックオブジェクトライブラリ」のフォーマットが崩れている箇所がある

### ISSUE THREAD

**Issue by arosh** [python-doc-ja/python-doc-ja#811]
# 概要

「unittest.mock --- モックオブジェクトライブラリ」のフォーマットが崩れている箇所がある

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/unittest.mock.html#autospeccing

# 問題の詳細

「```None``を spec にすることが有用な場面は *決して* なく、おそらくそのメンバーは他の何かの型のメンバーになることを示すので、 autospec は ``None に設定されているメンバーには spec を使いません。```」の部分のフォーマットが（おそらく）意図した通りになっていない。

# 修正案

「``` `None` を spec にすることが有用な場面は *決して* なく、おそらくそのメンバーは他の何かの型のメンバーになることを示すので、 autospec は `None` に設定されているメンバーには spec を使いません。```」など、Sphinx の記法に添うように修正する

**Comment by cocoatomo** [comment]
ご指摘ありがとうございました。
ドキュメントが更新され、正しいマークアップがなされていることを確認したらクローズします。

**Comment by cocoatomo** [comment]
このスクリーンショットの通り、マークアップが修正されたのでクローズします。

![Screen Shot 2019-12-01 at 23 38 07](https://user-images.githubusercontent.com/223050/69915568-d7b60600-1493-11ea-9267-36f50c398610.png)

**Comment by arosh** [comment]
ありがとうございました！
