### ISSUE TITLE
「最上位ビット」が「最も重大なビット」と訳されている

### ISSUE THREAD

**Issue by ernix** [python-doc-ja/python-doc-ja#812]
# 概要

`the most significant bit (MSB)` が `最上位ビット` ではなく `最も重大なビット` と訳されています。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/tutorial/floatingpoint.html

# 問題の詳細

> On most machines today, floats are approximated using a binary fraction with the numerator using the first 53 bits starting with the most significant bit and with the denominator as a power of two.

> 近年の殆どのコンピュータでは float 型は、分子に最も重大なビットから始めて最初の 53 ビットを使い、分母に 2 の累乗を使った、二進小数を使って近似されます。

# 修正案

> 近年の殆どのコンピュータでは float 型は、最上位ビットから数えて 53 ビットを分子、2 の累乗を分母とする二進小数で近似されます。

**Comment by cocoatomo** [comment]
ご指摘ありがとうございました。

訳語の修正を完了したのでクローズします。
