### ISSUE TITLE
contextvars.Context が「ContextVars とその値の写像」と説明されている部分の翻訳の修正提案

### ISSUE THREAD

**Issue by aiotter** [python-doc-ja/python-doc-ja#814]
# 概要
> A mapping of ContextVars to their values.
> ContextVars とその値の写像。

上記の翻訳ですが、「ContextVars とその値のマッピング」というのがより良い訳かと思います。
contextvars.Context がContextVarsとそれに対応している値の写像であるのはその通りですが、現在の訳では Context がマッピング型として扱えることが分からないのと、数学的なのですべての人に馴染みがある表現ではないように思います。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/contextvars.html#contextvars.Context
# 修正案
`ContextVars とその値の写像。` -> `ContextVars とその値のマッピング。`

**Comment by cocoatomo** [comment]
> 数学的なのですべての人に馴染みがある表現ではない

これはその通りですね。表現を修正します。

> Context がマッピング型として扱えることが分からない

ただし、これについては

> Context implements the collections.abc.Mapping interface.

という文があって、ここで十分に解説できています。
同じ意味の解説を2箇所でやる必要は無いので、先頭にある文の "mapping" は「対応付け」という意味の一般的な言葉として使われていると判断しました。
技術的な解説では、実装よりも先に設計の話をする方が自然なことからもそう判断しています。

@aiotter さんが、どういうふうな判断で「"mapping" の意味は『マッピング型』」と考えたのかを教えてもらえないでしょうか?

**Comment by aiotter** [comment]
"A mapping of ContextVars to their values." の mapping がマッピング**型**の意味であるとは私も考えていません。
「ContextVars とその値の写像」の意味が分からなかったため原文を当たったところ mapping と書かれていて、Mapping 型のような対応付けのことを指しているとそのまま理解できたたため、カタカナのままとしました。
「対応付け」という意味の一般的な言葉として使われているということに同意します。

> Context implements the collections.abc.Mapping interface.
> という文があって、ここで十分に解説できています。

これについては、cocoamotoさんの仰るとおりです。

**Comment by cocoatomo** [comment]
では、「写像」→「対応付け」という修正をします。

Pythonドキュメントでの話ですが、専門用語の翻訳は英単語の読みをそのままカタカナにしていることが多いので、それと混同させないように一般的な言葉は日本語の平易な表現で訳すことにしています。
