### ISSUE TITLE
名詞の format の訳語の揺れ

### ISSUE THREAD

**Issue by cocoatomo** [python-doc-ja/python-doc-ja#815]
# 概要

訳語の揺れ

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3.8/library/datetime.html 全体

# 問題の詳細

"format" の訳が「書式」「書式化」「形式」と揺れている

# 修正案

「書式」か「形式」に統一する

**Comment by methane** [comment]
format は名詞と動詞があるので「書式（文字列）」と「（datetimeの）書式化」があるのは大丈夫だと思います。

**Comment by cocoatomo** [comment]
これは名詞に限った話のつもりでした。
動詞の方は対象としないので、タイトルを修正しておきます。

**Comment by cocoatomo** [comment]
このページでは、文字列の *format* としてこの単語が使われているので訳語を「書式」に統一する。

「書式」と「形式」の訳し分けの方針としては、文字列については「書式」、「定められた構造」の意味合いが強い場合は「形式」を訳語として使うこととする。

**Comment by cocoatomo** [comment]
既存の翻訳の修正完了
issueをクローズします
