### ISSUE TITLE
typo: ネットワーク大域→ネットワーク帯域

### ISSUE THREAD

**Issue by yoichi** [python-doc-ja/python-doc-ja#816]
# 概要

typo: ネットワーク大域→ネットワーク帯域

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/howto/unicode.html

# 問題の詳細

typo: ネットワーク大域
原文(https://docs.python.org/3/howto/unicode.html)では network bandwidth です

# 修正案

ネットワーク帯域

**Comment by ymyzk** [comment]
ご指摘ありがとうございます．現時点で更新が可能な Python 3.6 のドキュメントまで遡って修正しました．次回のビルドで修正が反映される予定です．

**Comment by ymyzk** [comment]
現時点で更新が反映されましたので issue を close します．
