### ISSUE TITLE
グローバル変数の説明の誤訳

### ISSUE THREAD

**Issue by nkmk** [python-doc-ja/python-doc-ja#817]
# 概要

FAQのグローバル変数の説明の訳が誤っている。

# 問題のある箇所 (URLで指定すること)

> Python では、関数の中からしか参照されていない変数は暗黙的にグローバルとされます。
- https://docs.python.org/ja/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python

# 問題の詳細

原文の「only」は「inside a function」ではなく「referenced」にかかっているので、`3.6`までの訳のほうが適切かと思います。

> In Python, variables that are only referenced inside a function are implicitly global.
- https://docs.python.org/3/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python

> Python では、関数内で参照されるだけの変数は暗黙的にグローバルにです。
- https://docs.python.org/ja/3.6/faq/programming.html#what-are-the-rules-for-local-and-global-variables-in-python

# 修正案

```
修正前） Python では、関数の中からしか参照されていない変数は暗黙的にグローバルとされます。
修正後） Python では、関数内で参照されるだけの変数は暗黙的にグローバルです。
※ 3.6のtypoを修正（グローバルにです => グローバルです）
```

**Comment by cocoatomo** [comment]
報告ありがとうございました!
訳文を修正しました。
