### ISSUE TITLE
「バグへの対処」のページに当Issue Trackerへのリンクを追加

### ISSUE THREAD

**Issue by nkmk** [python-doc-ja/python-doc-ja#818]
# 概要

「このドキュメントについて」のページに加えて、「バグへの対処」のページにも日本語訳の問題についての報告先（当Issue Tracker）へのリンクがあると親切だと思います。

# 問題のある箇所 (URLで指定すること)

- https://docs.python.org/ja/3/bugs.html

# 問題の詳細

「このドキュメントについて」のページに当Issue Trackerへのリンクが記載されています。

> （訳注: 日本語訳の問題については、 GitHub 上の Issue Tracker で報告をお願いします。）
- https://docs.python.org/ja/3/about.html

一方、各ページのサイドバーの`バグ報告`から飛べる「バグへの対処」のページにはありません。

- https://docs.python.org/ja/3/bugs.html

# 修正案

サイドバーの`バグ報告`は目に付きやすいので、日本語訳の問題を報告しようとする人の多くは「バグへの対処」のページを見るのではないかと思います。

「バグへの対処」の「ドキュメントの不備」の項にも「このドキュメントについて」と同様の文章を追加してはいかがでしょうか。

```
（訳注: 日本語訳の問題については、 GitHub 上の Issue Tracker で報告をお願いします。）
```
- https://docs.python.org/ja/3/bugs.html#documentation-bugs

**Comment by cocoatomo** [comment]
提案ありがとうございます!
いただいた提案の通り訳注を追加しておきました。(数日くらいでドキュメントに反映されると思います。)
