### ISSUE TITLE
`logging.Formatter.formatTime`メソッドの`datefmt`引数が指定されなかったときのデフォルト値が間違っている

### ISSUE THREAD

**Issue by yuji38kwmt** [python-doc-ja/python-doc-ja#819]
# 概要
`logging.Formatter.formatTime`メソッドの`datefmt`引数が指定されなかったときのデフォルト値が、間違っていると思います。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/logging.html#logging.Formatter.formatTime

# 問題の詳細

>そうでない場合、 '%Y-%m- %H:%M:%S,uuu' というフォーマットが使われます。 
`%Y-%m-`ではなく`%Y-%m-%d`だと思います。

英語サイトは以下のように記載されていました。
>Otherwise, the format ‘%Y-%m-%d %H:%M:%S,uuu’ is used, where the uuu part is a millisecond value and the other letters are as per the time.strftime() documentation. 

https://docs.python.org//3/library/logging.html#logging.Formatter.formatTime

# 修正案

```
そうでない場合、 '%Y-%m-%d %H:%M:%S,uuu' というフォーマット
```

**Comment by cocoatomo** [comment]
報告ありがとうございました!
修正しました。
