### ISSUE TITLE
timedelta の演算の表の除算の説明のtypo

### ISSUE THREAD

**Issue by msakai** [python-doc-ja/python-doc-ja#820]
# 概要

`datetime.timedelta` の演算の表の除算の説明のtypo。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/datetime.html#timedelta-objects の「サポートされている演算を以下に示します」という表の「f = t2 / t3」の説明

# 問題の詳細

> t2 を 3 で除算 (3) したもの。float オブジェクトを返します。

とありますが、「3 で除算」は「t3 で除算」だと思います。

なお、原文は

> Division (3) of overall duration t2 by interval unit t3. Returns a float object.

です。

# 修正案

「3 で除算」 → 「t3 で除算」

**Comment by takuan-osho** [comment]
FYI: @msakai さんの指摘の通り、原文と訳文を見て、typoであろうと確認できたので、transifex上で修正しました。その内反映されると思います。

**Comment by msakai** [comment]
反映されているのを確認しました。
