### ISSUE TITLE
typo: オプジェクト->オブジェクト

### ISSUE THREAD

**Issue by tsuka** [python-doc-ja/python-doc-ja#823]
# 概要
typo: オプジェクト->オブジェクト

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/asyncio-task.html

# 問題の詳細
https://github.com/python/python-docs-ja/compare/3.8...tsuka:fix-typo

# 修正案
https://github.com/python/python-docs-ja/compare/3.8...tsuka:fix-typo

**Comment by cocoatomo** [comment]
報告ありがとうございます。
訳文を修正しました。

P.S.
diffのURLを使うの分かりやすくていいですね。
