### ISSUE TITLE
typo: 強調->協調

### ISSUE THREAD

**Issue by orisano** [python-doc-ja/python-doc-ja#824]
# 概要
typo: 強調->協調
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3.8/library/asyncio-task.html
# 問題の詳細
cooperative schedulingの訳が強調スケジューリングになっているので協調の誤変換だと思われる.
# 修正案
強調から協調に修正する

**Comment by cocoatomo** [comment]
報告ありがとうございます。
訳文を修正しました。
