### ISSUE TITLE
日本語版argparseのactionの誤表記

### ISSUE THREAD

**Issue by colun** [python-doc-ja/python-doc-ja#825]
# 概要

翻訳時の表記ミス。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/argparse.html

# 問題の詳細

argparseのactionの説明において、

英語版では: ..., 'append', ..., 'extend'
日本語版では: ..., 'append', ..., 'append'

という具合で、本来なら'extend'とされているべき箇所が'append'になっている。

# 修正案

英語版で'extend'となっている箇所を、日本語版でも'extend'に変更する。

**Comment by cocoatomo** [comment]
報告ありがとうございました。
訳文を修正しました。(反映されるには数日かかると思います。)
