### ISSUE TITLE
Typo: 約 1100 万個 -> 約 110 万個

### ISSUE THREAD

**Issue by usr4** [python-doc-ja/python-doc-ja#827]
# 概要
Typo: 約 1100 万個 -> 約 110 万個
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/howto/unicode.html#definitions
# 問題の詳細
[Unicode HOWTO](https://docs.python.org/ja/3/howto/unicode.html)のページの[定義](https://docs.python.org/ja/3/howto/unicode.html#definitions)のセクション第4段落目にて、コードポイント総数が正しくは約 110 万個であるところ約 1100 万個と誤記されている。

> 約 1100 万個の値であり、今のところ 11 万個くらいが割り当てられています

英語原文では about 1.1 million と正しく表記されておりました。
# 修正案
約 1100 万個から約 110 万個に修正する。

**Comment by cocoatomo** [comment]
報告ありがとうございます。
訳文を修正しましたので、数日内に反映されます。
