### ISSUE TITLE
C API Reference manual: PyObjec_CallObjectの説明文中の翻訳の誤り

### ISSUE THREAD

**Issue by futatuki** [python-doc-ja/python-doc-ja#828]
# 概要
文意の反転
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/c-api/object.html#c.PyObject_CallObject
# 問題の詳細
 "If no arguments are needed, then args can be NULL." に対する訳が "no" のない文に対するものになっている。
# 修正案
s/必要/不要/

**Comment by cocoatomo** [comment]
報告ありがとうございます。
やくぶんを修正しておきました。
数日内には反映されます。
