### ISSUE TITLE
(要望) 翻訳に対する問題の報告先についての訳註が欲しい

### ISSUE THREAD

**Issue by futatuki** [python-doc-ja/python-doc-ja#829]
# 概要
翻訳に対する問題の報告を行う方法がわかりにくかったです。
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/bugs.html#documentation-bugs
# 問題の詳細
翻訳ドキュメント中の左の「このページ - バグ報告」の先のリンクで到達するページにおいて、翻訳に対する問題の報告を行う方法が示されていません。私は上記URL中のリンクから https://bugs.python.org/ にて問題の検索を行い、
https://bugs.python.org/issue40041
を見てたどり着きました。
# 修正案
できれば、訳註としてでも上記ページにこちらのissuesを日本語翻訳の問題の報告先として加えて頂ければ幸いです。

**Comment by cocoatomo** [comment]
報告ありがとうございます。

訳注の追加は https://github.com/python-doc-ja/python-doc-ja/issues/818 で済んでいるのですが、どうも新しい翻訳がドキュメントに反映されず古い翻訳のままのようです。

翻訳を適用したドキュメントのビルドは管轄外なので、担当している人達に聞いてみます。

**Comment by cocoatomo** [comment]
https://github.com/python/docsbuild-scripts/issues/87 のバグの影響でした。
修正され、訳注で問題の報告先が示されるようになりました。
