### ISSUE TITLE
「bz2 --- bzip2 圧縮のサポート」の翻訳について

### ISSUE THREAD

**Issue by 7shi** [python-doc-ja/python-doc-ja#830]
# 概要

実際の動作と異なる記述があり、誤訳だと思われます。

# 問題のある箇所 (URLで指定すること)

<https://docs.python.org/ja/3/library/bz2.html#bz2.BZ2Decompressor.decompress>

>  返すデータは以前の decompress() 呼び出しの出力を全て連結したものです。

# 問題の詳細

翻訳は実際の動作と異なります。

引数 `max_length` によって出力サイズを制限した場合、返されるデータが `max_length` を超える場合には複数回に分割して返されます。

原文: <https://docs.python.org/3/library/bz2.html#bz2.BZ2Decompressor.decompress>

> The returned data should be concatenated with the output of any previous calls to decompress().

原文の記述に問題はなく、連結されたデータが返されるのではなく、複数回に分割して返されたデータを利用する側で連結するように、と読み取れます。

# 修正案

返されるデータは以前の decompress() 呼び出しの出力に連結される必要があります。

**Comment by cocoatomo** [comment]
報告ありがとうございました。
訳文を修正しておきました。
