### ISSUE TITLE
assert_not_called の説明の時制

### ISSUE THREAD

**Issue by msakai** [python-doc-ja/python-doc-ja#831]
# 概要

`unittest.mock.Mock.assert_not_called` の説明は、他の箇所の翻訳に合わせて、過去形にしてはどうでしょうか?

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/unittest.mock.html#unittest.mock.Mock.assert_not_called
> assert_not_called()
> モックが呼ばれないことをアサートします。

原文:
https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_not_called
> assert_not_called()
> Assert the mock was never called.

# 問題の詳細

他の箇所の翻訳に合わせて、過去形にしてはどうでしょうか?

# 修正案

「モックが一度も呼ばれなかったことをアサートします。」

**Comment by cocoatomo** [comment]
報告ありがとうございました。
訳文を修正しておきました。
