### ISSUE TITLE
辞書型の説明で脱字

### ISSUE THREAD

**Issue by kaytruck** [python-doc-ja/python-doc-ja#832]
# 概要
脱字があります。
```
キーが (辞書の中で)一意でければならない、
```
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/tutorial/datastructures.html#dictionaries
# 問題の詳細
概要のとおり。
# 修正案
```
キーが (辞書の中で)一意でなければならない、
```

**Comment by cocoatomo** [comment]
報告ありがとうございました。
訳文を修正しておきました。
