### ISSUE TITLE
「グローバルインタプリタロック (Global Interpreter Lock) を取り除くことはできないのですか？」についての指摘

### ISSUE THREAD

**Issue by ko1** [python-doc-ja/python-doc-ja#835]
# 概要

GIL についての説明が英語と違っている（日本語のほうは意味が通らない）

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/faq/library.html#can-t-we-get-rid-of-the-global-interpreter-lock

# 問題の詳細

> And finally, once you have multiple interpreters not sharing any state, what have you gained over running each interpreter in a separate process?

> そして最後に、一旦複数のインタプリタを状態を全く共有しないようにしたとして、それぞれのインタプリタを独立したプロセス上で動かしてなにが得られるというのでしょうか？

ここでは、Python の GIL をなくす、という修正を、「状態を共有しない」ことで実現する、という手法について議論しています。ただ、それにどういうメリットがあるの？　と疑問を投げかけています。日本語のほうは、そういうニュアンスがわかりません。

# 修正案

そして最後に、状態を共有しないインタプリタを複数1プロセス上で作れたとして、各インタプリタをそれぞれ別プロセスで動かすのに比べてどういう利点があるのでしょうか？

**Comment by cocoatomo** [comment]
報告ありがとうございました。
訳文まで作っていただきとても助かりました。

**Comment by ko1** [comment]
> 状態を共有しないインタプリタを複数1プロセス上で作れたとして、

読みづらいという指摘を受けたので、

> 複数の、状態を共有しないインタプリタを1プロセス上で作れたとして、

とかのほうがいいかもしれません。

**Comment by cocoatomo** [comment]
訳文の提案ありがとうございます。
訳文の掛かり受けなどの調整は翻訳者に任されているので、もし強く「こう訳した方がいい」という意見があれば、それ用にissueを立ててください。

ここの訳文は下記の通りになったようです。

> そして最後に、状態を共有しないインタプリタを1プロセス上で複数作れたとして、各インタプリタをそれぞれ別プロセスで動かすのに比べてどういう利点があるのでしょうか？

**Comment by ko1** [comment]
ありがとうございます。よいと思います。
