### ISSUE TITLE
バグ: Documentationのリンクが404 Not Found

### ISSUE THREAD

**Issue by takanory** [python-doc-ja/python-doc-ja#836]
# 概要

* 各ページのトップにある「Documentation」のリンク先が https://docs.python.org/ja/index.html となっており、404 Not Foundになります
* 英語以外全部そうなので、サーバー側でredirect設定とかしているのかも?

<img width="1098" alt="3_8_5_Documentation" src="https://user-images.githubusercontent.com/988241/88606562-ed79da80-d0b7-11ea-97ce-b966d8e17ea4.png">

# 問題のある箇所 (URLで指定すること)

* https://docs.python.org/ja/3/index.html などおそらく全ページ

# 問題の詳細

# 修正案

* https://docs.python.org/ja/index.html にアクセスすると https://docs.python.org/ja/3/index.html に redirect するようにする
* 英語版は https://docs.python.org/index.html → https://docs.python.org/3/index.html となってました

**Comment by cocoatomo** [comment]
この問題は翻訳の範囲を越えていて、ここでは解決できないので、ドキュメント作成スクリプトのメンテナーにメールを投げておきました。
翻訳についての issue ではないので close します。
