### ISSUE TITLE
typo: picle

### ISSUE THREAD

**Issue by yoichi** [python-doc-ja/python-doc-ja#837]
# 概要

typo: picle

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/copy.html#copy.deepcopy

# 問題の詳細

```
copyreg モジュールによって登録された picle 関数を使用します。
```

のpicle は正しくは pickle です。

原文では `In fact, the copy module uses the registered pickle functions from the copyreg module.` となっています。

https://docs.python.org/3/library/copy.html

# 修正案

picle を pickle に修正

**Comment by ymyzk** [comment]
ご報告ありがとうございます．Python 3.6 まで遡って修正しました．
