### ISSUE TITLE
typo: Pyhon

### ISSUE THREAD

**Issue by raster0x2a** [python-doc-ja/python-doc-ja#838]
# 概要
typo: Pyhon
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/tutorial/appetite.html
# 問題の詳細
1. やる気を高めようの5段落目の1文目でPythonがPyhonとなっています。  
> Pyhon は簡単に利用できますが、本物のプログラミング言語であり、シェルスクリプトやバッチファイルよりも多くの機構があり、大きなプログラムの開発にも適しています。

# 修正案
Pyhon を Python に修正

**Comment by ymyzk** [comment]
ご報告ありがとうございます．Python 2.7 と 3.6 以降のドキュメントを修正しました．
