### ISSUE TITLE
ページにマークアップ(:meth: ロール)が表示されている

### ISSUE THREAD

**Issue by tk0miya** [python-doc-ja/python-doc-ja#841]
# 概要

os のページに reST マークアップ ```:meth:`~os.PathLike.__fspath__``` が変換されずに表示されている。

>さもなければ、 :meth:`~os.PathLike.__fspath__ が呼び出され、その戻り値が str か bytes のオブジェクトであれば、その値を返します。他のすべてのケースでは TypeError が送出されます。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/os.html#os.fspath

# 問題の詳細

# 修正案

訳文に閉じバッククォートが抜けているように見受けられます。

**Comment by mollinaca** [comment]
3.9のドキュメントにおいて、修正しておきました。
https://docs.python.org/ja/3.9/library/os.html#os.fspath

3.8に関してもTransifex上では修正しておきました。
定期ビルドの対象になっていないため、ドキュメント側には反映されないようです。
