### ISSUE TITLE
ページにマークアップ(:class: ロール)が表示されている

### ISSUE THREAD

**Issue by tk0miya** [python-doc-ja/python-doc-ja#842]
# 概要

組み込み関数のページに reST マークアップ ```:class:`io.RawIOBase``` が変換されずに表示されている。

>Windowsでは、コンソールバッファのオープンは、io.FileIO`ではなく、:class:`io.RawIOBase のサブクラスを返すでしょう。

その直前の ```io.FileIO` ``` にもバッククォートがひとつ表示されており、これも同種の問題のように見受けられます。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/functions.html#open

# 問題の詳細

# 修正案

訳文にバッククォートが抜けており、マークアップが正しく解釈されていないように思われます。

**Comment by mollinaca** [comment]
3.9のドキュメントにおいて、修正しておきました。
https://docs.python.org/ja/3.9/library/functions.html#open

3.8に関してもTransifex上では修正しておきました。
定期ビルドの対象になっていないため、ドキュメント側には反映されないようです。
