### ISSUE TITLE
用語集の「callback」の説明が英語のままで表示英訳

### ISSUE THREAD

**Issue by kawasaki2013** [python-doc-ja/python-doc-ja#843]
# 概要　用語集のcallbackの解説が英語のままである
# 問題のある箇所 　https://docs.python.org/ja/3/glossary.html#glossary
# 問題の詳細　用語集のcallbackの解説が英語のままである

「callback
A subroutine function which is passed as an argument to be executed at some point in the future.」と英語です。

# 修正案
「callback

コールバック関数とは、プログラム中で、呼び出し先の関数の実行中に実行されるように、あらかじめ指定しておく関数」
（Wikipediaより引用）

これに近い日本語訳でお願いいたします。または原文のまま、「将来において何らかの時点で関数の引数として渡す関数」

**Comment by cocoatomo** [comment]
「英語のまま」というより、翻訳する余裕が無く放置されたまま、というのが正確なところです。

> これに近い日本語訳でお願いいたします。

と書かれていますが、要望が通る保証はありませんので、その点ご理解ください。

ともあれご報告ありがとうございます。

**Comment by cocoatomo** [comment]
翻訳を付けました。
数日のうちに反映されるはずです。

**Comment by kawasaki2013** [comment]
cocoatomo様

お忙しい中、ご連絡、ご対応ありがとうございます。また何か気が付いた点がありましたらご連絡させていただきます。ありがとうございました。
