### ISSUE TITLE
不要な「`」が表示されている

### ISSUE THREAD

**Issue by nkmk** [python-doc-ja/python-doc-ja#844]
# 概要

不要な「`」が表示されており、インラインコードが正しく適用されていない。

# 問題のある箇所 (URLで指定すること)

- https://docs.python.org/ja/3/reference/expressions.html#value-comparisons

# 問題の詳細

以下の部分。内容は概要の通り。

> (例えば、 `[1,2,x] <= [1,2,y]` は `x <= y``と同じ値になります)。 対応する要素が存在しない場合、短い方のコレクションの方が先の順序となります (例えば、 ``[1,2] < [1,2,3]` は真です)。

# 修正案

> (例えば、 `[1,2,x] <= [1,2,y]` は `x <= y`と同じ値になります)。 対応する要素が存在しない場合、短い方のコレクションの方が先の順序となります (例えば、 `[1,2] < [1,2,3]` は真です)。

**Comment by ymyzk** [comment]
報告ありがとうございます． Python 3.6 以降のドキュメントを修正しました．ビルド後に反映されます．
