### ISSUE TITLE
GeneratorExit の説明の technically の誤訳

### ISSUE THREAD

**Issue by msakai** [python-doc-ja/python-doc-ja#845]
# 概要

GeneratorExit の説明の technically の誤訳

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/exceptions.html#GeneratorExit
> この例外はエラーではなく技術的なものなので、 Exception ではなく BaseException を直接継承しています。

原文
https://docs.python.org/3/library/exceptions.html#GeneratorExit
> It directly inherits from BaseException instead of Exception since it is technically not an error.

# 問題の詳細

ここの technically は「技術的なもの」ではなく「厳密に言えば」というような意味。

# 修正案

> この例外は厳密に言えばエラーではないので、 Exception ではなく BaseException を直接継承しています。

**Comment by cocoatomo** [comment]
誤訳報告ありがとうございます。
訳文として修正案を使わせてもらいました。
数日したら反映されるはずです。
