### ISSUE TITLE
asyncio.Futureの訳の改善

### ISSUE THREAD

**Issue by michitaro** [python-doc-ja/python-doc-ja#846]
# 概要

asyncio.Futureの訳の改善

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/asyncio-task.html#awaitables
のFutureの説明
> asyncio での Future オブジェクトは、async/await と共に使用できるようにするため、コールバック形式のコードを使用できるように設計すべきです。

原文
> Future objects in asyncio are needed to allow callback-based code to be used with async/await.

https://docs.python.org/3/library/asyncio-task.html#awaitables

# 問題の詳細

原文はおそらく
「Futureオブジェクトは(既存の)callbackスタイルのコードを`async` / `await`スタイルで（`await`でコールバックが実行されるまでブロックするために）使うために必要」
という意味です。

```python
import asyncio


def callback_style_sleep_1_second(done):
    import threading

    def f():
        import time
        time.sleep(1)
        done()

    threading.Thread(target=f).run()

# ↑のようなcallbackスタイルのコードをmain内のようなasync/awaitで使えるようにするために
# ↓のようにFutureを利用する

def async_await_style_sleep_1_second():
    fut = asyncio.Future()

    def done():
        fut.set_result(None)

    callback_style_sleep_1_second(done)
    return fut


async def main():
    print('start')
    await async_await_style_sleep_1_second()
    print('sleep done')


asyncio.run(main())
```

# 修正案

> Future objects in asyncio are needed to allow callback-based code to be used with async/await.

↓
> asyncioのFutureオブジェクトはコールバック形式のコードをasync/awaitで利用するために必要です。

のような感じはどうでしょうか？

**Comment by atsuoishimoto** [comment]
ありがとうございます。

遅くなりましたが、

> asyncioのFutureオブジェクトを使うと、async/awaitとコールバック形式のコードを併用できます。

と修正してみました。
