### ISSUE TITLE
timezone クラスの表現できるタイムゾーン

### ISSUE THREAD

**Issue by msakai** [python-doc-ja/python-doc-ja#847]
# 概要

timezone クラスの表現できるタイムゾーンの説明が分かりづらい。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/datetime.html#aware-and-naive-objects
> timezone クラスは単純な UTC からの固定オフセットだけを表わすUTC 自身や北アメリカの EST や EDT タイムゾーンのようなものも表現できます。

原文:
https://docs.python.org/3/library/datetime.html#aware-and-naive-objects
> The timezone class can represent simple timezones with fixed offsets from UTC, such as UTC itself or North American EST and EDT timezones.

# 問題の詳細

「単純な UTC からの固定オフセットだけを表わすUTC 自身」が日本語として不自然。

また、原文ではEST/EDTがUTCからのオフセットが固定ではないタイムゾーンの例として示されているが、そのことがこの訳からは分かりづらい。

# 修正案

> timezone クラスは、UTCからのオフセットが固定である単純なタイムゾーン（例えばUTCそれ自体）および、北アメリカにおける東部標準時（EST）／東部夏時間（EDT）のような単純ではないタイムゾーンの両方を表現できます。

**Comment by atsuoishimoto** [comment]
ありがとうございます。

遅くなりましたが、頂いた修正案通り修正させていただきました。
