### ISSUE TITLE
for文のドキュメントのtypo: 結果対する

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#848]
# 概要

Python言語リファレンス > 8.複合文 > 8.3. for文 で発見したtypoの共有

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/compound_stmts.html#the-for-statement

# 問題の詳細

`expression_list` の結果対するイテレータが生成されます。

# 修正案

`expression_list` の結果に対するイテレータが生成されます。
（「に」を補うことを提案します）

原文
 An iterator is created for the result of the `expression_list`.
https://docs.python.org/3/reference/compound_stmts.html#the-for-statement

**Comment by mollinaca** [comment]
報告ありがとうございます、修正しておきました。
ビルド後に反映されます。

**Comment by ftnext** [comment]
修正ありがとうございました。
遅くなりましたが、直っていることを確認しました
