### ISSUE TITLE
typingのドキュメントのtypo：拡張た

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#849]
# 概要

Python標準ライブラリ > 開発ツール > typing > 「モジュールの内容」で見つけたtypoの共有

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/typing.html#module-contents

# 問題の詳細

>これらの型は、既存の相当するクラスが [] をサポートするように拡張たときに Python 3.9 で廃止になりました。

「拡張た」はtypoと思われます

# 修正案

これらの型は、既存の相当するクラスが [] をサポートするように拡張されたときに Python 3.9 で廃止になりました。
（拡張た→拡張された と修正）

原文（「拡張た」に対応するのは were enhanced ）
These types became redundant in Python 3.9 when the corresponding pre-existing classes were enhanced to support [].
https://docs.python.org/3/library/typing.html#module-contents

**Comment by mollinaca** [comment]
報告ありがとうございます、修正しておきました。
次回ビルドで反映されます。
