### ISSUE TITLE
Pythonチュートリアル「3. 形式ばらない Python の紹介」にて2箇所マークアップが壊れている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#850]
# 概要

Pythonチュートリアル「3. 形式ばらない Python の紹介」にて、マークアップが壊れている箇所を発見しました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/tutorial/introduction.html#lists

# 問題の詳細

2箇所気づきました。
いずれも英語版ではリンクになっていますが、日本語版ではリンクではなく、マークアップのようなものが表示されています。

## 1箇所目

>文字列 (や他の全ての組み込みの :term:` シーケンス <sequence>` 型) のように、

## 2箇所目

>例えば、次のスライスは、リストの 浅い <shallow_vs_deep_copy> のコピー を返します。:

# 修正案

いずれも英語版のリンクを参考に、日本語版の該当箇所へのリンクをMarkdownで表現しました。
https://docs.python.org/3/tutorial/introduction.html#lists

## 1箇所目

文字列 (や他の全ての組み込みの [シーケンス](https://docs.python.org/ja/3/glossary.html#term-sequence) 型) のように、

※用語集のシーケンスへのリンクを挿入しました

## 2箇所目

例えば、次のスライスは、リストの [浅い](https://docs.python.org/ja/3/library/copy.html#shallow-vs-deep-copy) コピー を返します。:

※copyモジュールドキュメントの該当箇所へのリンクを挿入しました
※「浅いのコピー」はtypoであることに気づいたので「浅いコピー」としています

**Comment by mollinaca** [comment]
報告ありがとうございます、修正しておきました。
念の為ビルド結果を確認して、問題なければCloseします。
