### ISSUE TITLE
日本語のTypo (Python チュートリアル  - 6.4. パッケージ)

### ISSUE THREAD

**Issue by shinshin86** [python-doc-ja/python-doc-ja#852]
# 概要
Python チュートリアル内の `6.4. パッケージ` にて、日本語のTypoと思われる箇所を見つけたため、Issueを出させていただきました。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/tutorial/modules.html#packages
の ` __init__.py` に関する説明箇所。

> ファイルを含むディレクトリをパッケージをとしてPython に扱わせるには、ファイル __init__.py が必要です。

# 問題の詳細
上記、問題箇所にて、`パッケージをとして` という文言がありましたが、正しくは `パッケージとして` という文言になりますでしょうか？

# 修正案
```
ファイルを含むディレクトリをパッケージをとしてPython に扱わせるには、ファイル __init__.py が必要です。
```

↓

```
ファイルを含むディレクトリをパッケージとしてPython に扱わせるには、ファイル __init__.py が必要です。
```

**Comment by mollinaca** [comment]
報告ありがとうございます、修正しておきました。
次回ビルド時に反映されます。

**Comment by shinshin86** [comment]
ご対応ありがとうございます。
