### ISSUE TITLE
Python用語集の「duck-typing」から抽象基底クラスへのリンクが日本語訳にはない

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#853]
# 概要

用語集の「duck-typing」の項目に、抽象基底クラスへのリンクの代わりに、1という数字が混入しているのを発見しました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/glossary.html#term-duck-typing

# 問題の詳細

> (ただし、ダックタイピングを 抽象基底クラス 1 で補完することもできます。) 

英語では
> (Note, however, that duck-typing can be complemented with abstract base classes.)

https://docs.python.org/3/glossary.html#term-duck-typing
と「abstract base classes」へのリンクになっており、1は入っていません。

# 修正案

提案：1を削除し、用語集の「抽象基底クラス」へのリンクにすることを提案します。
https://docs.python.org/ja/3/glossary.html#term-abstract-base-class

修正イメージ
(ただし、ダックタイピングを [抽象基底クラス](https://docs.python.org/ja/3/glossary.html#term-abstract-base-class) で補完することもできます。)

**Comment by ymyzk** [comment]
#854 と同様のマークアップミスを 3.9 以降のドキュメントで確認し，修正しました．
