### ISSUE TITLE
Python用語集の「抽象基底クラス」からmagic methodへのリンクが日本語訳にはない

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#854]
# 概要

用語集の「抽象基底クラス」の項目に、magic methodへのリンクがなく、さらに、1という数字が混入しているのを発見しました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/glossary.html#term-abstract-base-class

# 問題の詳細

> (例えば magic methods 1 の場合)

英語では
> (for example with magic methods)

https://docs.python.org/3/glossary.html#term-abstract-base-class

- 「magic methods」へのリンクになっている
- 1は入っていない

# 修正案

提案：1を削除し、用語集の「magic method」へのリンクにすることを提案します。
https://docs.python.org/ja/3/glossary.html#term-magic-method

修正イメージ
(例えば [magic methods](https://docs.python.org/ja/3/glossary.html#term-magic-method) の場合)

**Comment by ymyzk** [comment]
報告ありがとうございます．3.9 以降のドキュメントにマークアップの誤りを確認し修正しました．
