### ISSUE TITLE
ページにマークアップ(:data: ロール)が表示されている

### ISSUE THREAD

**Issue by tk0miya** [python-doc-ja/python-doc-ja#855]
# 概要

token モジュールのページに reST マークアップ  `:data:` が変換されずに表示されている。末尾のバッククォートが不足している (`:` に typo している) 模様です。

> バージョン 3.5 で変更: AWAIT と :data:`ASYNC: トーケンが追加されました。

また、「トーケン」は typo だと思われます。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/token.html#token.ENCODING (ページ末尾)

# 問題の詳細
# 修正案

* 訳文にバッククォートが抜けており、マークアップが正しく解釈されていないように思われます。
* トーケンをトークンに修正するのはどうでしょうか。

**Comment by ymyzk** [comment]
報告ありがとうございます． Python 3.7 以降のドキュメントでこの問題を確認し修正しました．次回以降のビルドで反映されるはずです．

**Comment by tk0miya** [comment]
素早い対応ありがとうございます！
