### ISSUE TITLE
doctestのドキュメントのtypo：ティレクティブ

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#856]
# 概要

 Python 標準ライブラリ > 開発ツール > doctest > ディレクティブ (Directives) で見つけたtypoの共有

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/doctest.html#directives

# 問題の詳細

 >doctest ティレクティブは後のソースコード例にあるような特殊な Python コメントです:

# 修正案

「ティレクティブ」→「ディレクティブ」と修正

原文を確認したところティレクティブはtypoと思われます（対応する部分を斜体で示します）
https://docs.python.org/3/library/doctest.html#directives
>Doctest directives may be used to modify the option flags for an individual example. Doctest *directives* are special Python comments following an example’s source code:

**Comment by ymyzk** [comment]
報告ありがとうございます．修正致しましたので，次回ビルドで反映されます．
