### ISSUE TITLE
extention (extension のスペルミス)

### ISSUE THREAD

**Issue by tueda** [python-doc-ja/python-doc-ja#857]
# 概要

extention (extension のスペルミス)。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/extending/extending.html?highlight=extention
https://docs.python.org/ja/3/c-api/intro.html?highlight=extention

検索すると2箇所ありました。

![image](https://user-images.githubusercontent.com/1481665/105353561-c0575080-5c32-11eb-8589-2897312478f1.png)

# 問題の詳細

「拡張モジュール (extention module) 」のようになっていますが、該当する英語版のページでは extension module です。

# 修正案

extension に直す。

**Comment by ymyzk** [comment]
報告ありがとうございます．修正しましたので，次回ビルドで反映されます．
