### ISSUE TITLE
Python言語リファレンスの累算代入文にて、マークアップに使っているアスタリスクが紙面に表示されている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#858]
# 概要

Python言語リファレンス「7.2.1. 累算代入文」にて、マークアップに使っているアスタリスクが紙面に表示されている箇所を発見しました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/simple_stmts.html#augmented-assignment-statements

# 問題の詳細

`通常の代入とは違い、累算代入文は右辺を評価する*前に*左辺を評価します。`

「`*前に*`」とアスタリスクで囲まれた部分を指摘しています。

英語では、beforeが斜体になっており、マークアップが機能しています。

> Unlike normal assignments, augmented assignments evaluate the left-hand side *before* evaluating the right-hand side.

https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements

# 修正案

ドキュメントはSphinxで書かれていると思うのですが、私の経験の範囲からは、
開始のアスタリスクの前と、終わりのアスタリスクの前に半角スペースを1つずつ入れると解決すると思います。

`通常の代入とは違い、累算代入文は右辺を評価する *前に* 左辺を評価します。`

**Comment by cocoatomo** [comment]
報告ありがとうございました。

修正案の通り直したので、数日後には反映されていると思います。
