### ISSUE TITLE
tempfileのドキュメントで、context managerが「コンテクスト管理者」と訳されている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#859]
# 概要

tempfileのドキュメントで、context managerが「コンテクスト管理者」と訳されている

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/tempfile.html#tempfile.TemporaryDirectory

# 問題の詳細

TemporaryDirectoryのドキュメント内でcontext managerの訳が揺れているのが問題と考えています。

>The resulting object can be used as a context manager
>返されたオブジェクトは、コンテキストマネージャとして使用することができます

> When the returned object is used as a context manager
> 返されたオブジェクトがコンテクスト管理者として使用された場合、

また、コンテキストマネージャのマネージャを*管理者*と訳していることで、不要なわかりにくさを生んでしまっていると思います。

# 修正案

「コンテクスト管理者」を「コンテキストマネージャ」に変更する

- https://docs.python.org/3/library/tempfile.html で context manager は
  - コード例に2件
  - 本文に4件出てきます
- tempfileのドキュメントには「コンテクスト管理者」は1件だけでした→これだけ直せば解決すると思います
  - 本文の3件は「コンテキストマネージャ」に統一されていました

「コンテキストマネージャ」は用語集に載っているので、統一先として妥当と考えます
https://docs.python.org/ja/3/glossary.html#term-context-manager
また、過去に https://github.com/python-doc-ja/python-doc-ja/issues/802 で「コンテキストマネージャ」に統一したことも確認しました

**Comment by cocoatomo** [comment]
報告ありがとうございます。訳文を修正しました。
