### ISSUE TITLE
tempfileのドキュメントで日本語訳と英語版とでリンクが異なる箇所がある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#860]
# 概要

tempfile.TemporaryDirectory のドキュメントから例として参照しているリンクが日本語版と英語版とで異なる

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/tempfile.html#tempfile.TemporaryDirectory

# 問題の詳細

英語版 https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory
>(see Examples)

Examplesは https://docs.python.org/3/library/tempfile.html#tempfile-examples へのリンク

該当箇所の日本語訳
>(with文とコンテキストマネージャ を参照)

データモデルのドキュメントへのリンクになっています
https://docs.python.org/ja/3/reference/datamodel.html#context-managers

# 修正案

日本語版のリンクも英語と合わせる。
具体的には https://docs.python.org/ja/3/library/tempfile.html#tempfile-examples に変更する

変更することで「(使用例 を参照)」と表示されるようになると期待しています

**Comment by cocoatomo** [comment]
報告ありがとうございます。訳文を修正しました。
