### ISSUE TITLE
tempfileのTemporaryDirectoryの翻訳の提案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#861]
# 概要

>返されたオブジェクトがコンテクスト管理者として使用された場合、1つなら name は with 文内の as のターゲットに割り当てられます。

という訳の「1つなら」が原文の意味の取り違えではないかと考えています。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/tempfile.html#tempfile.TemporaryDirectory

# 問題の詳細

https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory

>When the returned object is used as a context manager, the name will be assigned to the target of the as clause in the with statement, if there is one.

「1つなら」は`if there is one.`の訳だと思います。
ですが、1という意味のoneではなく、target (the target of the as clause in the with statement) を指すoneだと思います。
意味としては「asのtargetがあれば」となると思われます

# 修正案

「返されたオブジェクトがコンテクスト管理者として使用された場合、」のあとの訳の案です

- 「with 文内の as のターゲットがあれば、name が割り当てられます。」
- 「with 文内の as のターゲットがあれば、それに name が割り当てられます。」

**Comment by cocoatomo** [comment]
報告ありがとうございます。訳文を修正しました。
