### ISSUE TITLE
データモデルのドキュメントで「object」が「属性」と訳されている箇所がある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#862]
# 概要

Python言語リファレンス > データモデル 中の訳で「object」が「属性」と訳されている箇所がある

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/datamodel.html#objects-values-and-types

# 問題の詳細

>すべての属性は、同一性 (identity)、型、値をもっています。 

原文は
https://docs.python.org/3/reference/datamodel.html#objects-values-and-types
>Every object has an identity, a type and a value. 

objectを属性と訳していることで分かりにくくなっていると思います

用語集では、objectは「オブジェクト」と訳されていました
https://docs.python.org/ja/3/glossary.html#term-object

# 修正案

すべての**オブジェクト**は、同一性 (identity)、型、値をもっています。 

※変更点を強調しています

**Comment by cocoatomo** [comment]
報告ありがとうございます。訳文を修正しました。
