### ISSUE TITLE
unittestのドキュメントのtypo：使用されします

### ISSUE THREAD

**Issue by almandite1** [python-doc-ja/python-doc-ja#863]
# 概要
Python 標準ライブラリ > 開発ツール > unittest > クラスと関数で見つけたtypoの共有

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/unittest.html#classes-and-functions

# 問題の詳細
`TestCase のインスタンスのメソッドは3種類のグループを提供します。 1つ目のグループはテストの実行で使用されします。`:

# 修正案
「使用されします」→「使用されます」と修正

**Comment by ymyzk** [comment]
報告ありがとうございます．修正案通りに修正いたしましたので，次回ビルドで反映されます．
