### ISSUE TITLE
言語リファレンスの「Yield式」で参照されているPEPの番号に前ゼロが付いている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#864]
# 概要

Python 言語リファレンス > 6. 式 > 6.2.9. Yield 式 にて「参考」として掲載されているPEPの番号に、
前ゼロが付いているものが見つかりました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/expressions.html#yield-expressions

# 問題の詳細

>PEP 0342 - 拡張されたジェネレータを用いたコルーチン

リンクされたPEPは「PEP 342 -- Coroutines via Enhanced Generators」
https://www.python.org/dev/peps/pep-0342/

原文のSee alsoの部分は「PEP 342 - Coroutines via Enhanced Generators」
https://docs.python.org/3/reference/expressions.html#yield-expressions

# 修正案

「PEP 0342」→「PEP 342」と0をトル

**Comment by mollinaca** [comment]
ありがとうございます、修正しておきました。
次回ビルド時に修正が反映されます。
