### ISSUE TITLE
言語リファレンスの「yield 文」で「yield expression」の訳語に表記揺れがある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#865]
# 概要

Python 言語リファレンス > 7. 単純文 > 7.7. yield 文で「yield expression」の訳語に表記揺れを見つけました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/simple_stmts.html#yield

# 問題の詳細

>yield 文は意味的に yield expression 式と同じです。

原文
https://docs.python.org/3/reference/simple_stmts.html#yield
>A yield statement is semantically equivalent to a yield expression

この節では「yield expression」は「yield 式」と訳されているが、上記の箇所だけ表記揺れしている。
また、expressionと式とで意味が重複している（「頭痛が痛い」「馬から落馬」のようになっている）

# 修正案

「yield expression 式」→「yield 式」
※「yield 式」が https://docs.python.org/ja/3/reference/expressions.html#yieldexpr へのリンクとなる

**Comment by mollinaca** [comment]
ありがとうございます、修正しました。
次回ビルド時に修正されます。
念の為修正を確認後にこちらのIssueはクローズします。

**Comment by ftnext** [comment]
いつも修正ありがとうございます
