### ISSUE TITLE
datetimeのドキュメントに「。」が重なった箇所がある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#866]
# 概要

Python 標準ライブラリ > データ型 > datetime のドキュメントに「。」が重なった箇所を見つけました

# 問題のある箇所 (URLで指定すること)

以下の2箇所です

- https://docs.python.org/ja/3/library/datetime.html#datetime.time.hour
- https://docs.python.org/ja/3/library/datetime.html#datetime.datetime.hour

# 問題の詳細

>満たします。。

「。」が重なっていることに気づきました

原文
https://docs.python.org/3/library/datetime.html#datetime.time.hour
>In `range(24)`.

「。」を重ねて訳す必要はなさそうなので、入力時に混入した（typoの一種）と考えています。

# 修正案

2箇所とも「満たします。」に修正

**Comment by mollinaca** [comment]
ありがとうございます、修正しておきました。
