### ISSUE TITLE
日本語のタイポ

### ISSUE THREAD

**Issue by lissxxxx** [python-doc-ja/python-doc-ja#869]
# 概要
タイポ

# 問題のある箇所 (URLで指定すること)
<https://docs.python.org/ja/3/tutorial/controlflow.html#positional-only-parameters>

# 問題の詳細
これをもう少し詳しく見てみると、特定の引数を 位置専用 と印を付けるられます。

# 修正案
これをもう少し詳しく見てみると、特定の引数を 位置専用 と印を付けられます。

**Comment by mollinaca** [comment]
指摘ありがとうございます、修正しておきました。
