### ISSUE TITLE
pickleのtypo

### ISSUE THREAD

**Issue by pataiji** [python-doc-ja/python-doc-ja#871]
# 概要
pickleに関するドキュメントでpickelとtypoがある

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/pickle.html#data-stream-format

# 問題の詳細
> サイズの抑制目的の最適化が必要なら、pickel されたデータを効率的に 圧縮する ことができます。

pickle の誤りかと思います

# 修正案
pickel -> pickle へ修正する

**Comment by mollinaca** [comment]
指摘ありがとうございます、修正しておきました。
