### ISSUE TITLE
「条件式」にて原文の同格のカンマの取り違え

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#872]
# 概要

Python言語リファレンス > 6. 式 > 6.13. 条件式 にて

>`x if C else y` という式は最初に条件 *x* ではなく *C* を評価します;

「条件 x ではなく C を評価します」という訳が原文の取り違えと思われます。
xを条件と呼ぶのは誤り（条件と呼ぶべきはCの方）だと思います

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/expressions.html#conditional-expressions

# 問題の詳細

原文：https://docs.python.org/3/reference/expressions.html#conditional-expressions

>The expression `x if C else y` first evaluates the condition, *C* rather than *x*.

「the condition, C」は**同格**のカンマだと思われます。
訳すと「条件C」

# 修正案

`x if C else y` という式は最初に *x* ではなく条件 *C* を評価します。

（原文にセミコロンがなかったので、句点に変えて上記提案しました）

**Comment by mollinaca** [comment]
指摘ありがとうございます。確かにおかしいですね。
ご提案いただいた内容で修正しておきました。
次回ビルド時に反映されます。
