### ISSUE TITLE
組み込み関数「max」「min」のtypo

### ISSUE THREAD

**Issue by nkmk** [python-doc-ja/python-doc-ja#873]
# 概要

組み込み関数`max`, `min`の説明にtypoがある。

# 問題のある箇所 (URLで指定すること)

- https://docs.python.org/ja/3/library/functions.html#max
- https://docs.python.org/ja/3/library/functions.html#min

# 問題の詳細

> 位置引数が1つだけ与えられた場合、それはは空でない iterable でなくてはいけません。

※`max`, `min`どちらも同じ文章

# 修正案

「それはは」→「それは」

> 位置引数が1つだけ与えられた場合、それは空でない iterable でなくてはいけません。

**Comment by mollinaca** [comment]
指摘ありがとうございます、修正しておきました。
次回ビルド時に修正されます。
