### ISSUE TITLE
「C や C++ による Python の拡張」での矛盾文言

### ISSUE THREAD

**Issue by noymer** [python-doc-ja/python-doc-ja#874]
# 概要

「Python インタプリタの拡張と埋め込み » 1. C や C++ による Python の拡張 」
で矛盾する文言があり、削除すべき。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/extending/extending.html#back-to-the-example

# 問題の詳細

>return PyLong_FromLong(sts);
>
>上の場合では、 Py_BuildValue() は整数オブジェクトを返します。(そう、整数ですら、 Python においてはヒープ上のオブジェクトなのです! )

と書いてあるが、実際には上では `PyLong_FromLong()` を使っていて、おかしい。
そして英語版では以下のようになっている。

>In this case, it will return an integer object. (Yes, even integers are objects on the heap in Python!)
>
>https://docs.python.org/3/extending/extending.html#back-to-the-example

# 修正案

「上の場合では、整数オブジェクトを返します。(そう、整数ですら、 Python においてはヒープ上のオブジェクトなのです! )」とする。（「Py_BuildValue() は」を削り、英語と合わせる）

--

よろしくお願いします！

**Comment by mollinaca** [comment]
指摘ありがとうございます。
案としていただいた内容で修正しておきました。次回ビルド時に反映されます。
