### ISSUE TITLE
Python言語リファレンス > インポートシステム中で見つけた助詞が落ちている箇所

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#875]
# 概要

「5.4.4. インポート関連のモジュール属性」の中の `__package__` 属性の説明文中に以下があります。

>モジュールがパッケージでない場合、トップレベルのモジュールでは `__package__` 空の文字列、

「`__package__` 空の文字列」は「は」が落ちていると思います

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/import.html#__package__

# 問題の詳細

原文を示します
https://docs.python.org/3/reference/import.html#__package__
>When the module is not a package, `__package__` should be set to the empty string for top-level modules, ...

# 修正案

モジュールがパッケージでない場合、トップレベルのモジュールでは `__package__` は空の文字列、

※「は」を補いました

**Comment by mollinaca** [comment]
指摘ありがとうございます、修正しておきました。
次回ビルド時に反映されます。
