### ISSUE TITLE
Python 標準ライブラリのabcのドキュメントでoverrideをオーバーロードと取り違えて訳している箇所がある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#876]
# 概要

原文のoverrideを「オーバーロード」と訳している箇所を見つけました

>ABCMeta の派生クラスをメタクラスに持つクラスは、全ての抽象メソッドとプロパティをオーバーロードしない限りインスタンス化することができません。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/abc.html#abc.abstractmethod

# 問題の詳細

原文
https://docs.python.org/3/library/abc.html#abc.abstractmethod
>A class that has a metaclass derived from ABCMeta cannot be instantiated unless all of its abstract methods and properties are overridden.

「are overridden（オーバーライド）」を**オーバーロードと取り違え**ています。

ブラウザの機能で https://docs.python.org/3/library/abc.html の中を「overload」で検索したところ0件ヒットでした。

# 修正案

ABCMeta の派生クラスをメタクラスに持つクラスは、全ての抽象メソッドとプロパティをオーバーライドしない限りインスタンス化することができません。

**Comment by mollinaca** [comment]
指摘ありがとうございます、修正しておきました。
次回ビルド時に反映されます。
