### ISSUE TITLE
Unicode HOWTO に見つけた読みづらい訳のカイゼン提案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#877]
# 概要

「任意のサイズのチャンク (例えば、1024 もしくは 4096 バイト) にファイルの内容を読み込みたい場合、」に続く部分に読みづらい訳がありました。

>ある 1 つの Unicode 文字をエンコードしたバイト列が、チャンクの末尾での一部分のみ読み込まれの場合のエラー処理のためのコードを書く必要があります。

原文を確認した上で、「チャンクの末尾での一部分のみ読み込まれの場合」の部分をカイゼンする訳を提案します。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/howto/unicode.html#reading-and-writing-unicode-data

# 問題の詳細

原文
https://docs.python.org/3/howto/unicode.html#reading-and-writing-unicode-data

>If you want to read the file in arbitrary-sized chunks (say, 1024 or 4096 bytes), you need to write error-handling code to catch the case where only part of the bytes encoding a single Unicode character are read at the end of a chunk.

# 修正案

任意のサイズのチャンク (例えば、1024 もしくは 4096 バイト) にファイルの内容を読み込みたい場合、

ある1つの Unicode 文字をエンコードしたバイト列の一部だけが、チャンクの末尾で読み込まれた場合の

エラー処理のためのコードを書く必要があります。

---

構文メモ

S: only part of the bytes (encoding a single Unicode character でbytesを修飾)
V: are read [at the end of a chunkで修飾]

**Comment by shinsa82** [comment]
ご指摘ありがとうございます。「場合」の重複を避けるためにこうしましたがよろしいでしょうか。
ビルドが完了しましたら近日中にドキュメントに反映されます。

```
ある1つの Unicode 文字をエンコードしたバイト列の一部だけがチャンクの末尾まで読み込まれたケースに対応する、
エラー処理コードを書く必要があります。
```
