### ISSUE TITLE
math.iscloseのabs_tol引数の説明の誤訳

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#878]
# 概要

`math.isclose`の`abs_tol`引数の説明部分の

>abs_tol は0より大きくなければなりません。

は、`abs_tol=0.0`というデフォルト値と矛盾しています。
原文を確認したところ、誤訳だと思います

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/math.html#math.isclose

# 問題の詳細

原文
https://docs.python.org/3/library/math.html#math.isclose

>abs_tol must be at least zero.

# 修正案

いくつか案を出します

1. abs_tol は最低でも0でなければなりません。（at least: 少なくとも、最低でも に忠実な案）
2. abs_tol は0以上でなければなりません。（現在の訳に近く、かつ、at leastの意味を反映した案）

**Comment by mollinaca** [comment]
指摘ありがとうございます。これは "より" ではなく "以上" が正しいですね。
修正案の 2 を採用させていただきました。次回ビルド時に反映されます。
