### ISSUE TITLE
sys.setswitchinterval()の誤訳

### ISSUE THREAD

**Issue by a-takahashi223** [python-doc-ja/python-doc-ja#879]
# 概要

`sys.setswitchinterval()`の訳に誤りがあります。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/sys.html#sys.setswitchinterval

# 問題の詳細

> 実際の値はより高くなることがあり、特に長時間実行される内部関数やメソッドが使われた時や、他にスレッドが、その間隔の終了をオペレーティングシステムが決定するようスケジュールされた場合などが該当します。

一見して意味がわからず、原文とも対応しません。

原文

> Please note that the actual value can be higher, especially if long-running internal functions or methods are used. Also, which thread becomes scheduled at the end of the interval is the operating system’s decision.

原文は2つの文なのに、1つに訳されています。

# 修正案

特に長時間実行される内部関数やメソッドが使われたとき、実際の値はより高くなることがあります。
また、どのスレッドが間隔（注：インタプリタのスレッド切り替え間隔のこと）の終わりにスケジュールされる（注：次に実行される）かはオペレーティングシステムが決定します。

といった訳でいかがでしょうか。

**Comment by mollinaca** [comment]
指摘ありがとうございます。
修正案を参考に、以下のように修正してみました。次回ビルド時に反映されます。
```
特に長時間実行される内部関数やメソッドが使われたとき、実際の値はより高くなることがあります。
また、どのスレッドがスレッド切り替え間隔の終わりにスケジュールされる（次に実行される）かはオペレーティングシステムが決定します。
```
