### ISSUE TITLE
What's New の PEP 538: レガシーな C ロケールの抑圧 の1段落めの意味がとれない

### ISSUE THREAD

**Issue by mft** [python-doc-ja/python-doc-ja#881]
# 概要
3.7 What's New の "PEP 538: レガシーな C ロケールの抑圧" 節の1段落めの意味がとれない

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3.7/whatsnew/3.7.html#pep-538-legacy-c-locale-coercion

# 問題の詳細
原文
> An ongoing challenge within the Python 3 series has been determining a sensible default strategy for handling the “7-bit ASCII” text encoding assumption currently implied by the use of the default C or POSIX locale on non-Windows platforms.

訳文
> Python 3 シリーズにおける継続中の課題は、"7-bit ASCII" テキストのエンコーディングが何であるかと仮定して、取り扱う賢明なデフォルトの方針です。現在は、非 Windows のプラットフォームではデフォルトの C ロケールつまり POSIX ロケールを使っていると暗黙的に判断されます。

問題点
文の骨格は A challenge has been determining strategy つまり 課題は方針を決めること です。
何の strategy かというと for handling assumption つまり 仮定を取り扱う方針 であるはずです。
この assumption=仮定 を修飾する部分が長いので訳しづらいのは確かですが、
現在の訳文はこの文の構造を捉え損なっているように思えます。

# 修正案

> Python 3 シリーズにおける継続中の課題の一つは、非 Windows プラットフォームではデフォルトの C ロケールつまり POSIX ロケールの使用から現在のところ必然的に導かれてしまう "7-bit ASCII" テキストエンコーディングの仮定を取り扱う賢明なデフォルトの方針を決定することです。

**Comment by mollinaca** [comment]
指摘ありがとうございます！
内容確認し、提案いただいた修正案を採用させていただきました。
次回ビルド時に反映されます。
