### ISSUE TITLE
用語集 ファイルオブジェクト で oriented の訳が「志向」になっている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#882]
# 概要

用語集の「ファイルオブジェクト」の説明ですが、

>ファイル志向 API

訳語としては「指向」が適切なように思いました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/glossary.html#term-file-object

# 問題の詳細

翻訳
>下位のリソースへのファイル志向 API (read() や write() メソッドを持つもの) を公開しているオブジェクトです。

原文 https://docs.python.org/3/glossary.html#term-file-object
>An object exposing a file-oriented API (with methods such as read() or write()) to an underlying resource.

orientedは用語集の原文で他に2箇所出てきます。

- object oriented programming languages (metaclass) → オブジェクト指向
- a byte-oriented datastream (text file) → バイト指向

これらの訳語と合わせて「指向」の方が適切と考えます

# 修正案

下位のリソースへのファイル指向 API (read() や write() メソッドを持つもの) を公開しているオブジェクトです。

※underlying resource「下位のリソース」という訳もよりよくできそうなのですが、すぐには浮かばずママとしました

**Comment by shinsa82** [comment]
ご指摘ありがとうございます。修正しました。次回ビルド時に反映されます。
