### ISSUE TITLE
式のドキュメント中の「6.10.1. 値の比較」にtypoがある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#883]
# 概要

>オブジェクト、値、および型 の章では、オブジェクトは (型や id のに加えて) 値を持つことを述べています。

「id のに」がtypoと思われます

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/expressions.html#value-comparisons

# 問題の詳細

原文 https://docs.python.org/3/reference/expressions.html#value-comparisons
>Chapter Objects, values and types states that objects have a value (in addition to type and identity). 

in addition to type and identity の訳にtypoがあると考えています

# 修正案

オブジェクト、値、および型 の章では、オブジェクトは (型や id に加えて) 値を持つことを述べています。

※「のに」→「に」

**Comment by ymyzk** [comment]
修正案の通りに修正しました．次回ビルドで反映されます．
