### ISSUE TITLE
`argparse` の `allow_abbrev` 引数の誤訳

### ISSUE THREAD

**Issue by toslunar** [python-doc-ja/python-doc-ja#885]
# 概要

`argparse` の `allow_abbrev` 引数の説明が誤っています。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/argparse.html#argparse.ArgumentParser
https://docs.python.org/ja/3/library/argparse.html#prefix-matching

# 問題の詳細

現在の訳文では `allow_abbrev` により long option を short option に省略できるようにも読めますが、実際はたとえば `--number` を `-n` にではなく `--num` などに省略する機能です。

原文
> allow_abbrev - Allows long options to be abbreviated if the abbreviation is unambiguous. (default: True)

和訳
> allow_abbrev - 長いオプションが先頭の 1 文字に短縮可能 (先頭の文字が一意) である場合に短縮指定を許可する。(デフォルト: True)

# 修正案

「先頭の 1 文字」、「先頭の一文字」を「先頭文字列」に変更。「接頭辞」でも良いかもしれません。

修正例：
allow_abbrev - 長いオプションを先頭文字列で指定することを (一意に定まる場合に) を許可する。(デフォルト: True)

**Comment by mollinaca** [comment]
指摘ありがとうございます。
提案いただいた内容で修正しました。次回ビルド時に反映されます。
