### ISSUE TITLE
Python 言語リファレンス > 4.1. プログラムの構造 に見つけた、助詞の脱落と思われる箇所

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#886]
# 概要

>引数 -m を使用して、コマンド行からトップレベルスクリプト(モジュール `__main__` として)として実行されるモジュールコードブロックでもあります。

「〜もコードブロックです」が連続している中で、この文だけ平仄が合わないように思いました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/executionmodel.html#structure-of-a-program

# 問題の詳細

原文
https://docs.python.org/3/reference/executionmodel.html#structure-of-a-program
>A module run as a top level script (as module `__main__`) from the command line using a -m argument is also a code block.

大まかに捉えると A module is also a code block. という文なので、
「モジュールコードブロックでもあります」→「モジュール **も** コードブロックでもあります」
のように助詞が落ちているのではないかと考えています

# 修正案

「引数 -m を使用して、コマンドラインからトップレベルスクリプト(モジュール `__main__` として)として実行されるモジュールもまた、コードブロックです。」

- 助詞の落ちを修正（alsoの意味が出るように訳しました）
- コマンド行 → コマンドライン（＝ターミナル）と合わせて修正

## もう少し

修正案を書く中で「トップレベルスクリプト(モジュール `__main__` として)として」の部分も気になりました。
as a top level script (as module `__main__`)

ただ、どちらで解釈すればいいかはよく分かっていません

1. as a top level script as module `__main__` の後半を () に入れたもの
2. as a top level script の言い換えが as module `__main__`
    - https://docs.python.org/ja/3/library/__main__.html を参照すると2なのかなと思えてきました

別案

1. 引数 -m を使用して、コマンドラインから (モジュール `__main__` として) トップレベルスクリプトとして実行されるモジュールもまた、コードブロックです
2. 引数 -m を使用して、コマンドラインからトップレベルスクリプト (すなわち、モジュール `__main__` ) として実行されるモジュールもまた、コードブロックです

**Comment by osamu0329nakamura** [comment]
個人的に、別案2が自然な文章と感じたためこちらを採用して修正しました。
ドキュメントへの反映は自動ビルド後となるため、修正の反映までしばらくお待ちください。

**Comment by ftnext** [comment]
確認ありがとうございます。

このIssue閉じられるかなと思って、https://docs.python.org/ja/3/reference/executionmodel.html#structure-of-a-program を見たのですが、「概要」に記載した通りの文でした。
修正はまだ反映されていないようです

**Comment by atsuoishimoto** [comment]
修正の反映を確認したのでcloseします
