### ISSUE TITLE
用語集 named tuple に誤字

### ISSUE THREAD

**Issue by bsh-git** [python-doc-ja/python-doc-ja#887]
# 概要
誤字があります
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3.11/glossary.html#term-named-tuple
# 問題の詳細
 collections.namedtuple() ファクトリ関数デ作成したりできます
# 修正案
 collections.namedtuple() ファクトリ関数で作成したりできます

**Comment by osamu0329nakamura** [comment]
報告ありがとうございます。
以下のバージョンのドキュメントを修正しました。修正内容はビルド後自動的に反映されます。
- 3.11
- 3.9
- 3.8
- 3.7

**Comment by atsuoishimoto** [comment]
反映を確認したのでCloseします。
