### ISSUE TITLE
標準ライブラリ > `sys` > `sys.__std{in,out,err}__` の脱字

### ISSUE THREAD

**Issue by kakurasan** [python-doc-ja/python-doc-ja#888]
# 概要
脱字と思われる

# 問題のある箇所 (URLで指定すること)
[`https://docs.python.org/ja/3/library/sys.html#sys.__stdin__`](https://docs.python.org/ja/3/library/sys.html#sys.__stdin__)

3.5から3.11のバージョンごとのページでも同様

# 問題の詳細
> そのオブジェクトを復元る事を推奨します。

"復元る" という表現は聞いたことがないので、脱字ではないでしょうか

# 修正案
そのオブジェクトを復元する事を推奨します。

**Comment by osamu0329nakamura** [comment]
報告ありがとうございます。

下記のバージョンで翻訳を修正しました。
自動ビルドによるドキュメントへの反映までしばらく日数をいただきます。

- 3.10
- 3.9
- 3.8
- 3.7
- 3.6

3.5はドキュメント凍結済みのため修正しませんでした。

**Comment by atsuoishimoto** [comment]
反映を確認したのでcloseします
