### ISSUE TITLE
Logging HOWTO 中で、マークアップに使っている * が紙面に表示されている（2箇所）

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#889]
# 概要

斜体のマークアップに使っている `*` がページ上に表示されています。
2箇所見つけました

# 問題のある箇所 (URLで指定すること)

- 1箇所目：https://docs.python.org/ja/3/howto/logging.html#logging-from-multiple-modules
- 2箇所目：https://docs.python.org/ja/3/howto/logging.html#displaying-the-date-time-in-messages

# 問題の詳細

## 1箇所目

```
myapp.py を実行すれば、*myapp.log*でログが確認できます:
```

英語では `*` は表示されておらず、myapp.log が斜体になっています。
https://docs.python.org/3/howto/logging.html#logging-from-multiple-modules
>If you run myapp.py, you should see this in myapp.log:

## 2箇所目

```
以下の例の様に、``basicConfig``関数の*datefmt*引数に指定する必要があります:
```

英語では `*` は表示されておらず、datefmt が斜体になっています。
また、2連ダブルクォートも表示されておらず、basicConfig が code として扱われています。
https://docs.python.org/3/howto/logging.html#displaying-the-date-time-in-messages
>provide a datefmt argument to basicConfig, as in this example:

# 修正案

`*`マークアップの前後に空白を入れれば、パースされると思います。
※私が思い違いをしているかもしれません。手元で`make html`して確認するのが確実だと思います

## 1箇所目

```
myapp.py を実行すれば、*myapp.log* でログが確認できます:
```

（`log*` の後ろに半角スペースを挿入）

## 2箇所目

```
以下の例の様に、``basicConfig`` 関数の *datefmt* 引数に指定する必要があります:
```

- `*datefmt*` の前後に半角スペースを挿入
- basicConfig の後ろの2連バッククォートの後ろに半角スペースを挿入

**Comment by mollinaca** [comment]
指摘ありがとうございます、こちら修正しておきました。
ビルド確認後クローズします。

**Comment by ftnext** [comment]
修正ありがとうございます。

このIssueを閉じられるかなと「問題のある箇所」のURLを確認しましたが、まだ反映されていないようです

**Comment by mollinaca** [comment]
改めて修正しました、反映が確認できたらこちらでクローズしておきます。
ご報告ありがとうございます。

**Comment by atsuoishimoto** [comment]
どちらも反映されてないようですね…

**Comment by artakase** [comment]
サイトに反映されていることを確認しました。
