### ISSUE TITLE
dataclasses のドキュメント中で、マークアップに使っている `` が紙面に表示されている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#890]
# 概要

codeのマークアップに使っている2連バッククォートがページ上に表示されています。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/dataclasses.html#dataclasses.dataclass

# 問題の詳細

```
unsafe_hash: (デフォルトの)``False`` の場合、 eq と frozen がどう設定されているかに従って __hash__() メソッドが生成されます。
```

英語では `False` が code 扱いになっています
https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass
```
unsafe_hash: If False (the default), a __hash__() method is generated according to how eq and frozen are set.
```

# 修正案

) の後に半角スペースを入れると、マークアップがパースされるようになると思います

```
unsafe_hash: (デフォルトの) ``False`` の場合、 eq と frozen がどう設定されているかに従って __hash__() メソッドが生成されます。
```

**Comment by osamu0329nakamura** [comment]
3.9 と newest ブランチはスペースが挿入済みであることを確認しました。
3.7、3.8のドキュメントにスペースを挿入しました。
Web上のドキュメントへの反映はビルド待ちです。

**Comment by atsuoishimoto** [comment]
反映を確認しましたのでcloseします
