### ISSUE TITLE
「組み込みの sort() 関数」との typo

### ISSUE THREAD

**Issue by muranamihdk** [python-doc-ja/python-doc-ja#891]
# 概要
「sort() 関数」は「sorted() 関数」のtypoと思われる。

# 問題のある箇所 (URLで指定すること)
> 組み込みの sort() 関数は安定なことが保証されています。

https://docs.python.org/ja/3/library/functions.html#sorted

# 問題の詳細
- 組み込み関数に sort() 関数は存在しない
- 原文は sorted() となっている
> The built-in sorted() function is guaranteed to be stable.

https://docs.python.org/3/library/functions.html#sorted

# 修正案
> 組み込みの sorted() 関数は安定なことが保証されています。

**Comment by ymyzk** [comment]
提案の通りに修正しました．また，原文で `` :func:`sorted` `` となっているところが  `` :meth:`sort` `` となっていたため， `meth` から `func` への修正も行なっています．次回のビルドで反映されます．

**Comment by muranamihdk** [comment]
ありがとうございました。
