### ISSUE TITLE
x and y, x or y の評価の説明が曖昧なところがある

### ISSUE THREAD

**Issue by cocoatomo** [python-doc-ja/python-doc-ja#893]
# 概要

x and y, x or y の評価の説明に2の意味で取れるところがあり混乱させる

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/expressions.html#boolean-operations

発見元はこのtweet
https://twitter.com/oppaoppa/status/1439535500692373507

# 問題の詳細

> y の値を評価し

は

> y を評価した値を評価し

とも読めて、何故か評価を2回するように取れる

# 修正案

> y の値を評価し、その結果を返します。

を

> y を評価した結果値を返します。

に直す。

**Comment by atsuoishimoto** [comment]
修正案で変更しました
