### ISSUE TITLE
`distutils`が`distuils`になってる箇所がある

### ISSUE THREAD

**Issue by takesi0627** [python-doc-ja/python-doc-ja#894]
# 概要
`distutils`が`distuils`になってる箇所がある

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/distutils/setupscript.html#writing-the-setup-script

# 問題の詳細
> 上の 簡単な例 ... 開発者が `distuils` に対して与える ...

この文の`distuils`は`distutils`の誤植かと思われます。

# 修正案
> 上の 簡単な例 ... 開発者が `distuils` に対して与える ...

を
> 上の 簡単な例 ... 開発者が `distutils` に対して与える ...

に修正します。

**Comment by atsuoishimoto** [comment]
ありがとうございます。修正しました。
