### ISSUE TITLE
ファクトリ関数デ作成したりできます

### ISSUE THREAD

**Issue by hiwane** [python-doc-ja/python-doc-ja#895]
# 概要

`named tuple` の説明部で、「ファクトリ関数デ作成したりできます」

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/glossary.html

# 問題の詳細

タイポ

# 修正案

そのようなクラスは手動で書いたり、 `collections.namedtuple()` ファクトリ関数**で**作成したりできます。

**Comment by bsh-git** [comment]
7月に #887 として報告しました。  修正したとコメントがありましたが、未だに反映されていません。

**Comment by hiwane** [comment]
重複でしたか、申し訳ありません。修正されているそうなので、閉じます。
