### ISSUE TITLE
readlines の hint について翻訳の提案

### ISSUE THREAD

**Issue by Khromium** [python-doc-ja/python-doc-ja#896]
# 概要
> もし読み込んだすべての行のサイズ (バイト数、もしくは文字数) が hint の値を超えた場合、読み込みをそこで終了します。

読み込み終了部分についての定義を厳密にした方がより優しいと思いました。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/io.html?highlight=readlines#io.IOBase.readlines  

# 問題の詳細
https://docs.python.org/3/library/io.html?highlight=readlines#io.IOBase.readlines
> no more lines will be read if the total size (in bytes/characters) of all lines so far exceeds hint.

日本語の文では、`hintのバイト数、もしくは文字数` の直後で読み込みが終了するようにも読み取れます。  
そのため、`no more lines` に相当する日本語訳があった方が良いと思いました。  

# 修正案
「もし読み込んだすべての行のサイズ (バイト数、もしくは文字数) が hint の値を超えた場合、」のあとの訳の案です。  
- 「それ以上の行は読み込まれません。」  
- 「読み込みをその行で終了します。」

**Comment by atsuoishimoto** [comment]
ありがとうございます。
「それ以上の行は読み込まれません。」に修正しました。
