### ISSUE TITLE
unittest.mock.Mockのwraps引数の訳の修正提案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#897]
# 概要

`unittest.mock.Mock`の`wraps`引数の訳に誤りがあると思われます

>wraps: ラップするモックオブジェクトを指定します。 

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/unittest.mock.html#unittest.mock.Mock

# 問題の詳細

原文
https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock
>wraps: Item for the mock object to wrap.

「モックオブジェクトがラップするItem」と読みました。

wrapsにはモックオブジェクトは指定しないことが多いと考えます（サンプルコード参照）
そのため、「ラップするモックオブジェクト」という訳は誤りと考えています。

## サンプルコード

参考: https://stackoverflow.com/a/43065411

```python
from unittest.mock import patch


class Foo:
    def method1(self, x, y):
        return x + y + 1

    def method2(self, z):
        return self.method1(z, z + 1)


foo = Foo()
# wrapsにモックオブジェクトではなく、foo.method1（インスタンスのメソッド）を指定
with patch.object(foo, "method1", wraps=foo.method1) as wrapped_method1:
    print(foo.method2(2))  # 6 (モックオブジェクトwrapped_method1の呼び出しでfoo.method1が呼ばれるため、値が返る)
    wrapped_method1.assert_called_once_with(2, 3)  # wrapped_method1はモックオブジェクトなので、呼び出しを検証できる
```

# 修正案

「wraps: モックオブジェクトがラップするものを指定します。」

（itemの訳し方が難しいと感じています。itemはドキュメント全体での訳し方に合わせたいと思っています）

**Comment by atsuoishimoto** [comment]
「ラップするものを指定します。」というのもちょっとニュアンスがわかりにくい感じがするので、

「wraps: 指定したオブジェクトでラップします。」

はどうでしょう？

**Comment by artakase** [comment]
ありがとうございます。

この item という単語に当てるべき具体的な訳語が思いつかなかったので、
「wraps: このモックオブジェクトがラップするものです。」と訳しておきました。
