### ISSUE TITLE
argparse ライブラリの説明文に不要なスペースと typo が存在する

### ISSUE THREAD

**Issue by Doarakko** [python-doc-ja/python-doc-ja#898]
# 概要

argparse ライブラリの `ArgumentParser.add_mutually_exclusive_group(required=False)` の説明文で、タイポと不要なスペースがある

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/argparse.html#mutual-exclusion

# 問題の詳細

> その相互排他引数のどれか 1つを選ぶことが要求さます

- `どれか 1つを`
  - `1` の前に余分なスペースがある
- `要求さます`  

# 修正案

> その相互排他引数のどれか1つを選ぶことが要求されます

**Comment by atsuoishimoto** [comment]
ありがとうございます。修正しました。
