### ISSUE TITLE
dict.popメソッドの日本語訳のtypo

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#899]
# 概要

`dict.pop`メソッドの日本語訳のtypoに気づきました

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/stdtypes.html#dict.pop

# 問題の詳細

>default が与えらず、

英語
https://docs.python.org/3/library/stdtypes.html#dict.pop
>If default is not given

# 修正案

「default が与えられず、」

**Comment by atsuoishimoto** [comment]
ありがとうございます。修正しました。
