### ISSUE TITLE
search() の説明文に「文字列の操作」とあるが間違い

### ISSUE THREAD

**Issue by shoheichura** [python-doc-ja/python-doc-ja#900]
# 概要
search() の説明文に「文字列の操作」とあるが間違い

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/howto/regex.html#performing-matches

# 問題の詳細
英語では「Scan through a string, （省略）」となっているため「文字列を操作し」ではなく「文字列を前から見ていき」や「文字列を先頭からスキャンし」などが正しい。

# 修正案
修正前：文字列を操作して、正規表現がどこにマッチするか調べます。
修正後：文字列を先頭からスキャンして、正規表現がどこにマッチするか調べます。

**Comment by atsuoishimoto** [comment]
ご指摘ありがとうございます。

ここでは scan は「走査」と訳されてますので、どうも走査->操作の変換ミスっぽいですね。この箇所も「文字列を走査して」に変更します。
