### ISSUE TITLE
collections.Counterのドキュメントにて、dictへのリンク切れ

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#901]
# 概要

dictへのリンクが切れている箇所を見つけました

>バージョン 3.7 で変更: Counter は class:dict のサブクラスとして要素の挿入順を維持する機能を継承しました。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/collections.html#collections.Counter

# 問題の詳細

概要で引用した箇所ですが、「class:dict」は英語版ではdictへのリンク https://docs.python.org/3/library/stdtypes.html#dict です

>Changed in version 3.7: As a dict subclass, Counter Inherited the capability to remember insertion order.

https://docs.python.org/3/library/collections.html#collections.Counter から確認できます

# 修正案

英語版同様にdictへのリンクとするのがよいと考えます。

英語版ドキュメントのソースを見たところ、以下のようになっていました。

```
.. versionchanged:: 3.7 As a :class:`dict` subclass, :class:`Counter`
   Inherited the capability to remember insertion order.
```

https://github.com/python/cpython/blob/31ff96712e8f89ac1056c2da880b44650002219f/Doc/library/collections.rst#L273

以下の部分（classロールのマークアップ）が壊れているのではないかと思います。
マークアップを修正すればこの事象は直りそうに思います。

```
:class:`dict`
```

**Comment by souma987** [comment]
ご指摘ありがとうございます。
修正しましたので、数日以内に反映されると思います。

**Comment by artakase** [comment]
反映されていることを確認しました。
