### ISSUE TITLE
Python言語リファレンス > 代入文のtypo

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#902]
# 概要

「ターゲットリストは、丸括弧や角括弧で囲まれていてもよく、それに対するオブジェクトの代入は、以下のように再帰的に定義されています。」に続く箇条書きにtypoを見つけました。

>オブジェクトはイテラブルで、少なくともターゲットリストのターゲットの数よりも一つ少ない要素を持たなければはなりません。

「持たなければはなりません」がtypoです

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/reference/simple_stmts.html#assignment-statements

# 問題の詳細

（概要を参照ください）

# 修正案

該当するtypoを修正します（「は」を削除）

`オブジェクトはイテラブルで、少なくともターゲットリストのターゲットの数よりも一つ少ない要素を持たなければなりません。`

**Comment by atsuoishimoto** [comment]
ありがとうございます。
修正しました。
