### ISSUE TITLE
Python言語リファレンス > 代入文の「結果オブジェクト」という訳の代案提案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#903]
# 概要

以下の訳の「得られた単一の結果オブジェクト」が少し気になりました。
>得られた単一の結果オブジェクトをターゲット (target) のリストに対して左から右へと代入してゆきます。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/reference/simple_stmts.html#assignment-statements

# 問題の詳細

英語：https://docs.python.org/3/reference/simple_stmts.html#assignment-statements
>assigns the single resulting object to each of the target lists, from left to right.

「the single resulting object」を「得られた単一の結果オブジェクト」と訳しています。

気になったのは「結果オブジェクト」です。
初見時は「結果オブジェクト」という文法用語があるのかなと思いました（英語を見て、なさそうと思いました）

resultingは「結果として生じる」という意味なので、これを踏まえて提案します

# 修正案

1. 結果として得られた単一のオブジェクト（をターゲット (target) のリストに対して左から右へと代入してゆきます。）
2. 得られた単一のオブジェクト（をターゲット (target) のリストに対して左から右へと代入してゆきます。）

「結果オブジェクト」という今の訳語はミスリーディングと思ったので、少なくとも2案のように「結果」を削除したほうがいいと考えます

**Comment by atsuoishimoto** [comment]
ありがとうございます。
「結果オブジェクト」は意味不明ですね

ここの 「single」は結果として得たオブジェクトそれぞれを、ぐらいの感じだと思いますので、

得られた単一の結果オブジェクトを… 
→
得られたそれぞれのオブジェクトを…

としようと思います
