### ISSUE TITLE
disモジュールのドキュメントに用語集「バイトコード」へのリンク切れがある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#904]
# 概要

冒頭の一文

>dis モジュールは CPython バイトコード bytecode を逆アセンブルすることでバイトコードの解析をサポートします。

「バイトコード bytecode」が英語と対応しません

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/dis.html#module-dis

# 問題の詳細

英語
https://docs.python.org/3/library/dis.html#module-dis
>The dis module supports the analysis of CPython [bytecode](https://docs.python.org/3/glossary.html#term-bytecode) by disassembling it.

英語と対応しないの詳細

1. 「バイトコード bytecode」は同じ語の重複（bytecodeが不要と考えます）
2. 用語集「バイトコード」 https://docs.python.org/ja/3/glossary.html#term-bytecode へのリンクになっていない

# 修正案

dis モジュールは CPython [バイトコード](https://docs.python.org/ja/3/glossary.html#term-bytecode) を逆アセンブルすることでバイトコードの解析をサポートします。

* 重複していたbytecodeを削除しました
* 初出の「バイトコード」を用語集日本語版へのリンクにしています

**Comment by artakase** [comment]
報告ありがとうございます。取り掛かります。

**Comment by artakase** [comment]
修正が完了しました。
