### ISSUE TITLE
zlib.crc32() のデフォルト値表記が誤り

### ISSUE THREAD

**Issue by 1024kibits** [python-doc-ja/python-doc-ja#905]
# 概要
zlib.crc32() のデフォルト値表記が誤り
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/zlib.html#zlib.crc32
# 問題の詳細
zlib.crc32() の説明にある、
「与えられていない場合、デフォルト値の **_1_** が使われます。」
との表記ですが、正しいデフォルト値は「0」です。
英語版の表記も実挙動も確認しましたが、「0」で間違いないです。

zlib.adler32() の説明文を流用したために発生したものと思われます。(adler32 のデフォルト値は「１」で正しい)

この関数は、以下のような使い方が常套手段となるので、
ユーザーがドキュメントを参照して自分のコードに書く可能性が高い値かと思います。
```python
c = 0 # デフォルト値で初期化
while b := read(CHUNK_SIZE):
    c = zlib.crc32(b, c)
```

# 修正案
「与えられていない場合、デフォルト値の **_0_** が使われます。」

**Comment by atsuoishimoto** [comment]
ありがとうございます。修正しました。
