### ISSUE TITLE
sys.exitのドキュメントのtypo: オブェクト

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#906]
# 概要
`sys.exit`のドキュメントに「オブェクト」というtypoを見つけました

>それ以外の型のオブジェクトを指定すると、そのオブェクトが stderr に出力され、

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/sys.html#sys.exit

# 問題の詳細

「オブェクト」は「オブジェクト」のtypoと思われます

# 修正案

それ以外の型のオブジェクトを指定すると、そのオブジェクトが stderr に出力され、

**Comment by atsuoishimoto** [comment]
ありがとうございます。修正しました。
