### ISSUE TITLE
ast.dump の説明文の誤字

### ISSUE THREAD

**Issue by knsh14** [python-doc-ja/python-doc-ja#907]
# 概要
ast.dump の説明に誤字があります。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/ast.html#ast.dump

# 問題の詳細
「欲しければ」が「ほ欲しければ」になっています。

# 修正案
正しくは「これが欲しければ、 include_attributes をtrueにセットすることができます。」であるが適切だと思います。
更に日本語に意訳すると、「これが必要であれば、include_attributes をtrueにすると表示できます。」が良さそうです。

**Comment by ymyzk** [comment]
報告ありがとうございます。修正案の通りに修正しました、次回以降のビルドで反映されます。
