### ISSUE TITLE
デザインと歴史 FAQ の脱字: C語

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#908]
# 概要

>C語では中括弧の置き方についてさまざまな流儀があります。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/faq/design.html#why-does-python-use-indentation-for-grouping-of-statements

# 問題の詳細

英語
https://docs.python.org/3/faq/design.html#why-does-python-use-indentation-for-grouping-of-statements
> In C there are many different ways to place the braces.

# 修正案

1. この質問への回答では「Cのプログラマ」「Cプログラマ」と出てくるので統一して
「Cでは中括弧の置き方についてさまざまな流儀があります。」

2. (次点の案) デザインと歴史 FAQの他の箇所では「C 言語」（原語はC）
「C 言語では中括弧の置き方についてさまざまな流儀があります。」
ref: https://docs.python.org/ja/3/faq/design.html#why-are-floating-point-calculations-so-inaccurate

**Comment by atsuoishimoto** [comment]
ご指摘ありがとうございます。
いつの間にか修正済みなようなのでCloseします
