### ISSUE TITLE
デザインと歴史 FAQ: マークアップに使う``がインデントの質問への回答の中に表示されている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#909]
# 概要

```
条件式が真のとき、``x++``行のみが実行されます。(略) 経験豊富なCプログラマでさえ、``x > y``なのに``y``がデクリメントされるのはなぜだろうと、このコードをしばらく凝視することがあります。
```

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/faq/design.html#why-does-python-use-indentation-for-grouping-of-statements

# 問題の詳細

ReSTのコード片のマークアップに使う2連バッククォートがビルドされたドキュメントに現れています。
英語版では、2連バッククォートは現れていません。
https://docs.python.org/3/faq/design.html#why-does-python-use-indentation-for-grouping-of-statements
>Only the x++ statement is executed if the condition is true, (...). Even experienced C programmers will sometimes stare at it a long time wondering as to why y is being decremented even for x > y.

# 修正案

2連バッククォートで囲んだ部分が始まる前と終わった後に、半角スペースを1つ入れると解決しそうに思います

```
条件式が真のとき、 ``x++`` 行のみが実行されます。(略) 経験豊富なCプログラマでさえ、 ``x > y`` なのに ``y`` がデクリメントされるのはなぜだろうと、このコードをしばらく凝視することがあります。
```

例えば以下は

- 「に」の後（＝2連バッククォートで囲んだ部分が始まる前）に半角スペースを入れ
- 「が」の前（＝2連バッククォートで囲んだ部分が終わった後）にも半角スペースを入れています

```
なのに ``y`` が
```

**Comment by atsuoishimoto** [comment]
ありがとうございます。

修正済みなようなのでCloseします。
