### ISSUE TITLE
デザインと歴史 FAQ: マークアップに使う``がgotoの質問への回答の中に表示されている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#910]
# 概要

```
Pythonだと、分岐には if``節及び ``or ・ and ・ if-else 式を使います。
```

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/faq/design.html#why-is-there-no-goto

# 問題の詳細

ReSTのコード片のマークアップに使う2連バッククォートがビルドされたドキュメントに現れています。
英語版では、2連バッククォートは現れていません。
https://docs.python.org/3/faq/design.html#why-is-there-no-goto
>in Python, with if statements and or, and, and if-else expressions

# 修正案

ReSTのマークアップについて、以下のように、2連バッククォートで囲んだ部分が始まる前と終わった後に、半角スペースを1つずつ入れると解決しそうに思います

```
Pythonだと、分岐には ``if`` 節及び ``or`` ・ ``and`` ・ ``if-else`` 式を使います。
```

「節及び」の前後に半角スペースを入れています

**Comment by atsuoishimoto** [comment]
ありがとうございます。
修正済みなようなので反映を待ってCloseします。
