### ISSUE TITLE
訳語の指摘 (Twitterにあった内容のうのissue)

### ISSUE THREAD

**Issue by cocoatomo** [python-doc-ja/python-doc-ja#911]
# 概要
訳語の指摘

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/pickle.html

# 問題の詳細
より良い訳語がある?

# 修正案
"serializing" → 「シリアライズ」
"serialization" → 「シリアズ化」

ref. https://twitter.com/seigo2018/status/1490997414756745217

**Comment by atsuoishimoto** [comment]
Javaの翻訳ドキュメントとかも「直列化」だし、そのままでも良いんじゃないかって気もする

**Comment by atsuoishimoto** [comment]
Duplicate of #912
