### ISSUE TITLE
PYTHONSTARTUP変数のドキュメントの誤訳

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#913]
# 概要

>このファイル内のプロンプト [`sys.ps1`](https://docs.python.org/ja/3/library/sys.html#sys.ps1) や [`sys.ps2`](https://docs.python.org/ja/3/library/sys.html#sys.ps2)、ならびにフック [`sys.__interactivehook__`](https://docs.python.org/ja/3/library/sys.html#sys.__interactivehook__) を変更することも出来ます。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/using/cmdline.html#envvar-PYTHONSTARTUP

# 問題の詳細

PYTHONSTARTUPに指定したファイルで`sys.ps1`に文字列を代入すると、起動した**インタプリタのプロンプトが変わります**。
動作例[1]：https://scrapbox.io/nikkie-memos/PYTHONSTARTUP%E3%81%A7%E3%83%97%E3%83%AD%E3%83%B3%E3%83%97%E3%83%88%E3%82%92%E5%A4%89%E3%81%88%E3%82%8B%E4%BE%8B
PYTHONSTARTUPに指定した"ファイル内のプロンプトを変える"という今の訳は、上記の動作例を説明できておらず、読者の誤解を招いてしまうと考えます。

原文
https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSTARTUP
>You can also change the prompts [`sys.ps1`](https://docs.python.org/3/library/sys.html#sys.ps1) and [`sys.ps2`](https://docs.python.org/3/library/sys.html#sys.ps2) and the hook [`sys.__interactivehook__`](https://docs.python.org/3/library/sys.html#sys.__interactivehook__) in this file.

# 修正案

>このファイルの中で、プロンプト [`sys.ps1`](https://docs.python.org/ja/3/library/sys.html#sys.ps1) や [`sys.ps2`](https://docs.python.org/ja/3/library/sys.html#sys.ps2)、ならびにフック [`sys.__interactivehook__`](https://docs.python.org/ja/3/library/sys.html#sys.__interactivehook__) を変更することも出来ます。

差分は「in this file」の訳です。
「このファイル内の」→「このファイルの中で、」

[1]で示しているように、`sys.ps1`に文字列を代入して、*対話モードのプロンプトが変えられる*ということが現状よりも伝わると考えます。

nitsとして、Issueで指摘した以外の点ですが、以下のように訳すと読みやすいと思います
（「〇〇することができる」はtextlintといったツールでも指摘される点ですね）

- を変更することも出来ます → も変えられます

**Comment by atsuoishimoto** [comment]
ありがとうございます。

「このファイルの中では、このファイルの中で、プロンプト sys.ps1 や sys.ps2、ならびにフック sys.__interactivehook__ も変更できます。」としました。
