### ISSUE TITLE
ArgumentParser.convert_arg_line_to_args の訳をよりわかりやすくする提案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#914]
# 概要

>このメソッドをオーバーライドすると便利なこととして、スペースで区切られた単語を 1 つの引数として扱えます。

実装例をよりうまく説明できそうな言い回しがありそうに思ったのでIssueを書くことにしました。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args

# 問題の詳細

ここの例のコードは、ファイルから引数を読み込む場合、`-f bar`という行があったら、`-f`と`bar`と2つの引数が指定されたとして扱える(A)ことを示していると理解しました。

`prefix_chars`引数のドキュメントによると、「ファイルから読み込まれる引数は、デフォルトでは1行に1つ」[1]なので、`-f bar`という行はデフォルトでは`-f bar`という1つの引数です(B)。
[1]: https://docs.python.org/ja/3/library/argparse.html#fromfile-prefix-chars
この動きを変える方法を例で説明しているという理解です。

「スペースで区切られた単語を 1 つの引数として扱えます。」という今の訳ですと、(A)なのか(B)なのかが、例のコードを見ないとはっきりしないように思われます。

英語を確認するとeach space-separated word（スペースで区切られた1つ1つの単語）をan argument（1つの引数）として扱うということなので、(A)であることが分かりやすいです
https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.convert_arg_line_to_args
>A useful override of this method is one that treats each space-separated word as an argument.

# 修正案

案1
このメソッドをオーバーライドすると便利なこととして、スペースで区切られた単語1つ1つをそれぞれ引数として扱えます。

案2（1よりも積極的に言葉を補いました）
このメソッドをオーバーライドすると便利なこととして、スペースで区切られた行の単語1つ1つを別々の引数として扱えます。

**Comment by atsuoishimoto** [comment]
ありがとうございます。
案2で修正しました。
