### ISSUE TITLE
typo s/デコレーされて/デコレートされて/ in https://docs.python.org/ja/3/library/unittest.html#unittest.TestCase.tearDownClass

### ISSUE THREAD

**Issue by MItsutoshiNAKANO** [python-doc-ja/python-doc-ja#916]
# 概要

該当箇所1か所にtypoがあります。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/unittest.html#unittest.TestCase.tearDownClass

# 問題の詳細

s/デコレーされていなければなりません:/デコレートされていなければなりません:/

# 修正案

s/デコレーされていなければなりません:/デコレートされていなければなりません:/

**Comment by atsuoishimoto** [comment]
ありがとうございます
修正しました。
