### ISSUE TITLE
「2. 拡張の型の定義: チュートリアル」内における漢字の変換ミス

### ISSUE THREAD

**Issue by mirumirumi** [python-doc-ja/python-doc-ja#918]
# 概要
漢字の変換ミス（誤字）です。
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3.7/extending/newtypes_tutorial.html
上記 URL 「2. 拡張の型の定義: チュートリアル」ページ、項目「2.1. 基本的なこと」での初回のコードブロックの次の行、「**重い**ます」ではなく「**思い**ます」です。

# 問題の詳細
上記の通りです。
# 修正案
上記の通りです。

**Comment by atsuoishimoto** [comment]
ありがとうございます。
最新版では修正済みです。
