### ISSUE TITLE
デバッグをデバグとTypoしている

### ISSUE THREAD

**Issue by ghost** [python-doc-ja/python-doc-ja#919]
# 概要

[関数型プログラミング HOWTO>はじめに>デバグやテストの簡単さ](https://docs.python.org/ja/3/howto/functional.html#ease-of-debugging-and-testing)
において、デバッグがデバグと表記されている(他の部分は大丈夫)

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/howto/functional.html#ease-of-debugging-and-testing
# 問題の詳細
Typoしている部分

>デバグやテストの簡単さ[¶](https://docs.python.org/ja/3/howto/functional.html#ease-of-debugging-and-testing)
>テストやデバグも関数型プログラムなら簡単です。
>
>関数が一般的に小さくて明確に意味付けされているので、デバグ方法は単純です。
# 修正案
デバッグやテストの簡単さ[¶](https://docs.python.org/ja/3/howto/functional.html#ease-of-debugging-and-testing)
テストやデバッグも関数型プログラムなら簡単です。

関数が一般的に小さくて明確に意味付けされているので、デバッグ方法は単純です。

**Comment by atsuoishimoto** [comment]
ありがとうございます。
修正しました。
