### ISSUE TITLE
s/でふぉる/デフォルト/

### ISSUE THREAD

**Issue by raven38** [python-doc-ja/python-doc-ja#920]
# 概要
デフォルトのtypo
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/readline.html#readline.append_history_file

Python 3.5以降のドキュメントは同様，例えば
https://docs.python.org/ja/3.5/library/readline.html#readline.append_history_file
https://docs.python.org/ja/3.8/library/readline.html#readline.append_history_file
https://docs.python.org/ja/dev/library/readline.html#readline.append_history_file

# 問題の詳細

> 履歴の最後の nelements 項目をファイルに追加します。でふぉるのファイル名は ~/.history です。ファイルは存在していなくてはなりません。

# 修正案
> 履歴の最後の nelements 項目をファイルに追加します。デフォルトのファイル名は ~/.history です。ファイルは存在していなくてはなりません。

**Comment by atsuoishimoto** [comment]
ありがとうございます。
修正しました。
