### ISSUE TITLE
Magic Mock のタイポ

### ISSUE THREAD

**Issue by himkt** [python-doc-ja/python-doc-ja#921]
# 概要

magic mock の説明に一部 "magick mock" というタイポが含まれている。

# 問題のある箇所 (URLで指定すること)

- https://docs.python.org/ja/3.12/library/unittest.mock.html

# 問題の詳細

https://github.com/python/python-docs-ja/compare/3.10...himkt:fix-typo

# 修正案

None

**Comment by atsuoishimoto** [comment]
ありがとうございます。
修正しました。
