### ISSUE TITLE
「等価」の誤変換

### ISSUE THREAD

**Issue by nakashima-hikaru** [python-doc-ja/python-doc-ja#922]
# 概要
軽微な誤変換

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/abc.html
@abc.abstractmethodの説明

# 問題の詳細
一文「例えば、 Python 組み込みの [property](https://docs.python.org/ja/3/library/functions.html#property) は、次のコードと**透過**に振る舞います:」の「透過」は「等価」の誤変換

# 修正案
透過 -> 等価

**Comment by atsuoishimoto** [comment]
ありがとうございます。
修正しました。
