### ISSUE TITLE
`datetime` の「技術詳細 9.」について、「後ろに続ける 0」の原文は「leading zero」であり、意味が反転している。

### ISSUE THREAD

**Issue by 243f6a8885a308d313198a2e037** [python-doc-ja/python-doc-ja#925]
# 概要

`datetime` の「技術詳細 9.」について、「後ろに続ける 0」の原文は「leading zero」であり、意味が反転している。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/datetime.html#technical-detail の 9.

> strptime() メソッドと共に使われたときは、書式 %d, %m, %H, %I, %M, %S, %J, %U, %W, %V の **後ろに続ける 0** は任意です。 書式 %y では **後ろに続ける 0** は必須です。

https://github.com/python/python-docs-ja/blob/3.10/library/datetime.po#L3993-L4002

# 問題の詳細

「後ろに続ける 0」の原文は「leading zero」であり、意味が反転している。

# 修正案

直訳するなら「先頭のゼロ」などか。

なお、 `%y` については2桁の数値について言及しているので「a leading zero」は1桁分しかないことを踏まえると、「10の位の」などと意訳できるならばより意味が伝わりやすいと考える。（ひとつめの文については `%J` のみ最大3桁であるので、10の位と説明するのは不正確となる。）

**Comment by artakase** [comment]
報告ありがとうございます。
検索したところ、「先行ゼロ」と言う訳語があるようなのでそれを採用しました。
