### ISSUE TITLE
リンクの間違い

### ISSUE THREAD

**Issue by syquray** [python-doc-ja/python-doc-ja#926]
# 概要
GitHub へのリンクが間違っています。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/faq/general.html#how-do-i-obtain-a-copy-of-the-python-source
の上から 2 行目

# 問題の詳細
上の箇所の、GitHub の CPython リポジトリへのリンクが間違っています。

原文は
> The latest Python source distribution is always available from python.org, at https://www.python.org/downloads/. The latest development sources can be obtained at **https://github.com/python/cpython/**.

ですが、訳文は

> 最新の Python ソースは python.org (https://www.python.org/downloads/) からいつでも手に入れることができます。最新の開発版ソースは **https://github.python.org/cpython** にアクセスして手に入れることができます。

となっていて、リンクにアクセスできません。
(問題の箇所を太字にしています)

# 修正案
`https://github.python.org/cpython`
↓
`https://github.com/python/cpython`

**Comment by souma987** [comment]
ご指摘ありがとうございます。
修正しました。Webサイトにも反映されています。

**Comment by pscore23** [comment]
修正ありがとうございます。
