### ISSUE TITLE
データクラスのドキュメントに、リンクになっていない「:const:'KW_ONLY'」がある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#927]
ドキュメントを翻訳いただきありがとうございます。

# 概要

「:const:'KW_ONLY'」と表示され、https://docs.python.org/ja/3/library/dataclasses.html#dataclasses.KW_ONLY へのリンクになっていない

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/dataclasses.html#dataclasses.KW_ONLY

# 問題の詳細

「:const:'KW_ONLY'」という記載が4箇所あります：

>:const:'KW_ONLY' の型の擬似フィールドのあとのすべてのフィールドはキーワード専用フィールドとなります。

>:const:'KW_ONLY' の型の擬似フィールド自体は無視されることに注意してください。

>:const:'KW_ONLY' フィールドの名前としては _ が慣習的に使用されます。

>1つのデータクラスの中に、2つ以上の :const:'KW_ONLY' の型のフィールドがあるとエラーになります。

英語版 https://docs.python.org/3/library/dataclasses.html#dataclasses.KW_ONLY を見ると、
「:const:'KW_ONLY'」に相当する箇所は https://docs.python.org/3/library/dataclasses.html#dataclasses.KW_ONLY へのリンクになっています。

>Any fields after a pseudo-field with the type of [KW_ONLY](https://docs.python.org/3/library/dataclasses.html#dataclasses.KW_ONLY) are marked as keyword-only fields.

日本語のドキュメントでは、constロールがうまく動いていないようです

# 修正案

https://github.dev/python/cpython/blob/c00f2b15d8daf3faaa6b9932a10da719691ec35a/Doc/library/dataclasses.rst#L473 によると

```
:const:`KW_ONLY`
```

となっています。
日本語訳のrstファイルがあるのでしたら `:const:'KW_ONLY'` の**シングルクォートをバッククォートに変える**とconstロールが動くようになるのではないかと思いました

**Comment by souma987** [comment]
ご指摘ありがとうございます。
4箇所すべて修正しました。数日以内に反映されると思います。

**Comment by artakase** [comment]
反映されていることを確認しました。
