### ISSUE TITLE
組み込み関数 aiter のドキュメントでマークアップやロールがそのまま表示されている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#928]
ドキュメントを翻訳いただき、ありがとうございます。

# 概要
組み込み関数 aiter のドキュメントでマークアップやロールがそのまま表示されている

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/functions.html#aiter

# 問題の詳細

あるべきは、英語版 https://docs.python.org/3/library/functions.html#aiter のようにリンクになる状態と考えます。
英語版との違いを挙げます

(1) termロールが機能していない

```
:term:[`](https://docs.python.org/ja/3/library/functions.html#id1)asynchronous iterable[`](https://docs.python.org/ja/3/library/functions.html#id3)から :term:`asynchronous iterator`を返します。
```

(2) コードとしてマークアップできていない

```
[``](https://docs.python.org/ja/3/library/functions.html#id5)x.__aiter__()``を呼び出すのと等価です。
```

(3) funcロールも機能していない

```
なお、:func:[`](https://docs.python.org/ja/3/library/functions.html#id1)iter[`](https://docs.python.org/ja/3/library/functions.html#id3)とは異なり、:func:`aiter`は第二引数を持ちません。
```

(4) 上記3点に関して、バッククォートの部分だけがリンクになっているが、用語集や組み込み関数の該当箇所へのリンクにはなっていない

# 修正案

ロールやマークアップの **前後に半角スペースを入れる** ことで、解消するかもしれません。
日本語でrstを書いていて、ロールやマークアップがそのまま紙面に出てしまう場合、私の経験では半角スペース挿入で解決することが多いです

**Comment by thisishusseinali** [comment]
組み込み関数 aiter のドキュメントでマークアップやロールがそのまま表示されている

**Comment by artakase** [comment]
報告ありがとうございます。修正されました。
