### ISSUE TITLE
翻訳の誤り: 「__init__() と __init__() のどちらを使うべきか」

### ISSUE THREAD

**Issue by 243f6a8885a308d313198a2e037** [python-doc-ja/python-doc-ja#930]
# 概要

翻訳の誤り: 「__init__() と __init__() のどちらを使うべきか」

# 問題のある箇所 (URLで指定すること)

- https://docs.python.org/ja/3/library/enum.html#when-to-use-new-vs-init
  - 「__init__() と __init__() のどちらを使うべきか」

# 問題の詳細

- 原文: "When to use __new__() vs. __init__()"
  - cf. https://docs.python.org/3.10/library/enum.html#when-to-use-new-vs-init

# 修正案

- 「__new__() と __init__() のどちらを使うべきか」

**Comment by artakase** [comment]
報告ありがとうございます。
修正しました。以下のURLに反映されます。
https://docs.python.org/ja/3.10/library/enum.html#when-to-use-new-vs-init

**Comment by artakase** [comment]
最新版ではドキュメントが移動しており、こちらも合わせて反映待ちです。
https://docs.python.org/ja/3/howto/enum.html#when-to-use-new-vs-init
