### ISSUE TITLE
enum: 番号付けの値が同一であることの確認

### ISSUE THREAD

**Issue by 243f6a8885a308d313198a2e037** [python-doc-ja/python-doc-ja#931]
# 概要

- 「番号付けの値が同一であることの確認」

# 問題のある箇所 (URLで指定すること)

- https://docs.python.org/ja/3/library/enum.html#ensuring-unique-enumeration-values

# 問題の詳細

- 「同一な番号付けの値がないことの確認」ならまだわかるが、原文では意味が通らない。

# 修正案

- 「番号付けの値が **一意** であることの確認」

**Comment by artakase** [comment]
報告ありがとうございます。
以下の二つのURLに対応する訳文を更新しました。
最新版
https://docs.python.org/ja/3/howto/enum.html#ensuring-unique-enumeration-values
3.10
https://docs.python.org/ja/3.10/library/enum.html#ensuring-unique-enumeration-values
