### ISSUE TITLE
組み込み関数 `round()` の typo (ndigists -> ndigits)

### ISSUE THREAD

**Issue by seijinrosen** [python-doc-ja/python-doc-ja#933]
# 概要

組み込み関数 `round()` の説明に typo があります。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/functions.html#round

説明の一行目。

# 問題の詳細

> number の小数部を ndigists 桁に丸めた値を返します。

_ndigists_ ではなく _ndigits_ が正しいと思われます。

なお、同一ページ内に _ndigists_ が登場する箇所は他にありませんでしたので、修正は1箇所のみでOKだと思います。

# 修正案

_ndigists_ -> _ndigits_

> number の小数部を ndigits 桁に丸めた値を返します。

**Comment by artakase** [comment]
報告ありがとうございます。
訳文を修正しました。
