### ISSUE TITLE
「コルーチンとTask」の訳の修正案

### ISSUE THREAD

**Issue by rebunto** [python-doc-ja/python-doc-ja#934]
ドキュメントの翻訳ありがとうございます。いつも大変助かっております。

# 概要
「コルーチンとTask」の説明に誤った訳があるかもしれません。
"A is awaited from B"の訳が「AがBを待機させる」となっていますが、正しくは「AがBに待機される」だと考えております。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/asyncio-task.html#awaitables
# 問題の詳細
該当部分(3箇所)：
1. > Python のコルーチンは awaitable であり、そのため他のコルーチンを待機させられます:
2. > Future オブジェクトが他の awaitable を 待機させている と言うときは、ある場所で Future が解決されるまでコルーチンが待機するということです。
3. > Future オブジェクトはライブラリや asyncio の API で表に出ることもあり、他の awaitable を待機させられます:

[原文](https://docs.python.org/3/library/asyncio-task.html#awaitables)：
1. > Python coroutines are awaitables and therefore can be awaited from other coroutines:
2. > When a Future object is awaited it means that the coroutine will wait until the Future is resolved in some other place.
3. > Future objects, sometimes exposed by libraries and some asyncio APIs, can be awaited:

参考(awaitableの定義が書いてあります)：https://peps.python.org/pep-0492/#await-expression

# 修正案
直訳です：
1.  「Python のコルーチンは awaitable であり、そのため他のコルーチンに待機されることができます:」
2.  「Future オブジェクトが待機される とは、ある場所で Future が解決されるまでコルーチンが待機するということです。」
3.  「Future オブジェクトはライブラリや asyncio の API で表に出ることがあり、待機されることができます:」

ページ内で英語版の"await"を日本語版でもそのまま「await」としている場合がありますが、当該文もそうしていいかもしれません。また、能動態として訳す方法も考えられます。

**Comment by souma987** [comment]
以下のようにTransifex上で修正しました。ウェブ上にいつ反映されるかは私にはわかりません。
1. 「Python のコルーチンは *awaitable* であり、他のコルーチンから待機されることができます::」
2. 「Future オブジェクトが *待機 (await) されている* とは、Future がどこか他の場所で解決されるまでコルーチンが待機するということです。」
3.  「Future オブジェクトはライブラリや asyncio のAPIで外部に提供されることもあり、await （待機）されることができます::」

**Comment by artakase** [comment]
サイトに反映されていることを確認しました。
