### ISSUE TITLE
xml.etree.ElementTreeのドキュメント冒頭の警告のtypo

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#935]
# 概要
xml.etree.ElementTreeのドキュメントの冒頭の警告にtypoを見つけました。
（チュートリアルより前のところにある警告です）

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/xml.etree.elementtree.html#module-xml.etree.ElementTree

# 問題の詳細
>信頼できないデータや認証されていないデータををパースする必要がある場合は

「を」が重複していることに気付きました

# 修正案

「をを」→「を」

```diff
- 信頼できないデータや認証されていないデータををパースする必要がある場合は
+ 信頼できないデータや認証されていないデータをパースする必要がある場合は
```

**Comment by souma987** [comment]
ご指摘ありがとうございます。
元データは修正しましたが、Web上に反映されるのはしばらく先になると思われます。

**Comment by ftnext** [comment]
迅速にご対応いただきありがとうございます。

少し時間をおいてドキュメントを確認し、修正が反映されていたらこのIssueはクローズということですね

**Comment by souma987** [comment]
そうですね。
実はWebの更新がうまくいっていなくて（ページ下の最終更新が8/1になっていることからもわかると思います）、いつになるかはわからないです。

**Comment by souma987** [comment]
docs.python.org/ja でも修正されていることを確認しました。

**Comment by ftnext** [comment]
ご対応・ご確認ありがとうございました。
https://github.com/python-doc-ja/python-doc-ja/issues/935#issuecomment-1345533916 を満たしたのでクローズします
>少し時間をおいてドキュメントを確認し、修正が反映されていたらこのIssueはクローズということですね
