### ISSUE TITLE
StreamReader.readの翻訳

### ISSUE THREAD

**Issue by zakki** [python-doc-ja/python-doc-ja#937]
# 概要
StreamReader.read()の "up to n bytes" がわかりにくい。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/asyncio-stream.html#asyncio.StreamReader.read

# 問題の詳細

> Read up to `n` bytes from the stream.
> n バイト読み込みます。

"up to" 部分がなくreadexactlyと区別できず、nバイト読み込むまで待つように読めます。

# 修正案

"最大 n バイト読み込みます。" 

https://github.com/python/cpython/blob/main/Lib/asyncio/streams.py#L650
コメントの3段落目以降もあったほうが実際の動作はわかりやすいのですが、英語版のasyncio-stream.rstにも含まれていないようです。

**Comment by souma987** [comment]
ご指摘ありがとうございます。確かに **"最大"** nバイトですね。
日本語ドキュメントは翻訳版ですので、英語版にならってソースコードのコメントは載せないでおきます。
もし英語版ドキュメントの方を変えたほうがいいと思うなら、[python/cpython ](https://github.com/python/cpython/issues) のリポジトリにissueを立ててください。

"最大"の方は修正しましたので、数日以内に反映されると思います。

**Comment by souma987** [comment]
反映されていることを確認しました。
