### ISSUE TITLE
データモデルのリファレンス、__call__メソッドの説明のtypo: カンストして

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#938]
# 概要

データモデルのリファレンスの「[3.3.6. 呼び出し可能オブジェクトをエミュレートする](https://docs.python.org/ja/3/reference/datamodel.html#emulating-callable-objects)」
`__call__`メソッドの説明箇所にtypoを見つけました

# 問題のある箇所 (URLで指定すること)

[こちら](https://docs.python.org/ja/3/reference/datamodel.html#object.__call__)です
（`__call__`の後ろのダンダーがリンクにならなかったのでマークアップしています）

# 問題の詳細

>インスタンスがカンストして "呼ばれた" 際に呼び出されます。

カンストして -> **関数として** のtypoと思われます。

[英語](https://docs.python.org/3/reference/datamodel.html#object.__call__)は「as a function」でした
>Called when the instance is “called” as a function

# 修正案

```
インスタンスが関数として "呼ばれた" 際に呼び出されます。
```

**Comment by souma987** [comment]
ご報告ありがとうございます。
確かに typo ですね。修正しましたので、数日以内に反映されると思います。

**Comment by artakase** [comment]
反映されていることを確認しました。
