### ISSUE TITLE
データモデルのリファレンス、__call__メソッドの説明の訳の修正案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#939]
# 概要

データモデルのリファレンスの「[3.3.6. 呼び出し可能オブジェクトをエミュレートする](https://docs.python.org/ja/3/reference/datamodel.html#emulating-callable-objects)」
`__call__`メソッドの説明箇所に訳の誤りと思われる箇所があります

# 問題のある箇所 (URLで指定すること)

[こちら](https://docs.python.org/ja/3/reference/datamodel.html#object.__call__)です
（`__call__`の後ろのダンダーがリンクにならなかったのでマークアップしています）

# 問題の詳細

>このメソッドが `x(arg1, arg2, ...)` 定義されている場合、これは大まかには `type(x).__call__(x, arg1, ...)` に変換されます。

[英語](https://docs.python.org/3/reference/datamodel.html#object.__call__)
>if this method is defined, `x(arg1, arg2, ...)` roughly translates to `type(x).__call__(x, arg1, ...)`.

「このメソッドが `x(arg1, arg2, ...)` 定義されている場合」は「if this method is defined」の訳としては不適切だと思います。

# 修正案

```
このメソッドが定義されている場合、`x(arg1, arg2, ...)`は大まかには `type(x).__call__(x, arg1, ...)` に変換されます。
```

`x(arg1, arg2, ...)`の位置を変えるだけで修正できると思われます

**Comment by souma987** [comment]
ご指摘ありがとうございます。
"カンスト" の typo とあわせて修正しました。数日以内に反映されると思います。

**Comment by artakase** [comment]
反映されていることを確認しました。
