### ISSUE TITLE
組み込み型 イテレータ型のドキュメントでtermロールがそのまま表示されている

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#940]
# 概要

[イテレータ型のドキュメント](https://docs.python.org/ja/3/library/stdtypes.html#iterator-types)にtermロールがそのまま表示されている箇所を見つけました

# 問題のある箇所 (URLで指定すること)

[こちら](https://docs.python.org/ja/3/library/stdtypes.html#container.__iter__)です

# 問題の詳細

>term:iterator オブジェクトを返します。

[英語](https://docs.python.org/3/library/stdtypes.html#container.__iter__)を見ると
>Return an [iterator](https://docs.python.org/3/glossary.html#term-iterator) object.

と、iteratorが用語集へのリンクになっていました。
日本語訳では`term:iterator`と表示されていて、termロールがここだけ機能していないのが問題と考えています

# 修正案

https://github.com/python-doc-ja/python-doc-ja/issues/928 と同様の対応で修正できるのではないかと考えます

**Comment by souma987** [comment]
ご指摘ありがとうございます。
修正しましたので、数日以内に反映されると思います。

**Comment by artakase** [comment]
反映されていることを確認しました。
