### ISSUE TITLE
用語集 iterableの訳の改善提案：sequence意味論は__getitem__メソッドを指すのではないか

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#941]
用語集の翻訳、いつも大変助けられています。ありがとうございます

# 概要

iterableの用語集の翻訳の改善提案です

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/glossary.html#term-iterable

# 問題の詳細
>あるいは [sequence](https://docs.python.org/ja/3/glossary.html#term-sequence) 意味論を実装した `__iter__()` メソッドか `__getitem__()` メソッドを持つ任意のクラスのインスタンスが含まれます。

原文 https://docs.python.org/3/glossary.html#term-iterable
>and objects of any classes you define with an `__iter__()` method or with a `__getitem__()` method that implements [sequence](https://docs.python.org/3/glossary.html#term-sequence) semantics.

今の訳を一度忘れて原文の訳を考えると

- あなたが定義したどんなクラスのオブジェクト
  - `__iter__()`メソッドを持つクラス
  - sequence意味論を実装する`__getitem__()`メソッドを持つクラス

となるのではないかと考えました。
[sequenceの用語集](https://docs.python.org/3/glossary.html#term-sequence)からsequence semanticsとは、`__getitem__()`と`__len__()`の2つのメソッドのこと（semanticsは*プロトコル*のような意味ではないか）と考えています

# 修正案

```
あるいは __iter__() メソッドか sequence 意味論を実装した __getitem__() メソッドを持つ任意のクラスのインスタンスが含まれます。
```

**Comment by souma987** [comment]
ご指摘ありがとうございます。
修正しましたので、数日以内に反映されると思います。

**Comment by artakase** [comment]
反映されていることを確認しました。
