### ISSUE TITLE
「6.1. モジュールについてもうすこし」の節で :keyword: が露出しています

### ISSUE THREAD

**Issue by hideo67** [python-doc-ja/python-doc-ja#942]
# 概要
「6.1. モジュールについてもうすこし」の節で :keyword: が露出しています。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/tutorial/modules.html#more-on-modules

# 問題の詳細

以下は、ブラウザからのコピペで、実際の見た目とは異なります：

> モジュールは他のモジュールをインポートできます。:keyword:[`](https://docs.python.org/ja/3/tutorial/modules.html#id1)import`文はモジュール（さらに言えばスクリプ

というくだりで、「:keyword:」という原稿の中の指令がそのまま表示されてしまっています。また、「`import`」の最初のバックティックだけがクリッカブルになっています。

# 修正案
表記法に従って修正いただければと思います。

よろしくお願いします。

**Comment by artakase** [comment]
報告ありがとうございます。
訳文を修正しました。
