### ISSUE TITLE
「2.3.2. ソフトキーワード」に typo

### ISSUE THREAD

**Issue by suzuki-kei** [python-doc-ja/python-doc-ja#943]
# 概要
「2.3.2. ソフトキーワード」に typo がありました。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/reference/lexical_analysis.html#soft-keywords

# 問題の詳細
「特定のコンテキストのも元でだけ予約される識別子があります。」

# 修正案
「特定のコンテキストの元でだけ予約される識別子があります。」

**Comment by artakase** [comment]
報告ありがとうございます。
訳文を修正しました。
