### ISSUE TITLE
gc --- ガベージコレクタインターフェース に typo: Pyhon

### ISSUE THREAD

**Issue by kousukekikuchi1984** [python-doc-ja/python-doc-ja#948]
# 概要

GC に関するドキュメントに関して Python の表記が typo で Pyhon になっている。

# 問題のある箇所 (URLで指定すること)

- https://github.com/python/python-docs-ja/blob/3.11/library/gc.po#L45
- https://docs.python.org/ja/3/library/gc.html

# 問題の詳細

> 循環ガベージコレクタはPyhonの参照カウントを補うためのものなので、もしプログラム中で循環参照が発生しない事が明らかな場合には検出をする必要はありません。

- 上記の箇所で Pyhon と記載があります。

# 修正案

- Pyhon -> Python

**Comment by artakase** [comment]
ご報告ありがとうございます。
訳文を修正しました。
サイトに反映され次第クローズします。
