### ISSUE TITLE
argparseのドキュメントに見つけた余計な文字

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#949]
# 概要

ドキュメントの翻訳、誠にありがとうございます。

誤って余計な文字が入っているのに気づきました。

>[argparse](https://docs.python.org/ja/3/library/argparse.html#module-argparse) はモジュールは、ユーザーフレンドリーなコマンドラインインターフェースの作成を簡単にします。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/argparse.html#module-argparse

# 問題の詳細

英語も確認しましたが、「argparseモジュールは」とできると思います

https://docs.python.org/3/library/argparse.html#module-argparse
>The [argparse](https://docs.python.org/3/library/argparse.html#module-argparse) module makes it easy to write user-friendly command-line interfaces.

# 修正案

「[argparse](https://docs.python.org/ja/3/library/argparse.html#module-argparse) モジュールは、」

**Comment by artakase** [comment]
ご報告ありがとうございます。
訳文を修正しました。
サイトに反映され次第クローズします。
