### ISSUE TITLE
logging フィルタオブジェクト 中のtypo

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#950]
ドキュメントの翻訳・メンテナンス、誠にありがとうございます

# 概要

loggingモジュールのドキュメントの「[フィルタオブジェクト](https://docs.python.org/ja/3/library/logging.html#filter-objects)」にtypoがありました

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/logging.html#logging.Filter.filter
# 問題の詳細
>no ならばばゼロを、

# 修正案
no ならばゼロを、

**Comment by artakase** [comment]
ご報告ありがとうございます。
訳文を修正しました。
サイトに反映され次第クローズします。
