### ISSUE TITLE
日本語の誤植 (Python チュートリアル - 4.6. match 文)

### ISSUE THREAD

**Issue by watsumi** [python-doc-ja/python-doc-ja#951]
翻訳・メンテナンス作業、誠にありがとうございます。

# 概要
Pythonチュートリアル内の、[4.6. match 文](https://docs.python.org/ja/3/tutorial/controlflow.html#match-statements)において、日本語の誤植と思われる箇所がありました。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/tutorial/controlflow.html#match-statements

# 問題の詳細
> クラスの __match_args__ 特殊属性でによって

# 修正案
クラスの __match_args__ 特殊属性によって

**Comment by artakase** [comment]
ご報告ありがとうございます。
訳文を修正しました。
サイトに反映され次第クローズします。
