### ISSUE TITLE
「上級ロギングチュートリアル」の「ロガー」にて、よりわかりやすくできる訳の提案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#952]
ドキュメントの翻訳、またIssueに対して迅速にご対応いただき、誠にありがとうございます

# 概要
「[上級ロギングチュートリアル](https://docs.python.org/ja/3/howto/logging.html#advanced-logging-tutorial)」の「ロガー」によりわかりやすくできる箇所を見つけました。

>最後の 2 段落を参照してください。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/howto/logging.html#loggers

# 問題の詳細
最後の2段落がどこなのかがパッと分かりませんでした。

英語版を見ると明確でした。
https://docs.python.org/3/howto/logging.html#loggers
>See the last two paragraphs in this section.

# 修正案

1. この節の最後の 2 段落を参照してください。
2. このセクションの最後の 2 段落を参照してください。

Logging HOWTOの中でsectionの訳には「節」「セクション」と揺れがあるので、1と2のどちらでもいいのではないかなと考えています。

## 参考情報

1例目

https://docs.python.org/ja/3/howto/logging.html#changing-the-format-of-displayed-messages
>これは次の節で解説します。

https://docs.python.org/3/howto/logging.html#changing-the-format-of-displayed-messages
>This is described in the next section.

2例目
https://docs.python.org/ja/3/howto/logging.html#next-steps
>以下のセクションを読む必要があります。

>幾つかの節を読み続けることができます。

https://docs.python.org/3/howto/logging.html#next-steps

>you’ll need to invest a little more of your time in reading the following sections.

>You can carry on reading the next few sections,

**Comment by artakase** [comment]
ご報告ありがとうございます。
「この節の最後の 2 段落を参照してください。」と訳しました。
サイトに反映され次第クローズします。
