### ISSUE TITLE
typingのドキュメントでPEPへのリンクが壊れている箇所がある

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#957]
# 概要

冒頭部分
```
仕様は:pep:`484`に記載があります。簡潔な導入は:pep:`483`に記載があります。
```

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/typing.html

# 問題の詳細
英語版を確認するとリンクが有効になっています。

リンクが壊れている箇所は、上で挙げた2つの他にあと4つ、**全部で6つ**見つかりました

https://docs.python.org/ja/3/library/typing.html#typing.LiteralString
```
より詳しくは:pep:675 を参照してください。
```

https://docs.python.org/ja/3/library/typing.html#typing.Self
```
より詳しくは:pep:673 を参照してください。
```

https://docs.python.org/ja/3/library/typing.html#typing.dataclass_transform
```
より詳しくは:pep:681 を参照してください。
```

以上はPython 3.11で追加という共通点があるように思われます。

https://docs.python.org/ja/3/library/typing.html#typing.Protocol
```
詳細については pep:544 を参照してください。
```

# 修正案

reST原稿が見えないので案は浮かびませんが、pepロールが解決できている箇所はあるので、そこと書き方を揃えるのをまず試すことになるのではないかと考えます。

**Comment by souma987** [comment]
冒頭部分については transifex 上で確認したところ、最新版、3.11、3.10 では未翻訳となっていたのでそれぞれ翻訳し、3.9 では不適切なリンクがあったので修正しました。

他の4つの部分に関しては、最新版の翻訳文中の不適切なリンクを修正しました。

数日以内に反映されると思います。

**Comment by ftnext** [comment]
挙げた箇所6点はPEPへのリンクが表示されていました。
ご対応いただきありがとうございました
