### ISSUE TITLE
"row" を 「列」と訳している箇所

### ISSUE THREAD

**Issue by susurri** [python-doc-ja/python-doc-ja#960]
# 概要
"row" を 「列」と訳している箇所がある
# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/csv.html#csv.DictReader
# 問題の詳細
"row" は 「行」と訳すべきところ、「列」になっている箇所が複数ある
# 修正案
"row" は 「行」と訳す

**Comment by souma987** [comment]
ご指摘ありがとうございます。

修正しましたので、数日以内に反映されると思います。すべて修正したつもりですが、抜けている箇所があればまたご指摘ください。

**Comment by souma987** [comment]
反映されていることを確認しました。
