### ISSUE TITLE
`typing.NoReturn` は戻り値を持たない関数を表す型ではない

### ISSUE THREAD

**Issue by vraintanakarei** [python-doc-ja/python-doc-ja#965]
# 概要
Python 3.9 のドキュメントで `typing.NoReturn` について

> 関数が返り値を持たないことを示す特別な型です。

と書かれていますが、厳密には`NoReturn` は戻り値を持たないというよりは**関数から戻らない**ことを示す型です。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3.9/library/typing.html#typing.NoReturn

# 問題の詳細
`typing.NoReturn` は [PEP 484](https://peps.python.org/pep-0484/#the-noreturn-type) で提案されています。

PEP 484 には以下のような記載があり、`NoReturn` は「中で絶対に例外が発生する」「無限ループで脱出しない」「`sys.exit()` で終了する」のように、戻ることがない関数をアノテーションするための型です。

> The typing module provides a special type NoReturn to annotate functions that never return normally. For example, a function that unconditionally raises an exception:

# 修正案
「関数の呼び出し後、戻ることがないことを示す特別な型です。」など。

**Comment by souma987** [comment]
Transifex 上で修正しました。

**Comment by souma987** [comment]
ご提示の Python3.9 のドキュメントには反映されていませんが、[最新版](https://docs.python.org/ja/3/library/typing.html#typing.NoReturn) には反映されていることを確認しました。

**Comment by vraintanakarei** [comment]
@souma987 
ご対応ありがとうございました。
