### ISSUE TITLE
collections.abc内のtypo

### ISSUE THREAD

**Issue by lotadcate** [python-doc-ja/python-doc-ja#968]
# 概要
typo: "および"が"おyび"になっている。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/collections.abc.html

# 問題の詳細
バージョン 3.9 で追加: これらの抽象クラスは [] をサポートするようになりました。ジェネリックエイリアス型 ([Generic Alias Type](https://docs.python.org/ja/3/library/stdtypes.html#types-genericalias)) おyび [PEP 585](https://peps.python.org/pep-0585/) を参照してください。

# 修正案
おyび -> および

**Comment by souma987** [comment]
Transifex 上で修正しました。

**Comment by souma987** [comment]
docs.python.org 上に反映されていることを確認しました。
