### ISSUE TITLE
ダミースレッド (dummy thread)" オブジェクトを作成することができます

### ISSUE THREAD

**Issue by msakai** [python-doc-ja/python-doc-ja#972]
# 概要

Thread オブジェクトに関する説明で、「"ダミースレッド (dummy thread)" オブジェクトを作成できる場合があります」とありますが、これは意図的に作成するものではないので、受け身にして「"ダミースレッド (dummy thread)" オブジェクトが作成される場合があります」としてはいかがでしょうか。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3.13/library/threading.html#thread-objects

> "ダミースレッド (dummy thread)" オブジェクトを作成できる場合があります。ダミースレッドは、 "外来スレッド (alien thread)" に相当するスレッドオブジェクトです。ダミースレッドは、C コードから直接生成されたスレッドのような、 threading モジュールの外で開始された処理スレッドです。

原文:

https://docs.python.org/3.13/library/threading.html#thread-objects

> There is the possibility that “dummy thread objects” are created. These are thread objects corresponding to “alien threads”, which are threads of control started outside the threading module, such as directly from C code.

# 問題の詳細

# 修正案

> "ダミースレッド (dummy thread)" オブジェクトが作成される場合があります。〃

**Comment by souma987** [comment]
Transifex 上で修正しました。

**Comment by souma987** [comment]
docs.python.org 上に反映されていることを確認しました。
