### ISSUE TITLE
イベントループ/サブプロセスの実行の説明における助詞の抜け落ち

### ISSUE THREAD

**Issue by attakei** [python-doc-ja/python-doc-ja#974]
# 概要

`subprocess_exec()`の説明内にある引数に関する説明で、助詞の抜け落ちと思われる記述があります。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/library/asyncio-eventloop.html#asyncio.loop.subprocess_exec

# 問題の詳細

「その他の引数:」の項目内にてそれぞれ下記の文が記載されており、`stdin`の説明のみ「～は」が記述されていませんでした。

- stdin 下記のいずれかをとることができます:
- stdout は下記のいずれかをとることができます:
- stderr は下記のいずれかをとることができます:

原文のほうがどれも *can be any of these* となっているため、おそらく翻訳時における抜け落ちかと思います。

# 修正案

> stdin 下記のいずれかをとることができます:

を

> stdin は下記のいずれかをとることができます:

 に編集する。

**Comment by souma987** [comment]
docs.python.org 上に反映されていることを確認しました。

**Comment by attakei** [comment]
対応ありがとうございました。
