### ISSUE TITLE
チュートリアル「15. 浮動小数点演算、その問題と制限」の誤訳

### ISSUE THREAD

**Issue by shun-yamazaki** [python-doc-ja/python-doc-ja#980]
# 概要

チュートリアル「15. 浮動小数点演算、その問題と制限」の本文に誤訳がある。

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3.12/tutorial/floatingpoint.html#:~:text=%E3%81%9F%E3%81%A8%E3%81%88%E3%81%B0%E3%80%8110%E9%80%B2%E6%95%B0%20%E3%81%AE%E5%88%86%E6%95%B0%E3%81%A7%E3%81%AF%200.625%20%E3%81%AF%201/10%20%2B%202/100%20%2B%205/1000%20%E3%81%A8%E3%81%84%E3%81%86%E5%80%A4%E3%82%92%E6%8C%81%E3%81%A1

https://github.com/python/python-docs-ja/blob/a5b1e3ca06d792b512b5d5f82b925162e298a048/tutorial/floatingpoint.po#L42

# 問題の詳細

たとえば、10進数 の分数では 0.625 は **1**/10 + 2/100 + 5/1000 という値を持ち

# 修正案

たとえば、10進数 の分数では 0.625 は **6**/10 + 2/100 + 5/1000 という値を持ち

（わかりやすい翻訳ありがとうございます）

**Comment by tenmyo** [comment]
こんにちは。ご報告ありがとうございます。助かります。
最新ドキュメントで修正しました。
ご確認いただき、問題なければクローズをお願いします。

原文で`0.125`->`0.625`、`1/10 + 2/100 + 5/1000` -> `6/10 + 2/100 + 5/1000` と変わっていたのですが、日本語訳に一部しか反映できていなかったようです。直後の２進数も同様だったため、合わせて直しています。

**Comment by shun-yamazaki** [comment]
ご対応ありがとうございます！
