### ISSUE TITLE
Python チュートリアル venv 中のtypo「python -m pip freeze````pip freeze は」

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#982]
# 概要

バッククォートが表示されている箇所がありました

```
python -m pip freeze````pip freeze はインストールされたパッケージ一覧を、python -m pip install が解釈するフォーマットで生成します。
```

# 問題のある箇所 (URLで指定すること)

https://docs.python.org/ja/3/tutorial/venv.html#managing-packages-with-pip

# 問題の詳細
原文 https://docs.python.org/3/tutorial/venv.html#managing-packages-with-pip
>python -m pip freeze will produce a similar list of the installed packages, but the output uses the format that python -m pip install expects.

これに合わせるのがよさそうに思いました

# 修正案

python -m pip freeze はインストールされたパッケージ一覧を、python -m pip install が解釈するフォーマットで生成します。

**Comment by tenmyo** [comment]
いつもご報告ありがとうございます。助かります。訳す際に一部原文が誤って混ざってしまったようです。
最新ドキュメントで修正しました。
ご確認いただき、問題なければクローズをお願いします。

**Comment by ftnext** [comment]
修正ありがとうございました。確認しました
