### ISSUE TITLE
上級ロギングチュートリアル「ライブラリのためのロギングの設定」の一文の改善提案

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#987]
# 概要
「ライブラリのためのロギングの設定」の第2段落より

>このハンドラは何も処理しないというだけで、全てのライブラリイベントに対してハンドラが見つかるので、メッセージが表示されることを防げます。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/howto/logging.html#library-config

# 問題の詳細
英語
https://docs.python.org/3/howto/logging.html#library-config
>This avoids the message being printed, since a handler will always be found for the library’s events: it just doesn’t produce any output.

前文と続けて読むと引っかかるように感じました
>何らかの理由で、ロギング設定がなされていないときにメッセージを表示 させたくない なら、あなたのライブラリのトップレベルロガーに何もしないハンドラを取り付けられます。
>If for some reason you don’t want these messages printed in the absence of any logging configuration, you can attach a do-nothing handler to the top-level logger for your library. 

直訳
何もしないハンドラを取り付けることはメッセージを表示しないようにします。
全てのライブラリイベントに対してハンドラが見つかりますが、ハンドラは何も**出力**しません

太字にした部分ですが、「処理」ではなく「出力」が原文に即すと考えます

# 修正案

現行の訳に直訳の要素を入れ込む案

(何らかの理由で、ロギング設定がなされていないときにメッセージを表示 させたくない なら、あなたのライブラリのトップレベルロガーに何もしないハンドラを取り付けられます。)
全てのライブラリイベントに対してハンドラが見つかりますが、このハンドラは何も出力しないので、メッセージが表示されないようになります。

**Comment by methane** [comment]
ありがとうございます。英語特有の言い回しを直訳すると日本語として不自然なので、次のように修正してみました。

> 何らかの理由でロギング設定がなされていないときにメッセージを表示 *させたくない* のであれば、ライブラリのトップレベルのロガーに何もしないハンドラを取り付けられます。ライブラリの全てのイベントに対してそのハンドラが見つかるので、メッセージが表示されなくなります。ライブラリのユーザーがアプリケーションのためにロギングを設定する場合、おそらくハンドラが追加され、そしてレベルが適切に設定された場合に、ライブラリコード内でのロギングの呼び出しは通常通りそのハンドラに出力を送るようになります。

**Comment by ftnext** [comment]
ご対応いただきありがとうございます。
よさそうに思われました。
ドキュメントに反映され次第、このissueはcloseします

**Comment by ftnext** [comment]
反映を確認しました。ご対応いただき、ありがとうございました
