### ISSUE TITLE
loggingのドキュメント、LoggerのhasHandlers()メソッドの翻訳中のtypo修正

### ISSUE THREAD

**Issue by ftnext** [python-doc-ja/python-doc-ja#988]
# 概要
>そのために、このロガーとロガー階層におけるその祖先についてハンドラ探していきます。

# 問題のある箇所 (URLで指定すること)
https://docs.python.org/ja/3/library/logging.html#logging.Logger.hasHandlers

# 問題の詳細
助詞が落ちていることに気づきました

# 修正案

そのために、このロガーとロガー階層におけるその祖先についてハンドラ**を**探していきます。

**Comment by methane** [comment]
修正しました。
